### ISSUE TITLE
CLRMD fails to load coreclr 7.0 dump - PEImage.Read() doesn't update offset

### ISSUE THREAD

**Issue by noahfalk** [microsoft/clrmd#1038]
I was helping @Maoni0 try to debug a .NET 7 dump today and ran into an issue in CLRMD. In the DAC initialization code there is a point where it is parsing a PEOptionalHeader for coreclr.dll and it issues two reads starting at the same file offset. The first one reads a 2 byte magic and the 2nd one reads the entire structure. 
https://github.com/dotnet/runtime/blob/311ecfe43aed24d6ff39834d2761c630c50f36e1/src/coreclr/debug/dbgutil/dbgutil.cpp#L86

The expected behavior is that the first read will return either PE32 or PE32+, then the second read will return the entire structure, again including the PE32 or PE32+ magic bytes. However [PEImage.Read()](https://github.com/microsoft/clrmd/blob/main/src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs#L252) does not update the value of _offset after the first 2 byte read even though the underlying filestream cursor has advanced. When the 2nd read occurs at the same offset SeekTo() determines that _offset == offset so it does not issue a stream.Seek() call. Instead of reading from offset, CLRMD returns bytes read from the stream at offset+2. Once the incorrect data is returned to the DAC parsing fails and DAC initialization fails.

**Comment by leculver** [comment]
I believe this one is already fixed (but not shipped).  I will take a closer look and confirm though.
