### ISSUE TITLE
CLRMD fails to load coreclr 7.0 dump - PEImage.Read() does not apply fixups

### ISSUE THREAD

**Issue by noahfalk** [microsoft/clrmd#1039]
In the same debugging session as https://github.com/microsoft/clrmd/issues/1038 @Maoni0 and I applied a fix for 1038 locally attempting to get further, but we hit a 2nd issue. When the DAC tries to load the DAC table, this memory read comes from the .rdata section of coreclr.dll. The bytes in the file are encoded as a virtual address assuming that coreclr.dll loads at its preferred load address. For example in the case I debugged the preferred load address is 0x180000000 and the first pointer size value of the table is 0x180496438 (RVA=0x496438). When coreclr.dll loads in memory it loads at a different base address and the OS applies fixups to correct these values in memory. In my case coreclr.dll loaded at 0x00007fffd26a0000 so the OS mapped 0x180496438 on disk -> 0x7fffd2b36438 in memory. CLRMD's implementation of the reader does not perform fixups as far as I can tell and incorrectly reports the memory contents to be 0x180496438. Later DAC attempts to dereference the pointer for s_pThreadStore (which isn't the first one, but has the same problem). This fails because the preferred load address VA isn't the correct address in the final memory space. 

We did confirm that taking a full dump works around this issue (presumably because the DacTable bytes were captured in the dump and CLRMD never falls back to use PEImage.Read()). I'm guessing the lack of fixups wasn't an issue in the past because the DacGlobals table used to be encoded as a list of RVAs rather than a list of VAs, but it changed during .NET 7 so that we could use build coreclr.dll without custom binary post-processing steps.

cc @mikem8361 @jkoritzinsky

**Comment by leculver** [comment]
@cshung Reported this one previously, but I haven't gotten to it.

The design of .Net Core 7 (requiring us to parse and apply fixup tables) is a really painful one.  I have not had the time to get around to doing this work as I am not an expert in this side of the Windows loader.  It's on my todo list, but I expect it's going to take time to go figure this out.

Any chance you all would put the full dac table into minidumps?  That would save folks from having to pull apart reloc tables.  Though I suppose we'll have to support it for 7 anyway.

**Comment by mikem8361** [comment]
The SOS has an image mapper that does PE fix ups for dotnet-dump and lldb here: https://github.com/dotnet/diagnostics/blob/2e178a1dfa3d4a0c387924f3db53690c21a069bc/src/Microsoft.Diagnostics.DebugServices.Implementation/ImageMappingMemoryService.cs#L223.

**Comment by leculver** [comment]
Perfect, thank you!
