### ISSUE TITLE
Error in sample url

### ISSUE THREAD

**Issue by rjvdboon** [Microsoft/clrmd#107]
The url for the FileAndLineNumber sample is incorrect in 
https://github.com/Microsoft/clrmd/blob/f82fb8ab820d7acaae53b7223bf6fb3176436b84/pkg/Microsoft.Diagnostics.Runtime.nuspec#L19

It states  https://github.com/Microsoft/clrmd/blob/master/src/FileAndLineNumbers/Program.cs but should be  https://github.com/Microsoft/clrmd/blob/master/src/Samples/FileAndLineNumbers/Program.cs

**Comment by leculver** [comment]
This should be fixed now
