### ISSUE TITLE
The license disorientation

### ISSUE THREAD

**Issue by ww898** [microsoft/clrmd#1073]
Hi there, the `Microsoft.Diagnostics.Runtime.2.4.411901.nupkg` marked as MIT but contains [License-Stable.rtf](https://github.com/microsoft/clrmd/blob/main/src/Microsoft.Diagnostics.Runtime/License-Stable.rtf) file with MICROSOFT SOFTWARE LICENSE TERMS (MICROSOFT .NET LIBRARY) license. Could you please remove `License-Stable.rtf`?

**Comment by leculver** [comment]
Thanks for the heads up!  This is, indeed, a mistake.  It looks like it was pulled in with some engineering work many years back and I (embarrassingly) didn't notice until you posted this issue.  This will be corrected in an upcoming release.
