### ISSUE TITLE
Get ClrValueType similar to !DumpVC

### ISSUE THREAD

**Issue by StevenBonePgh** [microsoft/clrmd#1098]
When dumping a `ClrObject`, and one of the fields is a Value type, one can use `TryReadValueTypeField` with the field name to get the `ClrValueType` from the field. The instance of `ClrValueType` provides `Type.MethodTable` that gets the MT, and the `.Address` to get the address. In WinDbg SOS, you can then use `!dumpvc <mt> <address>` to dump the equal of the `ClrValueType`.

Given the MT and Address, you can use `ClrRuntime.GetTypeByMethodTable` to retrieve the `ClrType`. But from there I am lost as to how to replicate getting an instance of the `ClrValueType` given the address. Is this possible?

As a workaround, I suppose that one could use the `ClrObject.Address` and the `.Offset` of the field to achieve a similar result using different inputs, but would prefer to use similar semantics to SOS's `!dumpvc` if that were possible.

**Comment by leculver** [comment]
Ah this is an oversight on my part.  ClrMD 3.0 will have a public constructor for ClrValueType.  I'll put out a beta release on NuGet of it today with that change.  Full ClrMD 3 release will likely be next month.  Thanks!

**Comment by leculver** [comment]
This is fixed in this build:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.4.416101

There may (or may not) be more changes around this area in 3.0, but for now the 2.4 release should contain what you are looking for.

**Comment by StevenBonePgh** [comment]
Perfect, works as expected. Thank you!
