### ISSUE TITLE
ClrMD should provide local variables

### ISSUE THREAD

**Issue by leculver** [Microsoft/clrmd#11]
ClrMD should expose local variables and arguments in ClrStackFrame.  This was always on my todo list, but it is such a big work item I haven't taken the time to tackle it.

My current plan of action is to use IXClr interfaces as a baseline level of support (this is what SOS uses in !clrstack -a).  These interfaces unfortunately do not work very well, but they sometimes provide working information.  I also plan to implement local variable support based on the ICorDebug's OpenVirtualProcess.  This is only supported in v4 of the runtime and beyond, and there are several issues that will have to be tackled to make it work.  When the right dlls for ICorDebug cannot be found (or are not supported), we will fall back to IXClr's local support.

**Comment by ktrance** [comment]
We have a few windbg extensions that uses ICorDebug, so wouldnt it be possible to get ICorDebug(mscordbi.dll) from the symbol server? Visual studio seems to have this ability as we  normally opens dumps in visual studio, let it download mscordbi, then go back to windbg.

**Comment by leculver** [comment]
Yep that is possible and what I plan to do when implementing this feature. I have it very tentatively marked for work sometime in October but that may be too soon with other work I have to do.

**Comment by leculver** [comment]
Closing this.  This will be wrapped into the new parallel library instead of being part of ClrMD itself.
