### ISSUE TITLE
Where are the release notes for ClrMD 3.0 ?

### ISSUE THREAD

**Issue by CyberSinh** [microsoft/clrmd#1182]
According to [Nuget.org](https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/3.0.442202#release-body-tab), the release notes for ClrMD version 3 should be found here :
_See https://github.com/Microsoft/clrmd/releases for the latest release notes_
But this page contains nothing.

Nor is there any information about v3 in the doc folder:
https://github.com/microsoft/clrmd/tree/main/doc

However, the changes affecting this v3 seem major. For example, the `ClrThread` class has lost many of its properties (`IsBackground`, `IsSTA`, `IsUserSuspended`, `IsAborted`,...).

**Comment by leculver** [comment]
Added here:  https://github.com/microsoft/clrmd/blob/main/doc/ReleaseNotes3.0.md

Feel free to add comments to this thread if you have further questions or I missed something.

**Comment by odalet** [comment]
That maybe should be turned into a proper issue, but I find weird that the enum `ClrThreadState` in not marked `[flags]`. Its values are clearly meant to be bitwise combined. Is it an overlook of the API or intended?

**Comment by leculver** [comment]
Good catch, fixed in #1202.
