### ISSUE TITLE
Threads are not update after flush

### ISSUE THREAD

**Issue by iskiselev** [microsoft/clrmd#1187]
If ClrRuntime created before thread was created, even after flush new thread is not visible.

**Comment by leculver** [comment]
Sorry for the delay.

Hmm, that is surprising.  What version of .Net is your target process?  Is the process running on Windows or Linux?

**Comment by leculver** [comment]
@mikem8361 and @hoyosjs as an FYI.

I worry this might be related to #1169.  Discussion is here:  https://github.com/dotnet/diagnostics/issues/3917.  I'll need more info to narrow it down, but I can go test this on a variety of OS/.Net flavors.

If it ends up being a Flush issue, we don't have a ton of options.  I might be able to completely release all private debugger interfaces and recreate them.  I _think_ that eliminates the cache, but I'm not 100% sure.

**Comment by leculver** [comment]
I finally figured this one out.  We were incorrectly caching ThreadStore and AppDomainStore in 3.0.  This will be fixed in 3.1.
