### ISSUE TITLE
Add Microsoft to the list of owners on NuGet

### ISSUE THREAD

**Issue by bruno-garcia** [Microsoft/clrmd#119]
It's a bit confusing that [the package](https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/) is prefixed `Microsoft.` and is not shown as verified. 

That is because Microsoft is not listed as one of the owners.
![image](https://user-images.githubusercontent.com/1633368/43093235-cd7e5298-8eaf-11e8-95c8-61a3f5caa452.png)

I see now that [Lee Culver](https://github.com/leculver) is a Microsoft employee but still this is quite confusing.

I suggest adding `Microsoft` as one of the owners of the NuGet package to get the verified marker:

![image](https://user-images.githubusercontent.com/1633368/43093316-01e00d9c-8eb0-11e8-8330-13fb4dcb0da1.png)

**Comment by leculver** [comment]
This is done, thank you.
