### ISSUE TITLE
Linux support (for .NET Core/CoreCLR)

### ISSUE THREAD

**Issue by loop-evgeny** [Microsoft/clrmd#122]
Are there any plans to port ClrMd to Linux, so it can work with .NET Core (CoreCLR) processes there?

Even very basic functionality would be useful, e.g. all I need to do is dump all thread stack traces. (It can be done with LLDB + libsosplugin.so, but that's very painful, slow and limited compared to ClrMd.)

**Comment by leculver** [comment]
Yes, the plan is to complete this work in November.  There's a beta-ish build checked into the master branch right now, but it's still got some bugs and corner cases to iron out.  (Not to mention live process attach isn't working yet.)

It's currently in the master branch so I can redo some internal build signing work required to produce signed nuget packages on the new build system.  Feel free to try it now, but I won't consider this work "complete" until we've shipped a NuGet package containing this work.

**Comment by loop-evgeny** [comment]
That's great news, thank you! Looking forward to trying it out when it's a bit more stable.

**Comment by vchirikov** [comment]
@leculver maybe you can publish `pre` version on myget?

**Comment by leculver** [comment]
@vchirikov Daily myget builds are something we are discussing as part of that "internal build work" I mentioned.  Not sure if we are actually going to do that or not.  It's not _quite_ as simple as just throwing a build up there because we like to have stuff signed.  :)

**Comment by vchirikov** [comment]
okay, thanks for your work!

**Comment by wsq003** [comment]
any update?
