### ISSUE TITLE
Old MIT license file is still present in the repo

### ISSUE THREAD

**Issue by 0xd4d** [Microsoft/clrmd#125]
I assume the old `LICENSE` (MIT) file shouldn't be part of the repo now that the new `License.txt` (Apache v2) got merged into master.

https://github.com/Microsoft/clrmd/blob/master/LICENSE

https://github.com/Microsoft/clrmd/blob/master/License.txt

**Comment by leculver** [comment]
Should be fixed with the most recent pull request merge.
