### ISSUE TITLE
Missing methods in ClrMd 2.0

### ISSUE THREAD

**Issue by richardfencel** [microsoft/clrmd#1257]
I recently upgraded via NuGet to ClrMd 2.0 from 1.0 and got a large number of compile errors in my existing 1.0 ClrMd code.   Can someone tell me exactly what methods have been eliminated and how that functionality is now implemented?  For example, ClrType no longer as GetValue() method as well as a Heap.Runtime.ReadMemory().  Another example, ClrInstanceField no longer has a GetValue() method.  Am I supposed to reason out what the replacements might be or is this  documented somewhere?  Thanks for your help.

**Comment by richardfencel** [comment]
I found this useful [link](https://github.com/microsoft/clrmd/issues/567) from a prior incident that answers most of my questions.  If anybody has anything else to contribute, please add.

**Comment by richardfencel** [comment]
What I really need is a link to some ClrMd 2.0 sample code.

**Comment by timcassell** [comment]
> What I really need is a link to some ClrMd 2.0 sample code.

You could take a look at [BenchmarkDotNet's usage](https://github.com/dotnet/BenchmarkDotNet/blob/063d2f0dda0e3a1e0655de666d988d1b76304be4/src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs). Though it might not use all the features you're trying to use.

**Comment by richardfencel** [comment]
Thanks for the recommendation.  

I still have one problem I cannot solve.  I am trying to get the value of a ClrObject when the object type is not known, i.e. I want to convert a ClrObject to an object.  I was able to do that in ClrMd 1.0 at least for primitives.  That is, the following worked:

object myObj = someClrType.Getalue(someAddress);

In ClrMd 2.0 I tried:

ClrObject test = someClrType.Heap.GetObject(someAddress);

This works as well in that it returns a ClrObject (the type is a Double which is correct).  However, I need the actual value of the double.   The debug data for the ClrObject is shown in the attached image.
![Snap6](https://github.com/microsoft/clrmd/assets/11266768/e48c1f86-454c-40ca-b3b9-8387bbee658b)

**Comment by richardfencel** [comment]
Sorry, Getalue() should be GetValue()

**Comment by richardfencel** [comment]
I think the way for me to fix this is to determine first the Clrmd ElementType (e.g. "int") and then call one of the Clrmd generic "read" methods using that type, e.g.  if the "read" method had the signature Readxxxx<>(), then we would call Readxxxx<int>().   

I am going to close this incident now.   Thanks to all those who participated.
