### ISSUE TITLE
ThreadPool EnumerateManagedWorkItems doesn't work with dotnet core dumps

### ISSUE THREAD

**Issue by pakrym** [microsoft/clrmd#131]
It looks for mscorlib.dll that is replaced by `System.Private.CoreLib.dll` in dotnet core.

https://github.com/Microsoft/clrmd/blob/67e34c36107ff09d2e145decfe656b00eaba34e0/src/Microsoft.Diagnostics.Runtime/Desktop/threadpool.cs#L179

**Comment by leculver** [comment]
Thank you for the report.

In fact, a lot of the ThreadPool stuff is in bad shape.  I'm not clear whether all of it fully supports the managed threadpool.  It's to the point where I wish I had either not wrapped the threadpool into clrmd, or put that into a side-library.

I'll add this to the todo list to fix (specifically the assembly issue you point out here), but the longer-term "please make threadpool stuff 100% work...or validate that it's working now" will have to wait a bit.

**Comment by pakrym** [comment]
I'm fine if it gets dropped. 

It doesn't seem to contain anything DAC specific.

**Comment by leculver** [comment]
I have removed Threadpool related code from ClrMD 2.0.  I may revisit some form of threadpool support in the future, but for now I'm closing this issue.  Thanks for the report!
