### ISSUE TITLE
Extract class declarations into separate files, update project structure

### ISSUE THREAD

**Issue by isakiev** [Microsoft/clrmd#132]
I understand reasoning behind the current state of things.
Preserving history and compatibility with existing forks, etc.
But now, when the next major update is coming, maybe it's time to move on? :)

One-class-per-file approach brings so much more satisfaction compared to the current monstrous all-in-one files with 2K+ lines of code wrapped in multiple regions.
Easier to get the whole picture, easier to edit and navigate, easier to detect outdated/duplicated/unused stuff, easier to understand for the newcomers, less conflicts, etc. etc.
Of course, this can be considered as a personal preference, but... maybe I'm not alone? :)

**Comment by leculver** [comment]
That's a pretty reasonable request.  I've been wanting to do this myself for exactly the reasons you outline, but I've avoided it wanting to preserve file history (and also anyone with outstanding code changes/forks of ClrMD are going to have a tough time).

You are right, that with the large influx of changes it's a good time to do this.  I'll see what I can do.

**Comment by leculver** [comment]
Done.

**Comment by isakiev** [comment]
tyvm! :)
