### ISSUE TITLE
How do I get the line number on the stack

### ISSUE THREAD

**Issue by 1996v** [Microsoft/clrmd#135]
When I enumerate the thread stack，How do I get the line number on the stack？
such as ：
0012f380    7c92e514    Program.Main() ( C:/user/code/Console/Program.cs @ 17 )

**Comment by leculver** [comment]
You will have to use a combination of the PDB for that library, a pdb reader (I'm not sure if the one in ClrMD's Utilities namespace is sufficient for this or not, you may have to use the real DIA pdb interfaces), and map the instruction pointer back to an IL instruction to look up the offset in pdbs.

I don't have good example code offhand to share though.

**Comment by discostu105** [comment]
Here is an example code, that gets filename and linennumber: https://github.com/Dynatrace/superdump/blob/master/src/SuperDump/ClrMdExtensions.cs#L105

Of course it's required to have the proper PDB loaded.
