### ISSUE TITLE
Failure to get address of DAC_PAL_InitializeDLL on custom centos build

### ISSUE THREAD

**Issue by crntn** [Microsoft/clrmd#141]
Hi !

We know that the current port of Clrmd to linux is WIP and highly unstable but we are encountering scenarios where lldb + sosplugin are not enough to get to the bottom of our issues.

We tried playing with clrmd in its current state and we noticed that with our custom build of dotnet (v2.1.4 + a few cherry-picked commits) we fail to load the address of "DAC_PAL_InitializeDLL " in DacLibrary https://github.com/Microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/DacLibrary.cs#L74

We solved it locally by loading PAL_InitializeDLL instead. Would you have any pointers as to why this is happening ?

Thanks !

cc @kevingosse who came up with the idea to try to remove the DAC prefix

**Comment by leculver** [comment]
Hmm interesting, @mikem8361 for an FYI.

I don't have a CENTOS VM to test this with right now.  Maybe the code should look like this?

            IntPtr initAddr = DataTarget.PlatformFunctions.GetProcAddress(dacLibrary, "DAC_PAL_InitializeDLL");
            if (initAddr == IntPtr.Zero)
                initAddr = DataTarget.PlatformFunctions.GetProcAddress(dacLibrary, "PAL_InitializeDLL"); 
            
            if (initAddr != IntPtr.Zero)
            {
                IntPtr dllMain = DataTarget.PlatformFunctions.GetProcAddress(dacLibrary, "DllMain");
                DllMain main = (DllMain)Marshal.GetDelegateForFunctionPointer(dllMain, typeof(DllMain));
                int result = main(dacLibrary, 1, IntPtr.Zero);
            }

I'm hesitant to make this change without understanding why the DAC_ prefix is missing there.  I'll try to take a look at it this week if I can.

**Comment by crntn** [comment]
FYI we are using a dotnet runtime we built ourselves with https://github.com/dotnet/source-build. We are actually wondering if the DAC prefix is controlled by a flag during the build .

**Comment by leculver** [comment]
It's definitely possible that this is controlled by a build flag.  Unfortunately the person I would ask to help me track it down is out on vacation for a couple weeks.  Even still, we want ClrMD to work on these custom builds, even when you change the build flags to not do this...

Can you confirm the code snippet above does the right thing on your custom build?

**Comment by crntn** [comment]
Yes the snippet above is working :+1:

**Comment by janvorli** [comment]
The DAC prefix was added recently to solve some problems when libmscoredac.so and libcoreclr.so are loaded into the same process. They both contain PAL.

**Comment by janvorli** [comment]
See here for details: https://github.com/dotnet/coreclr/pull/18904

**Comment by leculver** [comment]
Ahh thank you @janvorli, so it sounds like I should use the non-DAC_ prefixed version in older builds.  Or are you saying these older builds just won't work when you load the dac into a .Net Core process?

**Comment by leculver** [comment]
@crntn I've pushed https://github.com/Microsoft/clrmd/commit/9d848aec96daf6abd6117286b8c86a144cc4afd6 which has that code snippet applied, for now.  I need to do some digging here later to see if everything works as intended, but for now this should be okay as a workaround.

**Comment by janvorli** [comment]
@leculver I have to dig out an old discussion thread to refresh my memory on the issues. But IIRC, the issue was happening on Alpine Linux only (or I should say on any Linux with MUSL standard C library).

**Comment by kevingosse** [comment]
It's probably this one: https://github.com/dotnet/coreclr/pull/18873

**Comment by janvorli** [comment]
Yes, it is the same one as I've mentioned, but this one actually got in. The other one was targeting release 2.1, but didn't get ported there if I recall it correctly.

**Comment by leculver** [comment]
Great thank you @janvorli!
