### ISSUE TITLE
System.OverflowException on Centos in TryGetComponentType for System.Int32[][] obj

### ISSUE THREAD

**Issue by crntn** [Microsoft/clrmd#142]
When reading a dump on Centos from runtime v2.1.4 we get a **System.OverflowException: 'Arithmetic operation resulted in an overflow.'**

This comes from an overflow while casting a ulong to a long in https://github.com/Microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/CoreDumpReader.cs#L163

We were able to move forward by doing the cast in unchecked :
```
           unchecked
            {
                bytesRead = _core.ReadMemory((long)address, buffer, bytesRequested);
                return bytesRead > 0;
            }
```

This bug happened when Getting the component type of this object
```
(lldb) dumpmt 00007f1ce9c42608
EEClass:         00007F1CE93E5558
Module:          00007F1CE9330400
Name:            System.Int32[][]
mdToken:         0000000002000000
File:            System.Private.CoreLib.dll
BaseSize:        0x18
ComponentSize:   0x8
Slots in VTable: 29
Number of IFaces in IFaceMap: 6
```

While investigating with @kevingosse we noticed that we should end up in [GetBasicType](https://github.com/Microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/Desktop/DesktopGCHeap.cs#L171) but the cast exception in [GetTypeByMethodTable](https://github.com/Microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/Desktop/DesktopGCHeap.cs#L168) is preventing us to get there (probably because in that case data.ElementTypeHandle is not a method table)

Could you confirm that this is indeed the correct way to deal with this exception ?

Thanks !

The full stack trace is :
```
>	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.CoreDumpReader.ReadMemory(ulong address, byte[] buffer, int bytesRequested, out int bytesRead) Line 165	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.CoreDumpReader.ReadMemory(ulong address, System.IntPtr ptr, int bytesRequested, out int bytesRead) Line 176	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.DacInterface.DacDataTargetWrapper.ReadVirtual(System.IntPtr self, ulong address, System.IntPtr buffer, int bytesRequested, out int bytesRead) Line 136	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.DacInterface.SOSDac.GetMethodTableData(ulong addr, out Microsoft.Diagnostics.Runtime.DacInterface.MethodTableData data) Line 416	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.Desktop.V45Runtime.GetModuleForMT(ulong addr) Line 264	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.Desktop.V46GCHeap.GetTypeByMethodTable(ulong mt, ulong _, ulong obj) Line 80	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.Desktop.DesktopGCHeap.TryGetComponentType(ulong obj, ulong cmt) Line 168	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.Desktop.V46GCHeap.GetTypeByMethodTable(ulong mt, ulong _, ulong obj) Line 117	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.Desktop.V46GCHeap.GetObjectType(ulong objRef) Line 54	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.HeapSegment.NextObject(ulong objRef, out Microsoft.Diagnostics.Runtime.ClrType type) Line 182	C#
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.HeapBase.EnumerateObjects() Line 189	C#
 	LinuxTest.dll!LinuxTest.Program.Main(string[] args) Line 34	C#

```

**Comment by leculver** [comment]
Can you please make sure your enlistment is synced to current?  I checked in https://github.com/Microsoft/clrmd/commit/f65cdac0910ce6a88cc59480e5891e5dd3c6c6f9 yesterday that should have fixed all of the under/overflow issues.  Please let me know if this still reproduces on that build.

**Comment by crntn** [comment]
Yes we are to current but we were testing and building in debug so we missed this. Thanks !

**Comment by crntn** [comment]
Oups I missed that is also present for Debug, however this is limited for net45 and we are targeting netstandard2.0

**Comment by leculver** [comment]
Ahhh right, can you see if https://github.com/Microsoft/clrmd/commit/3ea01c2ef6a52495b3df1277af49273e6a90fcd7 fixes the problem?  I'm a little fuzzy on the Arcade buildsystem here but I assume the .Net Core build should respect this flag as well.

**Comment by leculver** [comment]
Great, thank you!
