### ISSUE TITLE
How do I get the code line number on the stack?

### ISSUE THREAD

**Issue by 1996v** [Microsoft/clrmd#144]
sorry，I asked the same question two days ago，But that didn't solve my problem。
--------------
[Here's the original problem](https://github.com/Microsoft/clrmd/issues/135)：

When I enumerate the thread stack，How do I get the line number on the stack？
such as ：
0012f380 7c92e514 Program.Main() ( C:/user/code/Console/Program.cs @ 17 )

Both  [leculver](https://github.com/leculver) and  [discostu105 ](https://github.com/discostu105) gave me answers。
Among them， [discostu105 ](https://github.com/discostu105)provided **[clrmdexps.cs](https：//github.com/Dynatrace/superdump/blob/master/src/SuperDump/ClrMdExtensions.cs#L105)**。
I follow **clrmdexps.cs** to do，but I had some problems。
(I'm anxious to get the line number now, so I raised this question in [superdump](https://github.com/Dynatrace/superdump/issues/135) too，sorry。)
so，When I called the method from the link, it was just return the last column of PdbSequencePoint。
GetSourceLocation(this ClrStackFrame frame) =>call FindNearestLine()

```
private static SDFileAndLineNumber FindNearestLine(PdbFunction function, int ilOffset) {
			int distance = int.MaxValue;
			var nearest = new SDFileAndLineNumber();

			foreach (PdbSequencePointCollection sequenceCollection in function.SequencePoints) {
				foreach (PdbSequencePoint point in sequenceCollection.Lines) {
					int dist = (int)Math.Abs(point.Offset - ilOffset);
					if (dist < distance) {
						nearest.File = sequenceCollection.File.Name;
						nearest.Line = (int)point.LineBegin;
					}
				}
			}

			return nearest;
		}
```

Let's say I have a method ：Program.Main()

```
1.    static void Main(string[] args)
2.    {
3.            while (true)
4.                  Console.WriteLine(1);
5.    }
```

FindNearestLine method will always return to line=5 。

I want to know how to find out where the code is running in that stackframe。

thanks,thanks,thanks,thanks,thanks,thanks

**Comment by leculver** [comment]
You probably have an issue with ilOffset being off.  Remember that if the frame isn't the very topmost on the stack, then your instruction pointer for a frame will be the **return address**, not the instruction you are currently executing.

Here's the code:
```
#1 using System.Threading;
#2
#3 class Program
#4 {
#5     static void Main(string[] args)
#6     {
#7         while (true)
#8             Thread.Sleep(500);
#9     }
#10 }
```

Here's the real callstack:

```0:000> kc
00 ntdll!ZwDelayExecution
01 clr!LogHelp_TerminateOnAssert
02 clr!LogHelp_TerminateOnAssert
03 clr!GetMetaDataPublicInterfaceFromInternal
04 mscorlib_ni!System.Threading.Thread.Sleep(Int32)
05 TestPdb!Program.Main(System.String[])   <== This is not the topmost frame, ClrStackFrame.InstructionPointer will be the return address
06 clr
```

Here's what the IL map/Pdb ClrStackFrame.InstructionPointer says:

```
ClrStackFrame.InstructionPointer: 17e0474
ILMap:
    il:fffffffe ip:[17e0448-17e0465]
    il:0 ip:[17e0466-17e0466]
    il:1 ip:[17e0467-17e0469]
    il:3 ip:[17e046a-17e046e]
    il:8 ip:[17e046f-17e0473]
    il:d ip:[17e0474-17e0474]
    il:e ip:[17e0475-17e0481]
    il:10 ip:[17e0482-17e04a1]

PDB map:
    Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbSource:
        line:6-6 il:0
        line:16707566-16707566 il:1
        line:8-8 il:3
        line:7-7 il:e
```

So looking at this output, we'd subtract one from the IP (since it's a return address) to get an address inside the previous instruction.  Looking up 17e047**3**, you see that this is IL offset 8.  In the PDB map the closest to il:8 is il:3 or il:e, and so we pick il:3 since: abs(8-**3**) < abs(8-**e**).  According to the pdb map, il:3 is line 8, which is Thread.Sleep(500), which is correct.



I generated the output above with this program:

            using (DataTarget dt = DataTarget.LoadCrashDump(@"C:\Users\leecu\Documents\Visual Studio 2017\Projects\TestPdb\bin\Debug\dbg.dmp"))
            {
                ClrRuntime runtime = dt.ClrVersions.Single().CreateRuntime();

                ClrStackFrame frame = runtime.Threads.SelectMany(t => t.StackTrace).Where(f => f.Method?.Name.Contains("Main") ?? false).Single();

                Console.WriteLine($"ClrStackFrame.InstructionPointer: {frame.InstructionPointer:x}");

                Console.WriteLine($"ILMap:");
                foreach (var entry in frame.Method.ILOffsetMap)
                    Console.WriteLine($"    il:{entry.ILOffset:x} ip:[{entry.StartAddress:x}-{entry.EndAddress - 1:x}]");

                Console.WriteLine();
                using (PdbReader reader = new PdbReader(@"C:\Users\leecu\Documents\Visual Studio 2017\Projects\TestPdb\bin\Debug\TestPdb.pdb"))
                {
                    PdbFunction pdbFunction = reader.GetFunctionFromToken(frame.Method.MetadataToken);

                    Console.WriteLine($"PDB map:");
                    foreach (PdbSequencePointCollection pointCollection in pdbFunction.SequencePoints)
                    {
                        Console.WriteLine($"    {pointCollection.File}:");
                        foreach (PdbSequencePoint point in pointCollection.Lines)
                        {
                            Console.WriteLine($"        line:{point.LineEnd}-{point.LineEnd} il:{point.Offset:x}");
                        }
                    }
                }
            }
