### ISSUE TITLE
Docs on getting the Dac from a symbol server

### ISSUE THREAD

**Issue by drewnoakes** [Microsoft/clrmd#149]
The Getting Started docs state:

> See the later Getting the Dac from the Symbol Server section below for how to do this.

https://github.com/Microsoft/clrmd/blob/master/Documentation/GettingStarted.md#what-do-i-need-to-debug-a-crash-dump-with-clrmd

I cannot find the referenced _Getting the Dac from the Symbol Server_ section.

**Comment by leculver** [comment]
Thanks, this was probably lost somewhere along the way.  I've add the section to the document.  Thanks!

**Comment by drewnoakes** [comment]
Thanks very much. That's nice and clear.
