### ISSUE TITLE
Use of IList<T>

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/clrmd#163]
Several types use `IList<T>` to expose collections of data. `ClrType` is a good example.

There are a few issues with this:

- Enumerating them requires allocating an enumerator
- They're mutable
- Calls are virtual

The mutability thing is not a problem when everyone is well behaved, but the allocation/virtual points are only avoidable by casting to `List<T>` or `T[]`, which is suboptimal and risky.

Would you consider a dependency upon `System.Collections.Immutable` and using `ImmutableArray<T>` in place of `IList<T>`? When used well, it provides the performance and compactness of arrays with immutability and essentially zero overhead. It would be a breaking API change however.

**Comment by leculver** [comment]
When was ImmutableArray added?  Currently ClrMD is supported as far back as CLR 4.5 (and needs to be carried without dependencies on Desktop CLR).  Was ImmutableArray around in 4.5?

I do wish I hadn't used IList<T> so long ago, but I worry it's too big of a breaking change to modify these return types.

**Comment by drewnoakes** [comment]
I'm pretty sure it's always been distributed as a NuGet package. The latest release supports `net45`.

https://www.nuget.org/packages/System.Collections.Immutable

https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs

`ImmutableArray<T>` does implement `IList<T>` which would ease a transition, however it's a struct which means boxing and, more significantly, no `null` value (you use `IsDefault` or `IsDefaultOrEmpty` properties). For APIs that can never return `null` this might not be such a big deal.

I get the importance of backwards compatability.

If it's something you wanted to try out, I would be willing to help.

**Comment by leculver** [comment]
That runs into the second part of the problem, ClrMD on desktop CLR is supposed to run without any dependencies (not having to carry other DLLs).  There's still a small window of time we could probably make breaking changes for 1.0 of clrmd (especially since I need to do a large round of bugfixing).  Let me think about this.

**Comment by drewnoakes** [comment]
If it helps, the actual implementation of `ImmutableArray` is very simple and could be easily replicated within ClrMD directly to avoid any dependencies. There's no need for the other immutable collection types if you just want the immutable array container. Again, I'm happy to spike this out if you feel it might be worth it. No worries either way.

**Comment by leculver** [comment]
Ah good point.  Sure, if it's not too much work.  Let's see what this looks like putting an immutable array type into ClrMD.  I wouldn't mind the change so much if it implements IList to ease the transition.

**Comment by leculver** [comment]
Fixed in ClrMD 2.0.

**Comment by drewnoakes** [comment]
Fantastic, thanks.

**Comment by NextTurn** [comment]
It seems that the fix was to change `IList<T>`s to `IReadOnlyList<T>`s, so the issues with enumerator allocations and virtual dispatching still remain. Since ClrMD 2.0 can carry dependencies, how do you feel about `ImmutableArray<T>`?

**Comment by leculver** [comment]
I'd be happy using ImmutableArray.  I'll reopen this issue to track it.
