### ISSUE TITLE
V35MethodDescData and V2MethodDescData field layout changed

### ISSUE THREAD

**Issue by 0xd4d** [Microsoft/clrmd#164]
Seems like the big refactoring turned some of the fields into getter props and now the fields aren't in the same order as before.

It's possible that some other structs were changed too. These are the only ones I noticed when investigating a crash.

**Comment by 0xd4d** [comment]
I checked latest master against CLRMD 1.0 nuget package, and these are the only *struct*s that have a different field layout.

Microsoft.Diagnostics.Runtime.Desktop.LegacyDomainLocalModuleData
Microsoft.Diagnostics.Runtime.Desktop.LegacyObjectData
Microsoft.Diagnostics.Runtime.Desktop.V2MethodDescData
Microsoft.Diagnostics.Runtime.Desktop.V2ThreadPoolData
Microsoft.Diagnostics.Runtime.Desktop.V35MethodDescData
Microsoft.Diagnostics.Runtime.Desktop.V4ThreadPoolData

**Comment by leculver** [comment]
Thanks for the report, that's a pretty bad mistake on my part to not notice that.  I will revert them later this week.  @isakiev as an FYI.

**Comment by isakiev** [comment]
@0xd4d @leculver thank you for pointing this out.
I'll check if any other structures are affected and will create a PR.
The team has been informed about the code cleanup issue.
