### ISSUE TITLE
Add APIs to get name of JIT helper funcs and method tables

### ISSUE THREAD

**Issue by 0xd4d** [Microsoft/clrmd#165]
A feature request to get names of some things that is useful when showing a disassembly of a method body.

These could be exposed on ClrRuntime.

string GetJitHelperFunctionName(ulong address): use DacRequests.JIT_HELPER_FUNCTION_NAME & GetJitHelperFunctionName()

string GetMethodTableName(ulong address): use GetNameForMT()

They should return null if input isn't a jit helper function or a method table.

I can send a PR if needed.

**Comment by leculver** [comment]
Sounds reasonable, added to my todo list.  I need to tackle all the bugs introduced in v1.0 first.
