### ISSUE TITLE
AccessViolationException when getting a .NET 3.5 method

### ISSUE THREAD

**Issue by 0xd4d** [Microsoft/clrmd#166]
I'm using the latest master.

This happens when creating a new MetaDataImport. It gets a LegacyMetaDataImport value, but it seems that it has already been Release()'d and an exception (usually AccessViolationException) is thrown when calling queryInterface() in CallableCOMWrapper.

When hacking the code so it never calls RegisterForRelease(), the program works.

This happens when a ClrMethod gets created. Runtime = CLR35, x86 and x64.

**Comment by leculver** [comment]
This _might_ be the struct related problem that @isakiev just fixed.  I am doing some 3.5 related testing this week (or weekend) and will be sure to test this as well.

**Comment by leculver** [comment]
Nope, I was wrong.  Fixed in https://github.com/Microsoft/clrmd/commit/8e1c8235a00f0d2be17d859128a105858110565e.
