### ISSUE TITLE
What is the strategy for mocking entities in unit tests?

### ISSUE THREAD

**Issue by mitikov** [Microsoft/clrmd#175]
Hi @leculver ,

Straightforward approach with mocking frameworks (like NSubstitute) leads to type generation problems around **internal abstract** modifiers:

```
 System.TypeLoadException : Method 'get_GCDesc' in type 'Castle.Proxies.ClrTypeProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69' does not have an  Stack Trace:
      at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
      at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
      at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
      at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.CreateType(TypeBuilder type)
      at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
```
The solutions I'm aware of :

1. Avoid `internal` access modifier in **public abstract** classes, [example - ClrType.GCDesc]( https://github.com/Microsoft/clrmd/blob/8afa38daf34bdbfc3846c3cce555e49761306446/src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs#L16)
1. Define `InternalsVisibleTo` attribute on ClrMD 
1. Rely on [various access-level hacks](https://www.strathweb.com/2018/10/no-internalvisibleto-no-problem-bypassing-c-visibility-rules-with-roslyn/) disrespecting internal
1. Custom API consumers must mimic ClrMD abstraction - a wrapper around ClrMD abstractions

Could you please share your vision on how unit testing is expected to be done around ClrMD.

Thanks.

**Comment by zvirja** [comment]
BTW, you can also try to change access to [`protected internal`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected-internal), which is the less evil as to me and should still help 😉

**Comment by leculver** [comment]
Merged.

**Comment by mitikov** [comment]
@leculver The original PR was rolled back - do we want to re-open this issue as well?

Thanks.

**Comment by mitikov** [comment]
New PR #191 adding UnitTests project created.
