### ISSUE TITLE
Need to ship ClrMD 1.0.1

### ISSUE THREAD

**Issue by leculver** [Microsoft/clrmd#186]
Just giving an update (since I don't have twitter or other ways to communicate).  I'm essentially where I want to be to ship 1.0.1, having cleaned up a lot of v3.5 issues.  However, the internal build server that produces signed NuGet packages is broken again.  I have to find someone who knows how to fix it, but a lot of people take the last few weeks of December off for vacation.

I will ship a new version as soon as I'm able.

**Comment by leculver** [comment]
I've shipped this today as 1.0.2 (there was briefly a 1.0.1, but it was marked prerelease).

**Comment by discostu105** [comment]
I've just deployed 1.0.2 and verified that #157 and #158 have been fixed.

Thanks a lot!
