### ISSUE TITLE
Cannot get ClrRuntime from ClrThread

### ISSUE THREAD

**Issue by Zvirja** [Microsoft/clrmd#19]
There is no way in API to get `ClrRuntime` object for given `ClrThread` object.

We should extend API to provide cross-reference.

**Comment by Zvirja** [comment]
The same goes for the `ClrAppDomain` type.

I'm not sure whether this is by design or it makes sense to register that as issues/wishes.

**Comment by leculver** [comment]
Fixed in this changeset:  https://github.com/Microsoft/clrmd/commit/5b77b22cf45be088da4b41115dcdb31805660a84
