### ISSUE TITLE
Create parallel library for ICorDebug and the "clrobject" branch

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#203]
I plan to create a secondary library, something like Microsoft.Diagnostics.Runtime.CorDebug (or more generic like Microsoft.Diagnostics.Runtime.Extensions).  I have a set of code that I would like to fully support, but that doesn't belong in ClrMD proper.  This would ship in its own NuGet package.

The primary thing this library is for is an ICorDebug bridge.  This will let a developer initialize ICorDebug (the public debugging API for CLR) and use it along side of ClrMD.  This is a very useful thing to have available (and I don't want end users to have to build this bridge themselves), but that really don't belong in ClrMD proper.

**Comment by MattParkerDev** [comment]
@leculver was this ever done? :)

**Comment by leculver** [comment]
No, I removed this chunk of code from the library a while back but did not create a secondary library to house ICorDebug wrappers.  It's not something I plan to do anymore.

**Comment by MattParkerDev** [comment]
All good, thanks :) For anyone else curious, https://github.com/microsoft/clrmd/commit/41a9e40c72c3eb7eaf005e392f3b65357bed345c is the commit removing the ICorDebug wrappers.
