### ISSUE TITLE
Blocking Objects: Clean up, fix, or mark obsolete

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#205]
The "blocking objects" feature was a poor idea to add to ClrMD.  As I remember it, there's nothing unique this surface area provides.  It's something that should be implemented by a consumer of ClrMD and not ClrMD itself.

I plan to go through that code and see if there's anything that ClrMD is actually uniquely providing as a building block.  From there we need to reconsider whether that should be in a different surface area or to just remove it entirely in a future release.

**Comment by leculver** [comment]
Removed in ClrMD 2.0.

**Comment by akrock** [comment]
@leculver We were actually utilizing this in the older API's and are now trying to upgrade to 2.x. 

Since this was removed I assume that the following held true: 
> It's something that should be implemented by a consumer of ClrMD and not ClrMD itself.

Can you point us in the direction of where the relevant code was so that we can build something like this as the consumer?
