### ISSUE TITLE
ClrMethod.IL returns null

### ISSUE THREAD

**Issue by ZQiu233** [Microsoft/clrmd#217]
Here's my code
using (DataTarget data = DataTarget.AttachToProcess(Process.GetProcessesByName("Terraria").Single().Id, 5000, AttachFlag.Invasive))
			{
				var runtime = data.ClrVersions[0].CreateRuntime();
				var heap = runtime.Heap;
				var method = heap.GetTypeByName("Terraria.Main").Methods.First(t => t.Name == "Update");
				Console.WriteLine(method.IL);
			}
method.IL is null but method.ILOffsetMap isn't null
It may be a bug?

**Comment by sgkoishi** [comment]
Is it a COM related problem?

Following code throw error: System.InvalidCastException: 'Unable to cast object of type 'Microsoft.Diagnostics.Runtime.DacInterface.MetaDataImport' to type 'Microsoft.Diagnostics.Runtime.ICorDebug.IMetadataImport'.'

```chsarp
using (var dataTarget = DataTarget.AttachToProcess(Process.GetCurrentProcess().Id, 2000, AttachFlag.Passive))
{
    var rt = dataTarget.ClrVersions.Single().CreateRuntime();
    var import = rt.Heap.GetTypeByName("ClrMDProgram").Module.MetadataImport;
    var imeta = (IMetadataImport) import;
}
```

**Comment by leculver** [comment]
These are two different issues.

@ZQiu233:  What does ClrMethod.CompilationType return?  Is it MethodCompilationType.None?  If so then that method probably hasn't been compiled yet.

@sgkoishi: That's a different issue, so feel free to file an issue about that.  I can probably give you a way to get at the underlying COM object so you can do this conversion.  The wrapper for `IMetadataImport` in ClrMD is going away soon, so you'll either have to use the `MetaDataImport` class, or copy/paste the `IMetadaImport` interface into your project.

**Comment by sgkoishi** [comment]
> 
> 
> These are two different issues.
> 
> @ZQiu233: What does ClrMethod.CompilationType return? Is it MethodCompilationType.None? If so then that method probably hasn't been compiled yet.
> 
> @sgkoishi: That's a different issue, so feel free to file an issue about that. I can probably give you a way to get at the underlying COM object so you can do this conversion. The wrapper for `IMetadataImport` in ClrMD is going away soon, so you'll either have to use the `MetaDataImport` class, or copy/paste the `IMetadaImport` interface into your project.

Thanks for reply.
@ZQiu233 and I start from a similar point, both of us find that the il of methods is null.

We first find DesktopMethod.get_IL call InitILInfo
https://github.com/Microsoft/clrmd/blob/6095cd0fbff574454e7af8a4731a9f626e6924be/src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopMethod.cs#L186-L195

And inside it, it's the code I ref
https://github.com/Microsoft/clrmd/blob/6095cd0fbff574454e7af8a4731a9f626e6924be/src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopMethod.cs#L197-L204

Here `module?.MetadataImport` is always not a IMetadataImport - that's why get_IL returns null.

**Comment by leculver** [comment]
Ahh got it.  I will take a look.

**Comment by ZQiu233** [comment]
To your question.I'm sure that the method has already been compiled,otherwise I would have not used this method.

I've found out all possible return value of ClrMethod.IL I got.They're all instances of MetaDataImport instead of IMetaDataImport.
Then I changed IMetaDataImport in the code of DesktopMethod.InitILInfo into MetaDataImport and it works well.
