### ISSUE TITLE
ClrMethod ILOffsetMap doesn't return correct method end offset

### ISSUE THREAD

**Issue by Zhentar** [microsoft/clrmd#231]
The code slightly misunderstands the situation:
```cs
// There seems to be a bug in IL to native mappings where a throw statement
// may end up with an end address lower than the start address.  This is a
// workaround for that issue.
if (map[i].StartAddress > map[i].EndAddress)
```
What is actually happening is that the CLR structure only stores the start address for each offset;  `IXCLRDataMethodInstance::GetILAddressMap` calculates each end offset from the following start offset. Because there is no following start for the final offset, it just sets an end offset of 0, leaving you to calculate it yourself from the size of the function.

I believe the EnumExtents methods on IXCLRDataMethodInstance can be used to determine the total size of the function. Alternatively, it appears that `ICorDebugCode::GetILToNativeMapping` does the calculation itself.

**Comment by leculver** [comment]
Fixed, thanks for the report!
