### ISSUE TITLE
How can I get the unmanaged stacktrace on clrThread 

### ISSUE THREAD

**Issue by skybook888** [Microsoft/clrmd#237]
I wanna to parse a stackoverflow exception on linux
i found the recursion stacktrace on the unmanaged side. 
(by using lldb with sos plugin and use dumpstack command)

I wanna to do this by clrmd so i can check the exception automaticly。
but i cannot get the unmanage stack。
Is there any thing I can do？

**Comment by leculver** [comment]
ClrMD is only designed for inspecting CLR's data structures using the internal diagnostic apis (libmscordac*.*).  That means we actually don't do anything like native (unmanaged) stack unwinding anywhere in the library.  You will have to build a library (or use LLDB's plugin model) to pull apart the native side of things.
