### ISSUE TITLE
Desktop Runtime EnumerateMemoryRegions Never includes JIT Heaps

### ISSUE THREAD

**Issue by Zhentar** [microsoft/clrmd#258]
In https://github.com/Microsoft/clrmd/blob/18dd6649d85da782617dd73002cdb39d4940c9db/src/Microsoft.Diagnostics.Runtime/src/Desktop/V45Runtime.cs#L331-L332

Only Unknown heap types will be returned by EnumerateJitHeaps, and EnumerateMemoryRegions ignores unknown heaps. So I'm guessing that's supposed to be `==`.

**Comment by Zhentar** [comment]
Though I guess it doesn't matter much because SOS returns nulls for the heap regions 😩

**Comment by Zhentar** [comment]
It's because it's returning pointer to the first field of the heap, I guess; subtracting one pointer from the address for loader heap types allows it to correctly return the heap's allocation.

Also this:

https://github.com/Microsoft/clrmd/blob/18dd6649d85da782617dd73002cdb39d4940c9db/src/Microsoft.Diagnostics.Runtime/src/Desktop/V45Runtime.cs#L336-L337

Should be indexing with `j`

**Comment by leculver** [comment]
Not a ClrMD bug, but I will investigate fixing this in the CLR runtime in the future.  Leaving this issue open to remind me to go take a look.

**Comment by leculver** [comment]
This is tracked via https://github.com/dotnet/diagnostics/issues/1108.
