### ISSUE TITLE
"Failure loading DAC" in ClrInfo.CreateRuntime() when connecting to a mini dump.

### ISSUE THREAD

**Issue by baal2000** [microsoft/clrmd#259]
On a Windows Serer 2016 system, when attaching to a mini-dump created as

```
C:\SysInternals\procdump.exe -mm -n 1 SomeProcessName.exe C:\temp\testDump.dmp -accepteula 
```

a call to 
```
DataTarget.ClrVersions.Single().CreateRuntime()
```
fails with the error:

"Failure loading DAC: CreateDacInstance failed 0x80131c4f" that points to 
[CORDBG_E_MISSING_DEBUGGER_EXPORTS](https://github.com/dotnet/coreclr/blob/2ab76fe4fb75af98f470650c939f79c569c729a3/src/inc/corerror.xml#L2138): The debuggee memory space does not have the expected debugging export table.

Tried linking an earlier version of ClrMD and the error was there but look differently: "Could not request common MethodTable list."

Other notes:

- a mini dump of the same application taken on a local Windows 10 system can be successfully attached.
- a full dump of the same application taken on the same server Windows 2016 can be successfully attached.
- the dumped .NET Core process is a "published" application: the application assembly AND all necessary .NET Core assemblies reside in the same folder deployed to a "bare" Windows 2016 system with no .NET Core run-time installed.

Attached are win2016 and win10 dumps of the same dotnet application process: [here](https://drive.google.com/file/d/1lBUXcLJkCRYs-OsOqyFiTI92jGD27GL4/view?usp=sharing)

Contents:
- win10-mm (no error).dmp: mini dump taken on win 10, can successfully attached to.
- win2016-ma (no error).dmp: full dump taken on win 2016, can successfully attached to.
- win2016-mm (error).dmp: mini dump taken on win 2016, can not be attached to.

Let me know what other information you need. Thanks

**Comment by franklad** [comment]
**Failure loading DAC** is caused when a dump that is collected in machine A is trying to be parsed in machine B. ModuleInfo is a string that is hardcoded in the dump file, and when it gets loaded in the parser, the program tries to create the LocalMatchingDAC based on the hardcoded path, which in this case `C:\\Machine-A\path_to_test.exe\publish` but this path doesn't exist in machine B so it sets it as null, and when that value is null, Failure loading DAC exception gets thrown.

**Fix:**
Create the exact publish path from machine A in machine B and load `mscordaccore.dll`.
For example:  if you collect a dump from test.exe in machine A which resides in `C:\\Machine-A\path_to_test.exe\publish`, you have to create the exact same directory in machine B: `C:\\Machine-A\path_to_test.exe\publish` and load the original `mscordaccore.dll` that got created when the program was published.

**Comment by baal2000** [comment]
Thanks @franklad for his help in investigating the issue. 
FYI @karelz, @leculver    

Our conclusion is that one or more debug dlls in Microsoft Windows Server 2016 (as tested in GCE and VirtualBox) have a bug and as the result, minidumps created by ProcessExplorer (-mm) or ProcDump  from a published .NET Core 2.1 application are corrupted and their stack is not readable. When the dumps are in the process of being parsed the returned error is 
_ERROR_READ_FAULT  May be used to indicate that the device is not sending the correct amount of data_
"Failure to request MethodData, not in JIT code range" message is also added to the header of the corrupted dump files.
An example published file with its dump file is zipped and temporarily placed [here](https://drive.google.com/file/d/1cUOPp93Nc5dIV33WByW9JxjQddJeQnJu)

The issue that started this thread appears to also be rooted in (or affected by) the dump corruption issue and therefore can be closed. It hasn't attracted any interest anyway, as if the issue is unique to our environment pr nobody uses mini-dumps (as opposed to full dumps).
