### ISSUE TITLE
 EnumerateRefsOfObject dose not return all fields

### ISSUE THREAD

**Issue by EranOfer** [Microsoft/clrmd#260]
Hi, 
I am reading the documentations. 

> Why do we need EnumerateRefsOfObject?
You might be wondering why we need EnumerateRefsOfObject at all. As you will see in the next tutorial, you can walk each field in the object and get its value. You could implement this algorithm by walking fields instead. However, EnumerateRefsOfObject is much, much faster. It uses the same algorithm the GC does to get object references out of the object, which is far more efficient than walking fields to look for objects.

I tried to run EnumerateRefsOfObject on one of the System.StackOverflowException and did not receive any fields values, but when I looked with dot memory I saw additional fields 

![image](https://user-images.githubusercontent.com/13414515/55735727-936c8600-5a2a-11e9-892d-efa022d9bcba.png)

I succeeded to get the same value by calling get value with the field name ... am I doing something wrong?
![image](https://user-images.githubusercontent.com/13414515/55736031-38875e80-5a2b-11e9-930b-a40d48c794cb.png)

Thanks Eran

**Comment by leculver** [comment]
EnumerateRefsOfObject only returns _object reference_ fields, not all fields.  The reason for using it is to be 100% sure you find all object references in an object, using the same code the GC does.

This is for building the object graph.  You should use ClrType.Fields instead here.

**Comment by EranOfer** [comment]
Thanks a lot for your help 👍
