### ISSUE TITLE
SIGABRT on Linux when their is a ptrace() failure

### ISSUE THREAD

**Issue by ayende** [microsoft/clrmd#264]
Repro by the following code.
This will fail since the process doesn't have `SYS_PTRACE`, but the problem is that any error that is thrown there will cause an access violation and kill the process.
I believe that the issue is something with the way the code jumps between managed / native codes there that isn't ready to handle exceptions, but I'm not sure

```
try
{
    var dt = DataTarget.AttachToProcess(Process.GetCurrentProcess().Id, 1000, AttachFlag.Passive);
    var runtime = dt.ClrVersions[0].CreateRuntime();
    var st = runtime.Threads[0].EnumerateStackTrace().First();
    Console.WriteLine(st.DisplayString);
}
catch (Exception e)
{
    Console.WriteLine(e);
    Console.WriteLine("Error, died");
}
```

**Comment by leculver** [comment]
How would I test this scenario?  Let's say I have an `Ubuntu 18` and I'm unwilling to install another package...is there a way I can remove SYS_PTRACE from my own process to be able to test this?
