### ISSUE TITLE
ClrMd shouldn't write to the console

### ISSUE THREAD

**Issue by ayende** [microsoft/clrmd#265]
Just a note about what I believe to be debugging code that needs to be removed. 

https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs#L230

https://github.com/microsoft/clrmd/blob/b1c94e5a9643b35f846da16a95f8e0ec63a3e785/src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs#L230

Note that a decision needs to be made whatever about how to work with this.

**Comment by leculver** [comment]
Already fixed, but I did a pass through to make sure nothing was missed.
