### ISSUE TITLE
Cannot read a Windows .dmp where the dmp was taken from a 32-bit process running on a 64-bit computer

### ISSUE THREAD

**Issue by chrispynz4** [microsoft/clrmd#287]
I have a .dmp from a production server which I can't read, despite having the right mscordacwks.dll.

After spending some time stepping through ClrMD and looking at the .net dlls being referenced by the production .exe, I eventually came to the conclusion that the exe from which the dmp was taken was for some reason running in 32-bit mode, despite being on a 64-bit server and built as "Any CPU".

I can't run the program using ClrMD in 32 bit mode because it says the architectures don't match. I can't run in 64 bit mode because it says it can't load assembly when it tries to create the runtime. It seems to me that this might be a bug, where it's being checked against the wrong thing (I'm just guessing). The server has a pointer size of 8 (x64) but the application itself has a pointer size of 4 (x86)?

To test the theory, I tried opening a dmp of a simple application created specifically to run in 32 bit mode on the same 64-bit computer as Visual Studio. It doesn't work. It should be possible for you to reproduce the problem easily in the same way - make a tiny application, run it in 32 bit mode on a 64 bit server, take a dmp and then open the dmp. Alternately I can provide the dmp from the simple application if desired.

However, Visual Studio 2019 is quite happy to open the dmp file and give details of the objects, so it's inherently possible. I need to extract objects in bulk from the dmp, which I can't do manually in Visual Studio because there's too many of them. I could use ClrMD to do it, but it doesn't like the fact that the process was running in 32-bit mode.

Overall, ClrMD is wonderful - thankyou!

**Comment by leculver** [comment]
Unfortunately this isn't a supported scenario.  (Well, "unsupported" here means that I would make it work if I had infinite time.  However, keeping all of the weird crash dump corner cases working properly isn't something I can commit to.)

For CLR dumps, you are always expected to take a crash dump using the same bitness as the target process, and use the same bitness process to debug that crash dump.  So in this case, 32bit process means you need to use a 32bit debugger to generate a 32bit crash dump.  Then use a 32bit process to load clrmd to debug it.

In this case, I think I can get you unblocked to look at the heap, but again this won't be something I will support long term.

**Comment by leculver** [comment]
I've enabled you to work around the problem with this change:  https://github.com/microsoft/clrmd/commit/c16dad7a3d696e6f8124f62da61cedbcc68142bd

(You will need to build ClrMD from source, or wait until I ship a NuGet package.  I don't intend to ship one this week.)

Unfortunately it doesn't work "out of the box" right now.  I don't have a good way of knowing whether a dump is unsupported, so you'll have to use a custom startup path for ClrMD:

    using Microsoft.Diagnostics.Runtime;
    using Microsoft.Diagnostics.Runtime.Interop;
    using System;
    using System.Linq;
    using System.Runtime.InteropServices;

    class Program
    {
        static void Main(string[] args)
        {
            // create debugger
            IDebugClient client = CreateIDebugClient();
            IDebugControl control = (IDebugControl)client;

            // open the dump
            int hr = client.OpenDumpFile(@"test32.dmp");
            AssertOK(hr);

            // attach to the dump
            hr = control.WaitForEvent(DEBUG_WAIT.DEFAULT, uint.MaxValue);
            AssertOK(hr);

            hr = control.SetEffectiveProcessorType(IMAGE_FILE_MACHINE.I386);
            AssertOK(hr);

            using (DataTarget dt = DataTarget.CreateFromDebuggerInterface(client))
            {
                ClrRuntime runtime = dt.ClrVersions.Single().CreateRuntime();
                foreach (var obj in runtime.Heap.EnumerateObjects())
                    Console.WriteLine($"{obj.Address:x} {obj.Type?.Name ?? "error"}");
            }
        }

        private static void AssertOK(int hr)
        {
            if (hr != 0)
                throw new COMException("Error interacting with IDebug*", hr);
        }

        private static IDebugClient CreateIDebugClient()
        {
            Guid guid = new Guid("27fe5639-8407-4f47-8364-ee118fb08ac8");
            DebugCreate(ref guid, out object obj);

            IDebugClient client = (IDebugClient)obj;
            return client;
        }

        [DllImport("dbgeng.dll")]
        public static extern uint DebugCreate(ref Guid InterfaceId, [MarshalAs(UnmanagedType.IUnknown)] out object Interface);
    }

With this you will be able to walk the heap.  I'm not sure if stackwalking can be trusted in this scenario.  We don't need to do a normal stack unwind, but I haven't tested any of this.  Good luck!

**Comment by chrispynz4** [comment]
Thanks!
