### ISSUE TITLE
NativeCode value is zero for methods of structs implementing an interface

### ISSUE THREAD

**Issue by oakio** [microsoft/clrmd#288]
Steps to reproduce:
```csharp
interface IFoo
{
    int f();
}
struct Foo : IFoo
{
    public int f() => 42;
}
```

```csharp
using (var dataTarget = DataTarget.AttachToProcess(Process.GetCurrentProcess().Id, uint.MaxValue, AttachFlag.Passive))
{
    var clrVersion = dataTarget.ClrVersions.First(); // <= {v4.6.27617.04}
    var runtime = clrVersion.CreateRuntime(); // <= V45Runtime
	
    RuntimeHelpers.PrepareMethod(method.MethodHandle);
	
    var handle = (ulong)method.MethodHandle.Value.ToInt64(); // <= 0x00007ffc0607cd40

    ClrMethod clrmdMethodHandle = runtime.GetMethodByHandle(handle);

    ulong nativeCode = clrmdMethodHandle.NativeCode; // <= 0x0000000000000000 ???
}
```

Environment:
- Microsoft.Diagnostics.Runtime version: 1.1.37504
- dotnet version: 2.2.103
- win10-x64

**Comment by leculver** [comment]
There's not enough information here.  What does `method` point to?

**Comment by oakio** [comment]
```csharp
var method = typeof(Foo).GetMethod("f");
```

**Comment by leculver** [comment]
Ah.  I believe this is a quirk of how CLR operates and not a bug in ClrMD.  It looks like due to the fact that there's interface dispatch involved, the CLR runtime generates two slots for the "f" method.  Note that in your repro if you remove IFoo entirely, the repro works.

Unfortunately syncing up reflection and ClrMD is not an easy task because reflection gives you the view of the world as defined by metadata, but ClrMD is giving you a view of the world as the CLR sees it.  In this case CLR chose to create an interface dispatch slot for `f` and trying to match that to ClrMD is tough.

Here was my repro program that demonstrates this:

    static void Main(string[] args)
    {
        using (var dataTarget = DataTarget.AttachToProcess(Process.GetCurrentProcess().Id, uint.MaxValue, AttachFlag.Passive))
        {
            var clrVersion = dataTarget.ClrVersions.First(); // <= {v4.6.27617.04}
            var runtime = clrVersion.CreateRuntime(); // <= V45Runtime

            IFoo ifoo = new Foo();
            ifoo.f();  // ensures this method is JITed
            Foo foo = new Foo();
            foo.f();

            var method = typeof(Foo).GetMethod("f");

            RuntimeHelpers.PrepareMethod(method.MethodHandle);
            var handle = (ulong)method.MethodHandle.Value.ToInt64(); // <= 0x00007ffc0607cd40
            ClrMethod clrMethod = runtime.GetMethodByHandle(handle);

            Console.WriteLine($"{handle:x} {clrMethod.NativeCode:x} {clrMethod.CompilationType} {clrMethod.GetFullSignature()}");
            int methods = clrMethod.Type.Methods.Count(f => f.Name == "f");
            Console.WriteLine($"Number of f methods: {methods}");

            Debugger.Break();  // <-- Write a crash dump here to confirm with sos
        }
    }

Output:

    42
    42
    c94e5c ffffffffffffffff None Foo.f()
    Number of f methods: 2

From SOS we can confirm this:

    0:000> !name2ee * Foo
    Module:      00c94044
    Assembly:    StructMethodTest.exe
    Token:       02000003
    MethodTable: 00c94e78
    EEClass:     00c91414
    Name:        Foo
    --------------------------------------

    0:000> !dumpmt -md 00c94e78
    MethodDesc Table
       Entry MethodDe    JIT Name
    7381ad9c 72dccd68 PreJIT System.ValueType.ToString()
    730aa540 72dccd60 PreJIT System.ValueType.Equals(System.Object)
    73149f98 72dccd88   NONE System.ValueType.GetHashCode()
    73044f2c 72dc8930 PreJIT System.Object.Finalize()
    00ce0468 00c94e5c   NONE Foo.f()
    00ce0470 00c94e68    JIT Foo.f()
