### ISSUE TITLE
All elements in ClrThread.BlockingObjects.Owners are null

### ISSUE THREAD

**Issue by loop-evgeny** [microsoft/clrmd#294]
NuGet package 1.1.46104 on Windows 7 x64, .NET Core 2.1. When I attach to a .NET Core process and inspect ClrThread.BlockingObjects.Owners for each thread the collection has one element that is null, that is, it does not tell me the owner threads. This happens for all threads and all processes I've tried it on.

Also ClrThread.BlockingObjects is sometimes null and sometimes empty, which is a bit confusing - is there a difference between the two states?

**Comment by leculver** [comment]
This feature is unfortunately in a bad state, it's not something that I want to carry forward in ClrMD.  I don't plan to fix issues in this feature so I will mark it obsolete.
