### ISSUE TITLE
"PTRACE_GETREGS returns ffffffffffffffff"

### ISSUE THREAD

**Issue by loop-evgeny** [microsoft/clrmd#295]
When getting the threads and their stack traces for a .NET Core 2.1 process on Linux x64 I get this in the output:

```
PTRACE_GETREGS returns ffffffffffffffff for 42009
PTRACE_GETREGS returns ffffffffffffffff for 42029
PTRACE_GETREGS returns ffffffffffffffff for 42034
PTRACE_GETREGS returns ffffffffffffffff for 42038
PTRACE_GETREGS returns ffffffffffffffff for 42041
PTRACE_GETREGS returns ffffffffffffffff for 42042
PTRACE_GETREGS returns ffffffffffffffff for 42043
PTRACE_GETREGS returns ffffffffffffffff for 42046
```

I don't know what this means. I guess the register values could not be read?

**Comment by leculver** [comment]
@mikem8361 Any ideas?

**Comment by mikem8361** [comment]
This is part of live linux reader that @xinyanmsft added a few months ago.

**Comment by xinyanmsft** [comment]
Hi, @loop-evgeny does the caller has ptrace permission on the .net core process? 
Can you explain a bit in more detail what you are trying to accomplish? That would help me understanding what's going on. Right now this indicates the ptrace call with GETREGS failed. Thanks!

**Comment by loop-evgeny** [comment]
Yes, this happens even when running with sudo. I'm printing the stack trace of every managed thread. The code does something like this:

```
                var dataTarget = DataTarget.AttachToProcess(pid, 5000, AttachFlag.Passive);
                var runtime = dataTarget.ClrVersions[0].CreateRuntime();
                
                foreach (var thread in runtime.Threads)
                {
                    var st = thread.StackTrace; // This is what prints the PTRACE_GETREGS message...
                    // ... print it ...
                }
```

**Comment by xinyanmsft** [comment]
fix merged. thanks!
