### ISSUE TITLE
ClrThread.BlockingObjects property is very slow for a large process

### ISSUE THREAD

**Issue by loop-evgeny** [microsoft/clrmd#296]
For a large process (20GB RAM in my case) getting the `ClrThread.BlockingObjects` property was very slow. If this cannot be made much faster please make it a method instead of a property - I was calling it 3 times under the assumption that it's fast (as properties are generally assumed to only return already available data and not perform expensive operations).

**Comment by leculver** [comment]
Unfortunately this feature has rotted over the years. I highly recommend not using it, or possibly pulling the implementation out and implementing it yourself.

My plan for this feature is to mark it obsolete in 1.0, and remove it in ClrMD 2.0.  If you need to do something like what BlockingObjects is attempting to do, the plan going forward would be to copy the code out of ClrMD into your project and then you can fix bugs as needed.  (If there are internal functions in ClrMD required to implement this successfully we'll make it public when I strip out the code from ClrMD.)
