### ISSUE TITLE
Failed to load dac

### ISSUE THREAD

**Issue by tohghua** [microsoft/clrmd#299]
Zipped dump file:
[https://github.com/tohghua/hgh/blob/master/HttpReq.zip.001](url)
[https://github.com/tohghua/hgh/blob/master/HttpReq.zip.002](url)
[https://github.com/tohghua/hgh/blob/master/HttpReq.zip.003](url)

Code:
using (DataTarget dataTarget = DataTarget.LoadCrashDump(@"c:\HttpReq.DMP"))
{
	ClrInfo runtimeInfo = dataTarget.ClrVersions[0];  
	ClrRuntime runtime = runtimeInfo.CreateRuntime(); 
}

Exception:
Microsoft.Diagnostics.Runtime.ClrDiagnosticsException
  HResult=0x80131500
  Message=Failed to load dac: 0
  Source=Microsoft.Diagnostics.Runtime
  StackTrace:
   at Microsoft.Diagnostics.Runtime.DacLibrary..ctor(DataTarget dataTarget, String dacDll) in D:\test\clrmd-master\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DacLibrary.cs:line 83

Marshal.GetLastWin32Error() returns 1008

What can be the cause?
Thanks!

**Comment by leculver** [comment]
Sorry I didn't get to this when the blobs were up.  There's not enough information here.  If this is still an issue, you can re-send the zip file (and reply here) I should be able to take a look.
