### ISSUE TITLE
Grouping types by AssemblyLoadContext

### ISSUE THREAD

**Issue by raffaeler** [microsoft/clrmd#302]
In the .NET Framework, types can be loaded in different AppDomains.
Now with .NET Core, they can instead be loaded in different AssemblyLoadContexts. Since any outstanding reference to an AssemblyLoadContext can prevent it to be unloaded, it becomes fundamental to diagnose which are the types being loaded in a specific context.

Currently I am diagnosing this kind of issue by analyzing the roots of `System.Reflection.LoadAllocator`, but this is not always enough, since I have to search the first root living in a *different* load context.

Is there any way to identify the Load Context of the objects?

**Comment by mattwarren** [comment]
I don't know if you can do it in CLRMD, but the general process you'd need to follow is nicely outlined in https://github.com/dotnet/coreclr/issues/20166#issuecomment-486888820

**Comment by raffaeler** [comment]
Thanks @mattwar but I have already automated the reasearch of the leak by starting from LoaderAllocator. I created a small demo that just find the statics, and optionally the instances, if any, holding a direct or indirect reference to LoadContext.
The problem is that you need to stop to the first object belonging to a different LoadContext.
Since types can live in more than one context (and in different versions too), it is definitely not trivial to understand which object is where.

**Comment by mattwarren** [comment]
@raffaeler my bad, I mis-understood what you were asking

**Comment by raffaeler** [comment]
No worries at all @mattwar :)

**Comment by leculver** [comment]
Thanks for bringing this issue to my attention.  The ability to solve issues like this will be something I'm adding to ClrMD, but I'm not sure on the timeline yet.

**Comment by raffaeler** [comment]
This is a great news @leculver 
I wish to stay updated on this subject, I just ask you to keep this thread updated as soon as it moves on.
Thanks

**Comment by leculver** [comment]
Is this property in ClrMD 2.0 sufficient for your needs?  https://github.com/microsoft/clrmd/blob/testing/2.0/src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs#L51

Grouping objects by loader allocator should be as simple as:

    var grouping = from obj in heap.EnumerateObjects()
        let allocator = obj.Type.LoaderAllocatorHandle != null ? dataReader.ReadPointerUnsafe(obj.Type.LoaderAllocatorHandle) : 0
        group obj by allocator into g
        select new
        {
            Allocator = g.Key,
            Objects = g
        };

Is that enough to satisfy this issue, or were you thinking of something else?

**Comment by raffaeler** [comment]
@leculver I will make a test asap, but is there any shortcut to get the name of the load context as well?

**Comment by leculver** [comment]
I'm not sure you mean by "name"?  This test generates a collectible type to use: 
 https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs#L344

I added this code to the end of the test:

    foreach (var group in grouping)
    {
        if (group.Allocator != 0)
        {
            ClrObject allocator = heap.GetObject(group.Allocator);
            Debug.WriteLine($"Allocator {allocator}:");

            foreach (ClrObject o in group.Objects)
            {
                Debug.WriteLine($"    {o}");
            }
        }
    }

And it produces this output:

    Allocator System.Reflection.LoaderAllocator 2441c2b5418:
        Microsoft.Diagnostics.Runtime.Tests.TypeTests+CollectibleUnmanagedStruct 2441c2b58e8

Is this what you are looking for?  If not can you point me to some sample code that will set up the process in a state you are looking to debug?

**Comment by NextTurn** [comment]
https://docs.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext.name#System_Runtime_Loader_AssemblyLoadContext_Name

To be able to get the associated `AssemblyLoadContext` of the `LoaderAllocator` is exactly tracked in dotnet/coreclr#20166.

**Comment by leculver** [comment]
Ahh ok, thanks.  You should be able to get to that field through normal ClrMD field walking I think.  Resolving this issue, but please let me know if I missed something.
