### ISSUE TITLE
Unable to download 'mscordacwks' form Microsoft Symbol Server

### ISSUE THREAD

**Issue by IlyaAI** [microsoft/clrmd#305]
Starting from 27.10.2019 we have encountered problem with downloading 'mscordacwks' form Microsoft Symbol Server. The test `SymbolLocatorTests.FindBinaryTest` also fails.
Something changed on MS Symbols Server side? Or this is temporary problem?
//cc:@leculver

**Comment by leculver** [comment]
@IlyaAI Hello!  I'd be happy to help take a look at this, but I need slightly more information.  Can you please find a crash dump that is exhibiting this behavior (a dump in which you are not able to find the dac for) and run this program over it:

    using Microsoft.Diagnostics.Runtime;
    using System;

    class Program
    {
        static void Main(string[] _)
        {
            using (DataTarget dt = DataTarget.LoadCrashDump(@"C:\path\to\dump\not\working\crash.dmp"))
            {
                Console.WriteLine(dt.SymbolLocator.SymbolPath);
                Console.WriteLine();
                foreach (ClrInfo clr in dt.ClrVersions)
                {
                    Console.WriteLine($"{clr.Flavor} {clr.Version}:");
                    Console.Write($"    {clr.DacInfo.PlatformAgnosticFileName} ts:{clr.DacInfo.TimeStamp:x} fs:{clr.DacInfo.FileSize:x}");

                    string localPath = dt.SymbolLocator.FindBinary(clr.DacInfo.PlatformAgnosticFileName, clr.DacInfo.TimeStamp, clr.DacInfo.FileSize, checkProperties: false);
                    if (string.IsNullOrWhiteSpace(localPath))
                        Console.WriteLine($"   NOT FOUND!");
                    else
                        Console.WriteLine($"   found.");
                }
            }
        }
    }

What is the output of this program?

**Comment by aluhrs13** [comment]
The symbol server is experiencing an outage right now and likely the cause of this.
