### ISSUE TITLE
CODING STYLES

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#313]
(If you are not from Mono team) I believe the general conventions are **exposing `protected` properties for `private` fields** instead of exposing `protected` fields.

**Comment by leculver** [comment]
Thanks, I added this to the v2 planning document.  I cannot fix this in 1.0.* since it would be a breaking change.

**Comment by leculver** [comment]
Resolving as complete in testing/2.0.  If you find any protected fields or `protected internal` nonsense please feel free to reply back here or mark it on the pull request https://github.com/microsoft/clrmd/pull/358.  Thanks!

**Comment by NextTurn** [comment]
Actually I'm referring to https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/Common/ObjectSet.cs. I didn't make changes because FxCop doesn't allow array properties.

**Comment by leculver** [comment]
Ah I forgot about ObjectSet.  Yeah that class needs to be cleaned up.
