### ISSUE TITLE
UnauthorizedAccessException on Linux PassiveMode

### ISSUE THREAD

**Issue by weltkante** [microsoft/clrmd#315]
As discussed on dotnet/corefx#42621 I was trying out attaching to a Linux process to dump a stack trace (as the in-proc methods from Desktop Framework are not available), but I'm having issues with security

```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/proc/24461/mem' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.Diagnostics.Runtime.Linux.LinuxLiveDataReader.OpenMemFile()
   at Microsoft.Diagnostics.Runtime.Linux.LinuxLiveDataReader.ReadMemory(UInt64 address, IntPtr buffer, Int32 bytesRequested, Int32& bytesRead)
   at Microsoft.Diagnostics.Runtime.DacInterface.DacDataTargetWrapper.ReadVirtual(IntPtr self, UInt64 address, IntPtr buffer, Int32 bytesRequested, Int32& bytesRead)
   at Microsoft.Diagnostics.Runtime.DacLibrary..ctor(DataTarget dataTarget, String dacDll)
   at Microsoft.Diagnostics.Runtime.DataTarget.ConstructRuntime(ClrInfo clrInfo, String dac)
   at Program.Main(String[] args) in /home/xxx/private/build/guard/Program.cs:line 23
```

OS is Ubuntu 18.04.3 LTS 64 bit and I'm running both the process that is attaching and the one that is attached under the same user (but different shells). I'm not a Linux expert and searching for those dotnet-centric errors is not leading to any results of what to do to get proc/mem access to my own processes.

I'm aware that I'll probably have to give up on PassiveMode and do dumps to avoid torn stack traces, but considering there is no issue explaining how to resolve this security problem I thought I'd create one to document how to get PassiveMode working in case other people run into it.

/cc @leculver

**Comment by leculver** [comment]
I wonder if calling process_vm_readv like PR https://github.com/microsoft/clrmd/pull/304 does would have different (more relaxed) security implications.  I'm not sure if I'll be able to tackle it this week, but I'd like to investigate if this is something we should be doing differently here.

**Comment by NextTurn** [comment]
The permission required by `process_vm_readv` is exactly the same as that required to perform a `ptrace` or read from */proc/[pid]/mem*. `UnauthorizedAccessException` should be a reasonable exception and we just need to document it.

**Comment by weltkante** [comment]
Any idea why I do not have that permission against my own processes and/or how to grant that permission as a non-root user? Do you have any idea/keywords to search for? I've tried but didn't come up with something useable.

Note that I'm migrating an application previously using the `StackTrace(Thread)` constructor for logging unresponsive threads and was told to try this library instead. If this isn't a scenario that can be enabled with standard user rights I'll have to go back to CoreFX/CoreCLR and ask for looking into an alternative approach.

**Comment by NextTurn** [comment]
> Do you have any idea/keywords to search for?

Yes, the `CAP_SYS_PTRACE` capability.

**Comment by NextTurn** [comment]
The best workaround I can think of is to create a dump file with `dotnet-dump` and inspect it. You'll be able to create dumps programmatically if `dotnet-dump` is to be published as Nuget packages. dotnet/diagnostics#343

**Comment by NextTurn** [comment]
The best workaround I can think of is to create a dump file with `dotnet-dump` and inspect it. You'll be able to create dumps programmatically if the dumper is to be published as Nuget packages. dotnet/diagnostics#343

**Comment by NextTurn** [comment]
The best workaround I can think of is to create a dump file with `dotnet-dump` and inspect it. You'll be able to create dumps programmatically if the dumper is published as Nuget packages. dotnet/diagnostics#343

**Comment by weltkante** [comment]
Yes that is an option I came across yesterday as well, it works for my usecase and I'll probably be using this for now. But if dotnet-dump can use proc/pid/mem to read (which it is doing [according to the docs](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md), see implementation details) I should be able to get it working for clrmd ... unless dotnet-dump only works when coreclr is installed machine-wide because it needs to configure file system capabilities on the dump tool?

What I've tried by now is
- do not run my test code from two distinct shells, let the test code start a secondary copy of itself instead (using `Process.Start`)
- I did see [coreclr calling](https://github.com/dotnet/coreclr/blob/master/src/pal/src/thread/process.cpp) `prctl(PR_SET_PTRACER, childpid, 0, 0, 0)` for creating dumps and tried to add a P/Invoke to do the same

Still running into the UnauthorizedAccessException. Its not high priority to resolve since for now I'll go with making a dump and then have clrmd take the stack trace from there, but it'd be nice for the future if this could be figured out and documented how you have to setup your tooling to resolve this.

**Comment by NextTurn** [comment]
The second parameter of the `prctl` signature in your test code is incorrect. The declaration should be

```cs
static extern int prctl(int option, UIntPtr arg2, UIntPtr arg3, UIntPtr arg4, UIntPtr arg5);
```

and the call should be

```cs
prctl(PR_SET_PTRACER, (UIntPtr)p.Id, UIntPtr.Zero, UIntPtr.Zero, UIntPtr.Zero)
```

After the fix it runs well on WSL.

Yes this is a solution worth documenting if the user has full control over the process being inspected (as in your scenario).

**Comment by weltkante** [comment]
Awesome, yes this works and avoids the exception. Thanks a lot for taking time looking into the problem. I should have known better than copy/pasting a P/Invoke call without double checking what they were doing with it, in hindsight its obvious that I was passing a pointer to an integer while coreclr was passing an integer.

Adding PR to document it so the issue can be closed, I'm sure it can be formulated better so feel free to reformulate and discard the PR if you want to.

**Comment by leculver** [comment]
Thanks @NextTurn!
