### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Rondinelly** [microsoft/clrmd#319]
In the header is still:

https://github.com/Microsoft/clrmd/blob/master/Documentation/ClrRuntime.md

Instead of being:

https://github.com/microsoft/clrmd/blob/master/doc/ClrRuntime.md

![header](https://user-images.githubusercontent.com/15785121/69273668-89615700-0bb7-11ea-9b78-e4c4f3c266f8.PNG)

**Comment by leculver** [comment]
Unfortunately I lost the ability to edit the header when they locked down the microsoft repos a while back.  It might take some time to track down who can fix that and get it fixed. =)

**Comment by leculver** [comment]
Immo got it, thanks for the report!
