### ISSUE TITLE
ClrVersion reports Visual Studio version instead of clr.dll version

### ISSUE THREAD

**Issue by DianaKoenraadt** [Microsoft/clrmd#38]
Having made several memory dumps on the same machine in one run, the last memory dump, when reading it using Microsoft.Diagnostics.Runtime, reports version v12.0.52512.00, which seems to be the Visual Studio version, rather than the clr.dll version of the machine (4.0.30319.34209) (that all other memory dumps report)

My main issue here is that I cannot seem to find the _exact_ place in code in CLRMD where the version number of clr.dll is actually parsed/read/extracted. So my issue is twofold:
- Wrong clr.dll version is reported
- Cannot find location in code where the version number is extracted

**Comment by leculver** [comment]
Sorry for not responding to this when you filed it.  I believe this issue should be fixed in more recent versions of ClrMD.  I'm happy to take a fresh look if you still see this reproduce on ClrMD 1.0.*.
