### ISSUE TITLE
[Question] MetaDataImport, Generic Type Parameters

### ISSUE THREAD

**Issue by holc-tkomp** [microsoft/clrmd#408]
Hoping you could put some light on this.

### Questions

1. What happened to `IMetaDataImport2`? Will it ever be implemented?
2. Is there a way to retrieve generic type parameters as an array?

### Some context

This came up on this when I tried to retrieve more detailed informations about generic type using available functionalities and `MetaDataImport` looked like the way to go.

Given that I already have enumerated objects and their `Type` property contains correct `ClrType` objects, I now have access to `ClrObject.Type.MetadataToken`, which should contain `TypeDef token`. With it I can utilize `MetaDataImport`, to retrieve the name without generic params:
_Note: following code was run on version 1.0.5._
```c#
ClrModule _module; // initialized somewhere
ClrType _type; // initialized somewhere
// Get the COM wrapper and token
MetaDataImport _metadata = (MetaDataImport)_module.MetadataImport;
int _token = _type.MetadataToken; // Why it's not some unsigned int btw.?
_metadata.GetTypeDefProperties(_token, out var _name, out _, out _);

// Assuming C# type was "class Generic<T1,T2>"
// _name will contain "MyAssembly.Generic`2"
```
Probably there are more efficient ways to retrieve this, but let it be for now.

From what I see `MetaDataImport` class is a partial implementation of [`IMetaDataImport`](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadataimport-interface) interface.

Searching on how could I retrieve generic type parameters with it I stepped on [`IMetaDataImport2`](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadataimport2-interface) interface, which gloriously unveils `EnumGenericParams` and `GetGenericParamProps` methods which looks like exactly what I wanted.

Unfortunately when I looked into source code:

- in `1.0.5` there's a .cs file for this interface, but it does not appear to be finished, there's no class (COM wrapper) using it and comments hint that there's work to be done to make it work;
- in `2.0` (current master branch) this file is gone and it does not appear to be implemented elsewhere,

so it appears like there's no way of accessing those methods at the moment 😞.

**Comment by leculver** [comment]
This is just an oversight on my part.  ClrMD 2.0 is still being built, but I completely forgot about the second interface.

The intent here is that ClrMD will provide the ISOSDac, IXCLR*, and IMetaDataImport functions that it needs to do its work.  ClrMD will _also_ provide any functions requested by the community at large, either through a pull request or just filing an issue and having me do the work.  I don't want to just blanket implement _everything_ right now because it would take me forever and most people won't need it.  Just let me know if there's other stuff you need that's missing.

I'll try to implement `EnumGenericParams` and `GetGenericParamProps` this week.

> // Why it's not some unsigned int btw.?

Tokens probably should be `uint`, but I'm a bit on the fence about it.  The BCL uses `int`, [see this for example](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.metadatatoken?view=netframework-4.8).  In either case, I need to actually go through the entire library and make it fully consistent, which I haven't done yet.

Please do continue to file any issues where something seems missing, it's likely I either haven't gotten around to it yet or I just forgot.  Either way I always appreciate an issue filed as a reminder.

**Comment by holc-tkomp** [comment]
I understand.

After few more thoughts I'm not sure what will `EnumGenericParams` return - at first I thought it'll return tokens of the type params for this particular instance, e.g. for
```c#
class Generic<T1> { }
new Generic<int>(); // object in memory, token will be retrieved from it's type
```
it would return token for the `int` (`System.Int32`) type, but now when I look at the `GetGenericParamProps` method parameters, it appears that the `EnumGenericParams` more likely returns tokens for the GenericParams table, pointing to the generic param `T1` (not to a specific type).

Either way, as it's not yet implemented (no way to test it) and the documentation describes the returned array of those tokens as "The array of generic parameters to enumerate." this is just speculating.

Anyway I'm looking forward to being able to retrieve the `<T1, T2, ...>` generic params and `<int, Class1, ...>` types anyhow from an active object 😉.

**Comment by leculver** [comment]
Unfortunately I'm not 100% sure if what you are looking at will be accomplishable through the metadata interface.  The real underlying problem here is that the dac private API does not support generics in a lot of cases that it should or needs to.

If this isn't workable through the metadata api, we'll have fix this in the runtime.  This is one of the things on my todo list is to try to fix that in the .Net Core 5 timeframe, but that means it will only work when debugging a runtime that has the fix.

**Comment by NextTurn** [comment]
#431 added functionalities to retrieve the `<T1, T2, ...>` generic parameters.

The new APIs look like the followings:

https://github.com/microsoft/clrmd/blob/a5e28f71c2a319a80de027fdb4977cc855e6624c/src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs#L89

https://github.com/microsoft/clrmd/blob/a5e28f71c2a319a80de027fdb4977cc855e6624c/src/Microsoft.Diagnostics.Runtime/src/Common/ClrGenericParameter.cs#L9-L17

As for the generic arguments, I've no idea where to find them.

**Comment by NextTurn** [comment]
The generic arguments are only exposed through the native `IDacDbiInterface` interface.

**Comment by leculver** [comment]
> The generic arguments are only exposed through the native `IDacDbiInterface` interface.

Yeah.  I was thinking about the dac/dbi interface over the last few days.  I really don't want to build support for the `IDacDbiInterface` in clrmd.  It's not versioned and requires tight coupling, so changes between versions of CLR may start causing access violations at any time.

I think the long term direction here is for me to go do work in the coreclr repo to add new ISOSDac interfaces that implement a lot of functionality that we really need.  This is my current wishlist, if I had infinite time:

1. Get ElementType for method table data.
2. All functions which take method tables should work with type handles (for generic fields, for example).
3. Generic support in general.  (This issue.)
4. ~Images report size.~
5. TypeSpec enumeration
6. Change modulemaptraverse to fill an array
7. [Dac::Flush](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/debug/daccess/daccess.cpp#L2002) needs to be synchronized.

**Comment by leculver** [comment]
We have done all that we are going to around MetadataImport in this release.  NextTurn's `EnumerateGenericParameters` should resolve the initial problem here, and I think MetadataImport is where I want it to be for ClrMD 2.0.

I'm going to close this issue now, but please feel free to open a new issue if there's functionality in IMetaDataImport that you would like to need wrapped in ClrMD.

**Comment by holc-tkomp** [comment]
I was wondering a bit about retrieving the actual types of generic parameters (`[System.Int32, System.Double]`, rather than `[T1, T2]`) and I wonder if it's proper that `MetadataToken` for instances of generic types is actually `TypeDef` token, rather than `TypeSpec` token.

Note that it isn't a bug in ClrMD, as WinDbg (`!DumpClass`) already shows it like this, but I wonder if it's expected behavior.
<details><summary>WinDbg output</summary>

```
0:000> !DumpClass /d 00007ffa115704e0
Class Name:      ConsoleApp1.GenericType1`2[[System.Int32, mscorlib],[System.Double, mscorlib]]
mdToken:         0000000002000008    <-- 0x02000000 = TypeDef, 0x1b000000 = TypeSpec, so it's 8th entry in TypeDef
File:            C:\...\ConsoleApp1.exe
Parent Class:    00007ffa6ec12f68
Module:          00007ffa113e4148
Method Table:    00007ffa113e6228
Vtable Slots:    4
Total Method Slots:  5
Class Attributes:    100001  
Transparency:        Critical
NumInstanceFields:   1
NumStaticFields:     0
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffa6ec3aaa0  4000007        8        System.Byte[]  0 instance           SomeGarbage
```

</details>

If mdToken would be of TypeSpec type, this would allow to retrieve the underlying type (currently shown mdToken) and all of the arguments/params types (`System.Int32`, `System.Double` TypeRefs) from the TypeSpec signature.

This kind of stroke me, as recently I was dealing with some generics in our profiler, and tokens there tended to be `TypeSpec` and `MemberRef` tokens instead of `TypeDef` and `MethodDef` ones.
