### ISSUE TITLE
Consider using System.Reflection.Metadata

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#415]
Instead of using IMetaDataImport and our own PEFile implementation, consider using System.Reflection.Metadata in its place, if possible.

**Comment by leculver** [comment]
Additionally, PEImage needs to be threadsafe.

**Comment by NextTurn** [comment]
What are the benefits of using S.R.M in place of `IMetaDataImport`?

**Comment by leculver** [comment]
I'm not sure if there are any.  It's more of something I wanted to investigate if there were benefits or if we should maintain the status quo.
