### ISSUE TITLE
IDataReader implementations need to be thread safe

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#420]
Need to make CoreDumpReader and LinuxLiveDataReader thread safe.

**Comment by leculver** [comment]
Also need to validate that PR https://github.com/microsoft/clrmd/commit/54b64b91554873fff671156cf7cd0b5b34bed1c2 is thread safe.

**Comment by NextTurn** [comment]
> Also need to validate that PR [54b64b9](https://github.com/microsoft/clrmd/commit/54b64b91554873fff671156cf7cd0b5b34bed1c2) is thread safe.

There is an internal lock in S.R.PE.

https://github.com/dotnet/runtime/blob/33bedaf3bcc95d91dde5f09251a5972fbac5f05e/src/libraries/System.Reflection.Metadata/src/System/Reflection/Internal/MemoryBlocks/StreamMemoryBlockProvider.cs#L44
https://github.com/dotnet/runtime/blob/33bedaf3bcc95d91dde5f09251a5972fbac5f05e/src/libraries/System.Reflection.Metadata/src/System/Reflection/Internal/MemoryBlocks/StreamMemoryBlockProvider.cs#L121

**Comment by leculver** [comment]
I will likely not tackle thread-safety of Linux data readers before RTM.  Moving this to "future".
