### ISSUE TITLE
Can't get PDB info on Linux

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#434]
Can't get any PDB info of *NestedException.dll* and *SharedLibrary.dll* because the segments containing `IMAGE_DEBUG_DIRECTORY` are not written into the coredump.

Sample results of `PdbEqualityTest`:

The address of the first `IMAGE_DEBUG_DIRECTORY` of *NestedException.dll* is `0x00007f278acba828`.

The note

```
    0x00007f278acb8000  0x00007f278acba000  0x0000000000000000
        .../NestedException.dll
```

The segment

```
  LOAD           0x0000000000000000 0x00007f278acba000 0x0000000000000000
                 0x0000000000000000 0x0000000000001000         0x1000
```

Related test codes

1.1

https://github.com/microsoft/clrmd/blob/92a54f35d58b0088cff0d41c6d104dd36725098f/src/Microsoft.Diagnostics.Runtime.Tests/src/PdbTests.cs#L25

2.0

https://github.com/microsoft/clrmd/blob/dfe156cc75ec468f2a6ee077120b6ab1a2efc66a/src/Microsoft.Diagnostics.Runtime.Tests/src/PdbTests.cs#L19

**Comment by leculver** [comment]
I'll see if we can get this working like the previous version.  I'll file a bug in the clr diagnostics repo about the missing entry in dumps.  Those should be present.
