### ISSUE TITLE
Non-deterministic failures in TestFinalizerQueueObjects

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#436]
https://dev.azure.com/dnceng/public/_build/results?buildId=458580&view=ms.vss-test-web.build-test-results-tab

https://dev.azure.com/dnceng/public/_build/results?buildId=458803&view=ms.vss-test-web.build-test-results-tab

**Comment by NextTurn** [comment]
I believe this is an issue with the test target, not the codes.

**Comment by leculver** [comment]
GCRoot tests also looks to have non-deterministic failures.  That one looks like a real product issue.
