### ISSUE TITLE
Modules Size is always 0

### ISSUE THREAD

**Issue by PhDuck** [microsoft/clrmd#438]
I wanted to use the modules information to figure out the size of loaded assemblies, since I have application that loads thousands of assemblies at runtime.

Unfortunately though it seems that the Size field on ClrModule is always 0. I have tried both memory dumps and attaching to the process.

Version info:
Microsoft.Diagnostics.Runtime 1.1.57604
.NET Core 2.0, 3.0, and 3.1
Windows 10

The following code prints:
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

```
class Program
{
    static void Main(string[] args)
    {
        var procc = Process.GetCurrentProcess();
        using (var dtt = DataTarget.AttachToProcess(procc.Id, 1000, AttachFlag.Passive))
        {
            ClrRuntime runtime = dtt.ClrVersions.First().CreateRuntime();
            Console.WriteLine(String.Join(',', runtime.Modules.Select(e => e.Size)));
        } 
    } 
}
```

**Comment by leculver** [comment]
Is this an x86 or x64 process?

**Comment by PhDuck** [comment]
x64

**Comment by NextTurn** [comment]
Possibly related to https://github.com/microsoft/clrmd/pull/430#issuecomment-566161896.

**Comment by leculver** [comment]
@PhDuck What are you using the size for?

As I'm looking closer at fixing this there's a few different interpretations of what 'Size' could mean (the original design here is ambiguous which is bad).  For example, it could mean the linker image size, the size as loaded into the virtual address space, the size on disk of the PE image...

If I had a better understanding of what you are using it for that might inform what we should really be producing as the size here.

**Comment by leculver** [comment]
This is now fixed in the current versions of 1.1 and 2.0 on NuGet today.  It now works as well as it has in the past...we are still trying to figure out what this looks like going forward for 2.0.

**Comment by PhDuck** [comment]
Hey @leculver my usage is to measure the memory consumption of having the assembly loaded into memory.

In our product we load in thousands of assemblies, so I wanted to see the potential gain of unloading them, from the perspective of the assembly. 

Afterwards I will have to figure out the impact on the loader heap of loading these C# assemblies and creating classes from them.

**Comment by dcorbin-wintellect** [comment]
Note: I am currently trying to accomplish something extremely similar, and having the same issue with the size always being zero....
