### ISSUE TITLE
Deadlock in ClrInfo.CreateRuntime method.

### ISSUE THREAD

**Issue by kkokosa** [Microsoft/clrmd#44]
## Steps to reproduce

Call following code from WPF main thread (e.g. as a Command):

``` fsharp
use target = DataTarget.LoadCrashDump(@"path\to\file.dmp")
target.SymbolLocator.SymbolPath <- @"SRV*http://msdl.microsoft.com/download/symbols"
target.SymbolLocator.SymbolCache <- @"c:\symbols"
for version in target.ClrVersions do
   let dacInfo = version.DacInfo
   let runtime = version.CreateRuntime()
```
## Actual behavior

WPF application freezes on `version.CreateRuntime()` call because of the deadlock:

![issue4](https://cloud.githubusercontent.com/assets/11159779/15060611/90a0de0a-132c-11e6-9315-4fef050f8ce7.png)

Because of the waiting on async, which in fact should be avoided in generic purpose libraries:

```
protected override void CopyStreamToFile(Stream stream, string fullSrcPath, string fullDestPath, long size)
{
    CopyStreamToFileAsync(stream, fullSrcPath, fullDestPath, size)**.Wait()**;
}
```

This causes a deadlock as UI thread is waiting for result via `DispatcherSynchronizationContext`, while continuation after downloading a proper `mscordacwks` file (in this case) is trying to `Post` via `DispatcherSynchronizationContext` either.

**Comment by leculver** [comment]
Thanks!
