### ISSUE TITLE
x64 stack walking is broken

### ISSUE THREAD

**Issue by goldshtn** [Microsoft/clrmd#46]
The NuGet version works fine, but with `master` I'm getting UNKNOWN frames for any managed method in a 64-bit process. After running `git bisect` I was able to pinpoint https://github.com/Microsoft/clrmd/commit/3a6a4303c54092ad2e9efee6fad5d68e33663b6e as the problematic commit. I assume it's part of the move to the `CorDebug` interfaces.

**Comment by weltkante** [comment]
It's suspicious that as part of that commit it only does `BitConverter.ToUInt32` on what looks to be a pointer. Might be truncating 64 bit adresses. Old code used `BitConverter.ToUInt64` at least in one of the places.

**Comment by mitikov** [comment]
Switching to `BitConverter.ToUInt64` did the trick for me 👍 

Thanks guys.
