### ISSUE TITLE
Layout/Size related naming

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#475]
As discussed in some other threads, we need more appropriate layout/size related names.

For reference, there are three major layouts in CoreCLR:

https://github.com/dotnet/runtime/blob/bd6c81a944f609b88908864827b7797c6b127c5b/src/coreclr/src/vm/peimage.h#L287

https://github.com/dotnet/runtime/blob/bd6c81a944f609b88908864827b7797c6b127c5b/src/coreclr/src/vm/peimagelayout.h#L40

- Flat layout

Specifies that the image was directly mapped via a single `mmap`/`CreateFileMapping` call (file layout).

- Mapped layout

Specifies that the sections of the image were mapped to their corresponding virtual addresses, as if it was loaded with `LoadLibrary` (not file layout).

- Loaded layout

Windows specific: Specifies that the image was loaded using `LoadLibrary` (not file layout).

**Comment by leculver** [comment]
I'm not going to be able to get to this in the 2.0 RTM timeline.  If this requires breaking changes to the API surface it'll likely have to be addressed in 2.1.

**Comment by leculver** [comment]
@NextTurn I am not planning to fix this issue before RTM, but can you think of any function name/enum name/etc we should rename before we ship?

**Comment by NextTurn** [comment]
No good ideas. I haven't had time to visit all public APIs. But super long names like `returnOnlyFullyUniquePaths` won't be what I would prefer. ;)

As for this specific issue, the "size" here was referring to `ModuleInfo.FileSize` which could be a virtual size sometimes. Now the problem has automatically disappeared since we only have `ModuleInfo.IndexFileSize` for PE images.

**Comment by leculver** [comment]
I'm going to close this issue for now since we don't have a concrete issue outlined here.  Please feel free to open a new one or reply back here if there's an actionable bug related to this.
