### ISSUE TITLE
Cleaner, slimmer, and more stable code coverage workflow

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#485]
This is a tracker for tonerdo/coverlet# 628: coverlet.core as a Nuget package.

**Comment by leculver** [comment]
I merged the code coverage PR, but I don't see the expected code coverage text in pull requests, for example:  https://github.com/microsoft/clrmd/pull/482.  Any idea what's wrong?  Or where should I be looking to find code coverage for a pull request?

(FYI, I'm not fully back yet, will likely be only partially working until Jan 6th.)

**Comment by NextTurn** [comment]
The workflow is working as expected. There are three places where you can see the results for now:

- GitHub PR Checks tab (for the last run job): https://github.com/microsoft/clrmd/pull/482/checks?check_run_id=367649810
- Azure Pipelines Code Coverage tab (for the last run job): https://dev.azure.com/dnceng/public/_build/results?buildId=468118&_a=summary&tab=ms.vss-codecoverage-web.code-coverage-details&view=codecoverage-tab
- Azure Pipelines Artifacts page (for each job): No link - the link disappears!

**Comment by leculver** [comment]
Ahh, got it.  Thanks!

**Comment by NextTurn** [comment]
FYI the followings are steps to set up the umbrella bot if you want to give it a try:

- [Log in to Codecov](https://codecov.io/login/gh) with the GitHub account.
- Install [Codecov's GitHub App](https://github.com/apps/codecov).
- Add the repository and set the upload token in CI environment variables.
- Uncomment the task.
https://github.com/microsoft/clrmd/blob/c35e2115241e7dc6f9c835b4c59b9e396ec6471b/eng/Coverage.targets#L20

**Comment by NextTurn** [comment]
> I'm not fully back yet, will likely be only partially working until Jan 6th.

Coincidentally I'm busy preparing for some big events in the new year which will be finished on January 7th in PST.

**Comment by leculver** [comment]
With the amount of trouble I'm having getting our CI system to do the most basic things I don't want to try making this work again until I have tests running back in the system.  I'm going to close this issue so there's not a lot of open issues around that aren't immediately actionable, but I'm happy to revisit this in the future or look at PRs for this as soon as tests are working again.

**Comment by NextTurn** [comment]
This will not progress in the short term. No one is actively looking at dotnet/arcade# 1946 or related issues.
