### ISSUE TITLE
Support for multi dimensional arrays

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#488]
ClrMD should handle multi-dimensional arrays, such as `string[,,]`.  At minimum we should expose a property like `ClrArray.Rank` to tell you whether it's an szarray or not.  Multi-dim arrays are not a common feature, so I'm not sure how much effort I want to spend on them.  Especially if there's not a lot of dac support for it.

**Comment by NextTurn** [comment]
How do you feel the new APIs should look like?

**Comment by leculver** [comment]
I think what you have in the two pull requests are most of what I was thinking.  The only thing left would be something like `ClrObject ReadObject(params int[] indicies)` and `T Read<T>(params int[] indicies) where T: unmanaged` (or `T[] ReadMultidimensional<T>() where T: unmanaged` to let someone actually get the values from a multi-dim array.

However, usage of multi-dimensional arrays is so rare (and more rare to need to pull them apart in ClrMD) that I would rather wait until someone requests that feature to go build it rather than building it myself.  You are welcome to build that if you are interested though.

@ryanmolden How much support do you need for multi-dim arrays?  In email you only mentioned rank, but do you need to fully read multi-dim array contents?  If not I'll likely close this issue and only build that on demand.
