### ISSUE TITLE
Is there a way to use ClrMD from the CoreCLR?

### ISSUE THREAD

**Issue by ayende** [Microsoft/clrmd#50]
A brief look shows that it relies on internal calls, so that blocked me from trying to just recompile.
I'm assuming that there is more to it than that?

**Comment by ayende** [comment]
Any progress on this?

**Comment by loop-evgeny** [comment]
It won't run on CoreCLR, but it does seems to support attaching to CoreCLR processes (on Windows only, of course).

**Comment by leculver** [comment]
This is now fully supported as of ClrMD 1.0 (release very soon).
