### ISSUE TITLE
Microsoft.Diagnostics.Runtime.Utilities is not published to NuGet

### ISSUE THREAD

**Issue by panopticoncentral** [microsoft/clrmd#516]
It looks like the build is producing a NuGet package, but it's not getting pushed to NuGet itself. Are there plans to do this?

**Comment by leculver** [comment]
I have gotten approval to ship it to NuGet, but I don't plan to look into it until after ClrMD 2.0 is ready to ship.  We are still in beta right now.

**Comment by leculver** [comment]
I need to fix some of the metadata in it, but this is now published:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime.Utilities

**Comment by panopticoncentral** [comment]
Thanks!

**Comment by kokhany** [comment]
Hi, I see this issue is closed. However, can we please publish release version as well? As ClrMD is already in "public"
Thanks
