### ISSUE TITLE
SymbolPath not parsed correctly (SymPathElement with more than two elements)

### ISSUE THREAD

**Issue by discostu105** [microsoft/clrmd#52]
Had a problem with a SymbolPath like that:
`cache*c:\symbols;srv*\\mysymstore1*\\mysymstore2*http://msdl.microsoft.com/download/symbols`

It just would not download any symbols from the MS symbol store. Figured, that the problem is in `SymPathElement.ctor(string)`. The regex there only expects two symbol locations at max.

`element.Target` basically ends up with `\\mysymstore2*http://msdl.microsoft.com/download/symbols` as value.

**Comment by leculver** [comment]
Ah yeah, ClrMD doesn't support extra symbol stores.  Even fixing the regex, I'd need to fix the implementation to do the right thing.  I'm not sure if/when I'll get around to this but it's something I'd eventually want to fix.

**Comment by leculver** [comment]
Hello!  I am going to close this issue as "Won't Fix" since it's been around in ClrMD 1.0 for so long and I haven't seen many reports of this.  Sorry!  ClrMD 2.0 will not do symbol resolution on its own (it will delegate to a detached symbol package) which should handle this case better.
