### ISSUE TITLE
Problems loading DAC on clrmd2

### ISSUE THREAD

**Issue by PhDuck** [microsoft/clrmd#523]
I'm trying to switch to clrmd2, in the process I'm build master branch locally and trying to make it work.

Using the same dump file, on the same machine, with clrmd 1.1 everything goes well, but with master builds I get the following error:

```
Unhandled exception. System.IO.FileNotFoundException: Could not find matching DAC for this runtime.
File name: 'mscordacwks_Amd64_Amd64_4.8.4084.00.dll'
   at Microsoft.Diagnostics.Runtime.ClrInfo.CreateRuntime() in C:\Users\xxx\git_clones\c_sharp\clrmd\src\Microsoft.Diagnostics.Runtime\src\DataTargets\ClrInfo.cs:line 94
```

Code: 
```
 ClrInfo info = dataTarget.ClrVersions.First();
this.ClrRuntime = info.CreateRuntime();
```

I took a quick view of the code, there is a divergence in ClrInfo.cs. For my case the DacInfo.FileName is not null, so we do not try to load from symbol server. I tried however to revert it to just check if `dac == null`, it does not solve the problem since `FindBinary` has changed and does not find it.

```
        public ClrRuntime CreateRuntime()
        {
            string? dac = LocalMatchingDac;
            if (dac != null && !File.Exists(dac))
                dac = null;

            if (DacInfo.FileName != null)
                dac ??= DataTarget.BinaryLocator.FindBinary(DacInfo.FileName, DacInfo.TimeStamp, DacInfo.FileSize);

...
```

Env details:
Local machine:
Windows 10 x64
.NET 4.8

Dump:
Windows 10 x64
.NET 4.8

**Comment by NextTurn** [comment]
Unfortunately I failed to reproduce this...

Information collected:

  | Name | Value
-- | -- | --
▶ | DacInfo | {mscordacwks_Amd64_Amd64_4.8.4084.00.dll}
  | Flavor | Desktop
  | LocalMatchingDac | "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscordacwks.dll"
▶ | ModuleInfo | {C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll}
▶ | Version | {4.8.4084.0}

  | Name | Value
-- | -- | --
▶ | BuildId | Uninitialized
  | FileName | "mscordacwks_Amd64_Amd64_4.8.4084.00.dll"
  | FileSize | 0x00ac7000
  | ImageBase | 0x0000000000000000
  | IsManaged | false
  | Pdb | null
  | PlatformAgnosticFileName | "mscordacwks_Amd64_Amd64_4.8.4084.00.dll"
  | TargetArchitecture | Amd64
  | TimeStamp | 0x5dda434a
▶ | Version | {4.8.4084.0}

**Comment by PhDuck** [comment]
@NextTurn which product version does your "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscordacwks.dll" have?

Mine is 4.8.4075.0

**Comment by NextTurn** [comment]
@PhDuck It's 4.8.4084.0.

  | Name | Value
-- | -- | --
  | FileName | "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\clr.dll"
  | FileSize | 0x00ac7000
  | ImageBase | 0x00007ffc3e0e0000
  | IsManaged | false
▶ | Pdb | {e6f1c82e-e82c-4f80-9c33-8b6f3db49f82 2 clr.pdb}
  | TimeStamp | 0x5dda434a
▶ | Version | {4.8.4084.0}

**Comment by PhDuck** [comment]
Yeah, so for me, I have the wrong version locally 4.8.4075.0 which would then lead to it having to find the matching one on 1. 1. Which actually workes, however for clrmd2 it doesn't try to locate the binary.

Can you get a hold of a v4075 and try?

**Comment by NextTurn** [comment]
Odd. IIRC the version string in DAC file name is taken from CLR module's version so they should match.

**Comment by PhDuck** [comment]
I even tried to hack it together by giving the path from ModuleInfo.path but then it throws on version mismatch.

**Comment by leculver** [comment]
I think I see the problem.  I submitted PR #529 to try to fix this issue.

Does the problem go away with the updated 2.0 nuget package?  (It won't go up for another few hours.)  If not, can you please paste the output of these two programs run against the same crash dump to help narrow down the issue?

    // ClrMD 1.1
    using Microsoft.Diagnostics.Runtime;
    using System;

    class Program
    {
        static void Main(string[] args)
        {
            // Pass dump file as only argument.
            using (DataTarget dt = DataTarget.LoadCrashDump(args[0]))
            {
                Console.WriteLine(dt.SymbolLocator.SymbolPath);

                foreach (ClrInfo info in dt.ClrVersions)
                {
                    Console.WriteLine();
                    Console.WriteLine($"[{info.Version}]");
                    Console.WriteLine($"Dac: {info.DacInfo.PlatformAgnosticFileName}");
                    Console.WriteLine($"LocalDac: {info.LocalMatchingDac}");
                    Console.WriteLine($"DacInfo: fs:{info.DacInfo.FileSize:x} ts:{info.DacInfo.TimeStamp:x}");
                    Console.WriteLine($"Found: {!string.IsNullOrWhiteSpace(dt.SymbolLocator.FindBinary(info.DacInfo))}");
                }
            }
        }
    }

-------------------------

    // ClrMD 2.0
    using Microsoft.Diagnostics.Runtime;
    using Microsoft.Diagnostics.Runtime.Implementation;
    using System;
    using System.IO;

    class Program
    {
        static void Main(string[] args)
        {
            // Pass dump file as only argument.
            using (DataTarget dt = DataTarget.LoadCrashDump(args[0]))
            {
                SymbolServerLocator locator = (SymbolServerLocator)dt.BinaryLocator;
                //Console.WriteLine(locator.SymbolPath);

                foreach (ClrInfo info in dt.ClrVersions)
                {
                    Console.WriteLine();
                    Console.WriteLine($"[{info.Version}]");
                    Console.WriteLine($"Dac: {info.DacInfo.PlatformAgnosticFileName}");
                    Console.WriteLine($"LocalDac: {info.LocalMatchingDac}");
                    Console.WriteLine($"DacInfo: fs:{info.DacInfo.FileSize:x} ts:{info.DacInfo.TimeStamp:x}");
                    Console.WriteLine($"Found: {!string.IsNullOrWhiteSpace(locator.FindBinary(info.DacInfo.PlatformAgnosticFileName, info.DacInfo.TimeStamp, info.DacInfo.FileSize, checkProperties: false))}");
                }
            }
        }
    }

**Comment by leculver** [comment]
Having trouble getting a signed build produced, may take me a couple days to figure out what's wrong to ship a nuget package.  =/

**Comment by leculver** [comment]
Thankfully Matt figured out  the problem, @PhDuck can you give this a try?  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.0-beta.20072.5

**Comment by PhDuck** [comment]
Can confirm 2.0.0-beta.20072.5 works!
