### ISSUE TITLE
Cannot load runtime for 4.6

### ISSUE THREAD

**Issue by mitikov** [Microsoft/clrmd#53]
Hey folks,

I get following exception when trying to load MD generated on 4.6+

```
Diagnostics.Runtime.ClrDiagnosticsException: This runtime is not initialized and contains no data.
   at Microsoft.Diagnostics.Runtime.RuntimeBase..ctor(DataTargetImpl dataTarget, DacLibrary lib)
   at Microsoft.Diagnostics.Runtime.Desktop.LegacyRuntime..ctor(DataTargetImpl dt, DacLibrary lib, DesktopVersion version, Int32 minor)
   at Microsoft.Diagnostics.Runtime.DataTargetImpl.CreateRuntime(String dacFilename)
```

Example is 4.6.1085 mscordacwks.dll version, but it seems to take place for all 4.6 =\

What steps should I take to help you overcome the behavior ?

Thanks.

**Comment by weltkante** [comment]
It looks like it picks the wrong runtime. I had that problem in some older version of this library but thought it had already been fixed. Did you build the library from source or used some prebuilt version, if so which?

**Comment by mitikov** [comment]
Hi @weltkante,

Thanks for looking in to this request :)

Referenced assembly seems to be outdated indeed (0.8.25 modified in January, 2015).

I`ll try to use a newer version, and will let you know the results.

Thanks again.

**Comment by mitikov** [comment]
Hi @weltkante,
Using a newer runtime did the trick, thanks !
