### ISSUE TITLE
Is it possible to build a metadata reader in?

### ISSUE THREAD

**Issue by ZQiu233** [microsoft/clrmd#534]
I've looked through this lib and found that only the token of MetaData is provided.
I'm in need of getting details of target assemblies and I've known that there's a native C++ lib provided by MS for this.But I'm seeking for a managed way to do this.

So is it possible to add support for this?Theoretically and practically?
If it's possible,I'm glad to contribute to this.

**Comment by NextTurn** [comment]
After #467 is merged you will be able to get a `MetadataReader` from the `PEReader`.

**Comment by ZQiu233** [comment]
> After #468 is merged you will be able to get a `MetadataReader` from the `PEReader`.

Thanks a lot.
