### ISSUE TITLE
ClrSegment.NextObject is missing

### ISSUE THREAD

**Issue by cshung** [microsoft/clrmd#539]
According to the [walking the heap](https://github.com/microsoft/clrmd/blob/master/doc/WalkingTheHeap.md) chapter of the documentation, there should be a `NextObject()` method defined on `ClrSegment`, but it is no longer available after the [Merge testing/2.0 into master](https://github.com/microsoft/clrmd/commit/b529bfb7a8d69ec1ff51d3cdfd807d6d3895b001) commit.

Is the removal of the method intentional? If it is not, shall we add it back? If it is, shall we update the documentation to eliminate that way of walking the heap?

**Comment by leculver** [comment]
I will add this back.  It's intended that you use EnumerateObjects instead of manually walking object to object, but for advanced uses there's no reason to remove this functionality.
