### ISSUE TITLE
Better way to screen out NativeThread objects?

### ISSUE THREAD

**Issue by jazzdelightsme** [Microsoft/clrmd#54]
The NativeThread class is just a stub (everything throws NotImplementedException).

When enumerating managed threads, I need to filter out these NativeThread objects, because they don't actually do anything but throw. Unfortunately, I don't see a good way to do it other than reflection:

```
    foreach( var dac in proc.ClrRuntimes )
    {
        var t = dac.Threads.Where( ( x ) => x.OSThreadId == Tid ).FirstOrDefault();
        if( (null != t) && !(t.GetType().Name.Contains( "NativeThread" )) )
            list.Add( t );
    }
```

What's the plan for this class--will it eventually be filled in? Or if they are only ever meant to be a placeholder, should there be a non-reflection way to recognize them?

**Comment by leculver** [comment]
I've split the the .Net Native code into its own library (no NuGet package for it yet).  This should fix the underlying issue you are having here.
