### ISSUE TITLE
Ability to detect crashing thread Id in a Crash Dump

### ISSUE THREAD

**Issue by puneetg1983** [microsoft/clrmd#541]
Recently I was using ClrMd to determine **crashing thread** of a memory dump and I didn't find anything in built. Luckily, I was able to achieve this using `IDebugClient` which thankfully is exposed. 

```
private static int GetCrashingThreadId(ClrRuntime runtime)
{
    var crashingThreadId = -1;
    runtime.DataTarget.DebuggerInterface.CreateClient(out IDebugClient client);
    IDebugAdvanced2 adv = (IDebugAdvanced2)client;
    var osThreadIdBuffer = new byte[4];
    var hresult = adv.Request(DEBUG_REQUEST.TARGET_EXCEPTION_THREAD, null, 0, osThreadIdBuffer, osThreadIdBuffer.Length, out int outsize);
    
    if (hresult == 0)
    {
        crashingThreadId = BitConverter.ToInt32(osThreadIdBuffer, 0);
     }
     return crashingThreadId;
}
```

It would be nice to either add a new property to the `RuntimeThread `class (say `IsCrashingThread`) or just another helper method that lets people use CLRMD retrieve this easily.

Another option was to use [IDebugControl4::GetStoredEventInformation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgeng/nf-dbgeng-idebugcontrol4-getstoredeventinformation) but this was returning debugger thread Id rather than the OS Id. 

A few other things that would help for Crash Dumps would be - Exception Code for the crash.

**Comment by leculver** [comment]
Thanks for the suggestion!

Unfortunately, this is expected.  ClrMD is a CLR runtime inspection library, not a general purpose debugger.

The runtime itself doesn't know what thread 'crashed' the process, so you will need to go to another layer of information, such as either the crash dump (using DbgEng) or to the coredump for Linux to find the faulting signal.

The only way to make this work in ClrMD would be to add a property or method to `IDataReader` which every client had to implement, and it wouldn't make sense when attaching to a live process.  As such, I don't intend to add that to the library.

> Another option was to use [IDebugControl4::GetStoredEventInformation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgeng/nf-dbgeng-idebugcontrol4-getstoredeventinformation) but this was returning debugger thread Id rather than the OS Id.

You can convert the debugger thread ID to the OS id using IDebugSystemObjectN.  Offhand I think you use `GetThreadIdsByIndex` to build a mapping table, but there may be another function that lets you convert them directly.  I can't exactly remember offhand.  Good luck!

**Comment by NextTurn** [comment]
> Another option was to use [IDebugControl4::GetStoredEventInformation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgeng/nf-dbgeng-idebugcontrol4-getstoredeventinformation) but this was returning debugger thread Id rather than the OS Id.

`IDebugSystemObjects::GetCurrentThreadSystemId` returns the OS thread ID, used by SOS `clrstack` command.
