### ISSUE TITLE
Offsets of fields are 4 smaller

### ISSUE THREAD

**Issue by ZQiu233** [microsoft/clrmd#544]
Test environment:
Windows 10 x64
.NET Framework 4.6.1

From the following code, 400(TestField2) is expected.But in fact I got 200 which should be the value of TestField1.
As my other tests,the offsets of instanced fields that clrmd get are 4 smaller than they should be.
I don't know if it's a bug, or a feature.In fact I'm just using it with offsets added 4 manually.

```C#
Here's the TARGET process.
namespace TargetProgram
{
	class TestClass
	{
		public int TestField1 = 200;
		public int TestField2 = 400;
	}
	class Program
	{
		static TestClass Test = new TestClass();
		static void Main(string[] args)
		{
			Console.ReadKey();
		}
	}
}

Here's the tester.
namespace clrMDOffsetTest
{
	class Program
	{
		[DllImport("kernel32.dll")]
		public static extern bool ReadProcessMemory
		(
			uint lpProcess,
			int lpBaseAddress,
			ref int lpBuffer,
			int nSize,
			int BytesRead
		);

		[DllImport("kernel32.dll")]
		public static extern bool WriteProcessMemory
		(
			uint lpProcess,
			int lpBaseAddress,
			ref int lpBuffer,
			int nSize,
			int BytesWrite
		);
		[DllImport("kernel32.dll")]
		public static extern uint OpenProcess(uint dwDesiredAccess, bool bInheritHandle, uint dwProcessId);
		[DllImport("kernel32.dll")]
		public static extern int CloseHandle(uint handle);
		public const uint PROCESS_ALL_ACCESS = 0x1F0FFF;
		static void Main(string[] args)
		{
			using (var dataTarget = DataTarget.AttachToProcess(Process.GetProcessesByName("TargetProgram")[0].Id, 1000))
			{
				var process = OpenProcess(PROCESS_ALL_ACCESS, false, dataTarget.ProcessId);
				var runtime = dataTarget.ClrVersions[0].CreateRuntime();
				var module = runtime.Modules.First(t => t.FileName.EndsWith("TargetProgram.exe"));
				var programType = module.GetTypeByName("TargetProgram.Program");
				var instanceAddress = programType.GetStaticFieldByName("Test").GetValue(runtime.AppDomains[0]);

				var testType = module.GetTypeByName("TargetProgram.TestClass");
				var offset2 = testType.GetFieldByName("TestField2").Offset;
				int value1 = 0;
				ReadProcessMemory(process, (int)(ulong)instanceAddress + offset2, ref value1, 4, 0);
				Console.WriteLine(value1);

				CloseHandle(process);
			}
		}
	}
}```

**Comment by NextTurn** [comment]
Use `ClrInstanceField.GetValue`. It will add a pointer size offset for you.

**Comment by NextTurn** [comment]
More on this: the class (reference type) instance address points to the method table pointer at the object start, while the instance field offset is calculated from the end of the method table pointer. You need to add the pointer size and the field offset to the instance address to get the actual field address.

**Comment by ZQiu233** [comment]
> More on this: the class (reference type) instance address points to the method table pointer at the object start, while the instance field offset is calculated from the end of the method table pointer. You need to add the pointer size and the field offset to the instance address to get the actual field address.

Got it. But how can I get some information about these structure?

**Comment by NextTurn** [comment]
> But how can I get some information about these structure?

Sorry, what information?

**Comment by ZQiu233** [comment]
> > But how can I get some information about these structure?
> 
> Sorry, what information?

In other words, I wonder how do you know the memory structure so exactly.
How can I to get some information of that.

**Comment by NextTurn** [comment]
I can recommend some blogs exploring the internals:

[.NET Internals Archives](https://devblogs.microsoft.com/premier-developer/category/net-internals/)

**Comment by ZQiu233** [comment]
> I can recommend some blogs exploring the internals:
> 
> [.NET Internals Archives](https://devblogs.microsoft.com/premier-developer/category/net-internals/)

Thanks a lot.
