### ISSUE TITLE
Is it possible to resume/suspend a process after attaching invasively?

### ISSUE THREAD

**Issue by alexrp** [microsoft/clrmd#548]
If so, what are the relevant APIs in CLR MD? I see there are debugger-related APIs in `Microsoft.Diagnostics.Runtime.Utilities`, but this library does not appear to be on NuGet yet.

**Comment by leculver** [comment]
The secondary library will be on NuGet when 2.0 comes out of beta.

> Is it possible to resume/suspend a process after attaching invasively?

Right now this is only possible if you dispose of the DataTarget.  It's probably a good idea to give a way to resume/suspend the process in some way...I'll leave this open until then.

I'll likely make DbgEngDataReaderr public with some helper functions to resolve this problem and not require the use of .Utilities.

**Comment by NextTurn** [comment]
Good question. If you get `IDebugClient` and `IDebugControl` somehow, you can call `IDebugClient.SetEventCallbacks` to register an event handler and then invoke `IDebugControl.SetExecutionStatus(DEBUG_STATUS.GO)` to resume the process and `IDebugControl.SetExecutionStatus(DEBUG_STATUS.BREAK)` to suspend it again.

It's not possible to get complete COM interfaces from `DbgEngDataReader`, because the M.D.R package is referenced by the M.D.R.Utilities package where the DbgEng interfaces are. Right now we call those COM APIs by manually creating delegates for function pointers.

**Comment by leculver** [comment]
@alexrp After some further thought here I think I would like to keep the core of ClrMD as purely an inspection API and not offer any mechanism to resume/pause processes outside of the initial attach and detatch.  However, ClrMD still supports your scenario of wanting to pause/resume processes at will, but you have to supply the code to do that yourself.

I think there are two options forward:

1.  In a Windows-only world, you can use `DbgEng` as as NextTurn suggests here.  The Utilities project is now posted on [NuGet](https://nuget.org/packages/Microsoft.Diagnostics.Runtime.Utilities).

**Comment by leculver** [comment]
@alexrp After some further thought here I think I would like to keep the core of ClrMD as purely an inspection API and not offer any mechanism to resume/pause processes outside of the initial attach and detatch.  However, ClrMD still supports your scenario of wanting to pause/resume processes at will, but you have to supply the code to do that yourself.

I think there are two options forward:

1.  In a Windows-only world, you can use `DbgEng` as as NextTurn suggests here.  The Utilities project is now posted on [NuGet](https://nuget.org/packages/Microsoft.Diagnostics.Runtime.Utilities).  If you use DbgEng directly you can can fully control the state of the process, and you can use [DbgEng.CreateFromDbgEng](https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs#L390) to create a ClrMD instance from a raw `IDebugClient` pointer.
2.  Alternatively you can use `DataTarget.AttachToProcess(pid, suspend: false)` and implement process suspension yourself.  The "suspend: false" tells clrmd to not attempt to suspend/resume the target process and instead let the user control process suspension.  This will work on other processes than Windows at the cost of having to implement process suspension for each.

For the second option, you should be able to find example code of process suspension in ClrMD.  Let me know if you want me to point you to examples.

Thanks!
