### ISSUE TITLE
Update ClrMD 2.0 Documentation/Samples

### ISSUE THREAD

**Issue by TheXenocide** [microsoft/clrmd#567]
I'm getting an odd exception stating "IsPointer64Bit failed" from 1.1 and noticed there was a 2.0 beta which I figured might be worth a try, but now a bunch of my code won't compile and, while some things I was able to find an alternative to, I'm not sure how best to update others. When I looked into the docs/samples they're also using methods that appear to have been removed. Could you provide guidance and consider updating documentation or maybe provide a migration guide?

`EnumerateRefsOfObject` and `GetArrayLength` both appear to be removed from `ClrType`. I'm also not exactly sure how we're supposed to be doing things equivalent to `GetValue` and `GetEnumName`, or `EnumerateTypes` and  `ReadMemory` removed from `ClrHeap`. I'm not done digging around and getting used to things yet, but any advice on patterns/methods to replace these with would be helpful.

**Comment by TheXenocide** [comment]
For anybody coming across this, `EnumerateRefsOfObject` is simply `EnumerateObjectReferences` now, which I think is a better name. Still digging through for other bits.

**Comment by TheXenocide** [comment]
This is my approximation of `EnumerateTypes` for now, though I'd love to know if there's a more appropriate way.
 
```csharp
public static class ClrMDExtensions
{
	public static IEnumerable<ClrType> EnumerateTypes(this ClrHeap heap)
	{
		var runtime = heap.Runtime;
		return runtime.EnumerateModules()
			.SelectMany(mod => mod.EnumerateTypeDefToMethodTableMap()
				.Select(tuple => tuple.Item1)
			)
			.Distinct()
			.Select(runtime.GetTypeByMethodTable);
	}
}
```

**Comment by TheXenocide** [comment]
Since I'm seeing the current source has public methods that don't exist in the beta NuGet package, I'm guessing it might be early days yet. Since some methods have alternatives, those may just be a matter of documentation, but for others I see no clear alternative. I'm thinking maybe some of these things are just yet to be implemented? I tried to take a look at the 2.0 project and backlog items, but those don't give me a sense that any functionality is considered missing at all. I figured I'd try pulling source and was forging my way ahead with extension methods to try to get a general feel for what still works and what doesn't, but for the time being there are a number of details I'm missing that would take me quite a bit of time to determine how to re-implement.

Overall I'm appreciating the cleanup and finding the code mostly readable, if a little uncommented (which makes it difficult to contribute to, since some things don't express their intention or the scenarios they intend to handle particularly clearly; for instance, I found a `StackOverflowException` in `FixGenerics`, which I _think_ I've fixed, but I'm not really sure). The contribution guidelines are fairly sparse, but do you have any guidance on what would work best for you in terms of tracking functionality parity (both for documenting code migration and from establishing needed functionality that is currently missing)?

I'll open an issue for the `StackOverflowException` soon; would you like me to submit a pull request? Is there anything you need me to do with a pull request first?

**Comment by TheXenocide** [comment]
Related: https://github.com/microsoft/clrmd/issues/417

**Comment by NextTurn** [comment]
ClrMD 2.0 is still under development, and the public APIs may change before RTM. We have a issue tracking documentation (#417) but you're welcome to update the samples if you like.

> I'm thinking maybe some of these things are just yet to be implemented?

It's possible that some things were removed intentionally or unintentionally (like #539). Feel free to ask if you found anything missing.

> I'll open an issue for the `StackOverflowException` soon; would you like me to submit a pull request? Is there anything you need me to do with a pull request first?

Contributions are welcome! There is no limitation for pull requests.

**Comment by NextTurn** [comment]
`ClrType.GetArrayLength` -> `ClrObject.AsArray().Length`

`ClrType.GetEnumName` -> `ClrType.AsEnum()`...

`ClrType.GetValue` -> maybe `ClrHeap.GetObject`

`ClrHeap.ReadMemory` -> maybe `DataTarget.DataReader.ReadMemory`

**Comment by TheXenocide** [comment]
Oh, I think I might quite like the direction I'm seeing here with the arrays and enums and such. It reminds me of a Gist prototype I made ages ago that did something similar. I'll try those out and see how things go and I'll try to get the pull request together soon, I just want to take a look at tests and such. Should I create an issue for it or will the pull request be sufficient to document it? (I've seen projects go either way on this).

I could also add `EnumerateTypes` if that implementation seems good enough; maybe to `ClrRuntime` since that's where all the members used come from? It used to be on ClrHeap and I suspect my implementation falls short since it doesn't deal with platform differences like `AppDomain`s and such, but thought I'd ask (and if you want to point me in the right direction maybe I could do it properly).

I've also implemented `EnumerateObjectAddresses` in similar extension methods using the `GetNextObjectAddress` method I found in code (this didn't appear in the NuGet package so maybe this is work already in progress?). I used this to make `EnumerateObjects` "overloads" (they're currently extension methods) that only returned objects of a specific type (i.e. `!DumpObject -mt ...`) without having to use a `Where` on `EnumerateObjects` to save on having to create `ClrObject` instances I wasn't looking for. My extension methods are probably suboptimal and could be done a lot more efficiently within the actual codebase. Would you be open to me providing an implementation of `EnumerateObjectAddresses` as well as overloads for that and `EnumerateObjects` which receive `ClrType` along with overloads that receive a method table? These seem like key optimizations for larger memory dumps and interactive browsing. I could try refactoring `ClrSegment.EnumerateObjects(Action<ulong, ulong, int, int, uint>? callback)` to share code and leverage what looks like a more optimal iteration strategy if you'd prefer. Question though: what is the callback for? I don't see it used anywhere.

Lastly, since you're using iterators, I think I'd recommend wrapping all `ArrayPool` usages a try/finally. As it stands currently if anything stops enumeration early (an `Exception`, `break`, or manually using `GetEnumerator`/`MoveNext`/`Current` without enumerating to the end), there's no way to ensure the buffer is released back to the pool. Iterators automatically generate `IDisposable` implementations for `using`/`finally` blocks and `foreach` automatically calls it. Anybody using an enumerator manually still needs to know that they must also manually check if they implement `IDisposable` and, if so, call `Dispose`, which is somewhat arcane knowledge, but then so is manually enumerating to some extent.

**Comment by NextTurn** [comment]
> Should I create an issue for it or will the pull request be sufficient to document it? (I've seen projects go either way on this).

Just open a pull request so we could exchange ideas by commenting on the codes. There are no complicated ceremonies in this repo.

> maybe to `ClrRuntime` since that's where all the members used come from?

Some members were refactored to belong to the closer types. Design questions are left to the author @leculver.

> Question though: what is the callback for? I don't see it used anywhere.

The callback along with `GetNextObjectAddress` was added recently and I haven't taken a close look at it. Its use is kind of magic:

https://github.com/microsoft/clrmd/blob/399b316002bc2725a08efe3fdd1b42ab7ddb1638/src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs#L223

> Lastly, since you're using iterators, I think I'd recommend wrapping all `ArrayPool` usages a try/finally.

Yes, it's best to return as many arrays as possible. But it's not mandatory (#441).

**Comment by leculver** [comment]
Sorry for the delay in responding, I'm somewhat out of office this week, but should be back as normal next week.  Looks like NextTurn answered most questions (thank you!), here's a few other thoughts.  Feel free to reply back again if I missed something.

> When I looked into the docs/samples they're also using methods that appear to have been removed. 

I plan to add back the documentation/samples when the library is ready to ship.  Note that some functionality has been greatly changed or refactored so the the documents as they exist for 1.1 may not be directly translated...  The next few items are examples of that:

> I could also add `EnumerateTypes` if that implementation seems good enough;

EnumerateTypes was purposefully removed.  There's actually not a function in the CLR diagnostics layer that gives you the _real_ answer, and it was a bad design choice on my part to try to "fake" the answer and give it out.  The equivalent way to do this is to use `ClrModule.EnumerateTypeDefToMethodTableMap` and pass the MethodTable enumerated to `ClrRuntime.GetTypeByMethodTable`.  This is essentially what `EnumerateTypes` used to do, but now it's more explicit that you aren't enumerating every type, you are only enumerating constructed typedefs in a module.


> I've also implemented `EnumerateObjectAddresses` in similar extension methods using

`EnumerateObjectAddresses` is no longer needed.  `ClrObject` is implicitly castable to ulong, which gives you the address.  In clrmd 1.1:  `foreach (ulong addr in heap.EnumerateObjectAddresses())` in 2.0 should be `foreach (ClrObject obj in heap.EnumerateObjects())`.  Similarly, if you really just want the address do this:  `foreach (ulong addr in heap.EnumerateObjects())` and casting should take care of it.

> The callback along with `GetNextObjectAddress` was added recently and I haven't taken a close look at it. Its use is kind of magic

Yeah, the design here is rough.  I'm struggling to keep the public surface area `ClrHeap` and `ClrSegment` from having that kind of weird quirk.  I'm also trying to keep their implementations (**Clrmd**Segment/**ClrmdHeap**) from being too deeply coupled but I'm not sure the direction I went with was really the right direction.  At minimum that Action should be a descriptive delegate.  I could also just remove the heap enumeration logging...but it's super helpful when tracking down failures.

In any case, no one should need to directly use the implementation classes even if they are marked public (such as Clrmd*) unless they are either extending ClrMD to do something new/unique, or some other similarly advanced case.

> Would you be open to me providing an implementation of EnumerateObjectAddresses as well as overloads for that and EnumerateObjects which receive ClrType along with overloads that receive a method table? 

I'm a bit confused there.  Can you give a sample API surface area and usage so I can see what you are talking about?

Also with that change what problem are you trying to solve?  Are you trying to speed up how fast you walk the heap?  are you trying to lower memory usage?  Or is there some other purpose?

> The contribution guidelines are fairly sparse, but do you have any guidance on what would work best for you in terms of tracking functionality parity (both for documenting code migration and from establishing needed functionality that is currently missing)?

You are welcome to ask any questions here if you want to know if a given change would be accepted before you work on it.  Alternatively you are welcome to open any pull request you like, but keep in mind I might reject them or request changes if you didn't clear them with me first.

**Comment by TheXenocide** [comment]
Oh, it calls the callback within the method itself, I mean nothing supplies a callback when calling it. Since it's not part of the abstraction, just an implementation detail of the `ClrmdSegment` (I misquoted it as being `ClrSegment` above, though it is public it doesn't implement anything abstract/virtual). What's curious about it to me is that everything it passes to the callback already exists in the type/object returned. It won't force enumeration through the whole iterator, so whatever is passing the callback likely also expects to enumerate every item. Just a bit confusing imo, but if there's a purpose it'd just be nice to know what it is if I refactor it around so I know what to consider.

As for the comment from #441 that makes enough sense to me, though I don't suppose it would be any harm to wrap it in a try/finally either which at least accounts for using a break in a foreach. Not a priority, but I think if I'm changing code already I might add a try finally for a slight free improvement unless there's a reason not to. All that said, I think most of this type of conversation can probably move to the pull request now that I'm poking away at the code.

**Comment by TheXenocide** [comment]
Oooh, didn't see that response until I sent mine

**Comment by leculver** [comment]
> Oh, it calls the callback within the method itself, I mean nothing supplies a callback when calling it.

It is supposed to pass ClrmdHeap.WriteHeapStep, but doesn't right now due to an oversight when I was checking in a refactoring.  I haven't fixed it yet as I'm still debating stripping out the entire "heap step logging" feature or not.  I'll likely leave it in until clrmd 2.0 is ready to ship in case I need it to debug broken heap enumeration as I'm making changes.

> I think if I'm changing code already I might add a try finally for a slight free improvement unless there's a reason not to.

Feel free to put a try/catch if it really bothers you.  It doesn't matter much either way, but if you are going to fix it please make it its own checkin instead of wrapping it into other changes.

**Comment by TheXenocide** [comment]
I had to step away while writing this message so some of it is from last evening and some is from today 😓 

Okay, I'm caught up. First: no worries; I hope you're safe and healthy. I have appreciated this project for a very long time (pretty sure since pre-1.0, or at least I remember a time when `.Heap` was `.GetHeap()`).

My `EnumerateTypes` extension method does exactly what you mention, and I'm okay with keeping it an extension method over on my side knowing that the existing implementation sets a more clear expectation of what it's really doing. This all started because I was trying to dig deep into an object graph from a very large memory dump and the tools I've used most recently (some LINQPad scripts I've built up as well as the `ClrMD.Extensions` NuGet package). One of those finds types matching matching a certain name which I can then click on to interact with a bit (rather than walking the whole heap like `!dumpheap -stat` would). I'm comfy enough with WinDbg/SOS for quick questions, but I usually break these tools out when I'm working with rather large dumps (this one was 17GB; tomorrow I get to look at one that's 13GB) and/or have complex interrogations of the data to perform.

`EnumerateTypes` aside, though, my hope for EnumerateObjectAddresses is to not require instantiation of a ton of ClrObject instances when I'm only looking for instances of a specific type. Particularly due to the size, it takes a very long time for me to use `.EnumerateObjects.Where(obj => obj.Type == someClrType)` and anything I can do to reduce allocations/GC/time is helpful. I made the extension methods down below using `GetNextObjectAddress` to try to accommodate that, but once I ran into the exception and had the code down thinking about contributing and I started looking at the code for `EnumerateObjects` I figured it'd be even faster to implement using a variation of the logic there and just comparing method table (and a `ClrType` overload that would just call the other passing the method table from the type). Even the `GetNextObjectAddress` approach takes quite a long time with these dumps though.

I'm currently running a query using only `EnumerateObjects`. WinDbg reports that of the 153,006,151 objects in the heap of this ~13GB dump there are 3717 of the type I'm looking for. My query has been running for 40 minutes and has only enumerated ~225,000 of the objects in the heap (so far I've found 196 of the instances I'm looking for). Now, I expect managed code and more rich sets of data to cost a extra, but for reference  `!dumpheap` enumerates all the addresses for that method table in about 4 minutes. I have actually combined these tools before and might again, but still thought that it might be helpful to use more optimal enumeration methods in general.

Here are the extension methods I'm currently using to supply this functionality:
```csharp
public static class ClrMDExtensions
{
	public static IEnumerable<ClrType> EnumerateTypes(this ClrHeap heap)
	{
		var runtime = heap.Runtime;
		return runtime.EnumerateModules()
			.SelectMany(mod => mod.EnumerateTypeDefToMethodTableMap()
				.Select(tuple => tuple.Item1)
			)
			.Distinct()
			.Select(runtime.GetTypeByMethodTable);
	}
	
	public static IEnumerable<ulong> EnumerateObjectAddresses(this ClrHeap heap) => heap.Segments.SelectMany(EnumerateObjectAddresses);
	
	public static IEnumerable<ulong> EnumerateObjectAddresses(this ClrSegment segment)
	{
		ulong address = segment.FirstObjectAddress;
		while (address < segment.CommittedEnd && address > 0)
		{
			yield return address;
			address = segment.GetNextObjectAddress(address);
		}
	}
	
	public static IEnumerable<ulong> EnumerateObjectAddresses(this ClrHeap heap, ClrType type) => heap.Segments.SelectMany(seg => seg.EnumerateObjectAddresses(type));
	
	public static IEnumerable<ulong> EnumerateObjectAddresses(this ClrSegment segment, ClrType type)
	{
		foreach (var address in segment.EnumerateObjectAddresses())
		{
			if (segment.Heap.GetObjectType(address) == type)
			{
				yield return address;
			}
		}
	}
}
```

The logging bit makes sense and I can keep that in consideration. The try/finally thing isn't that important to me, I'm just thinking that if I implement `EnumerateObjects` and `EnumerateObjectAddresses` with method table and `ClrType` overloads I would probably be pulling pieces of that method apart to take advantage of the optimized iteration without duplicating a bunch of code. If it's cleaner for you if I don't add it, that's fine too.

**Comment by TheXenocide** [comment]
Sidenote: my query appears to have hit a bug of some sort. I need to stay focused on my other troubleshooting at the moment, but it looks like `EnumerateObjects` made it through 278802 instances but now appears to be blocking indefinitely.

**Comment by TheXenocide** [comment]
It also looks like someone else was using that environment mentioned above; having pulled everything locally I enumerate objects significantly faster, but so too does WinDbg.

**Comment by leculver** [comment]
If it's taking 40 minutes to enumerate the heap either you are running into hardware limitations (slow hard drive), OS/other programs interfering problems (virus scanner killing your perf or the file being in super cold storage), or something is wrong with your code.  I would have expected a heap of 15million objects to complete in 60 seconds or less.

Before trying to "optimize" ClrMD's usage you should measure where your time is really being spent, especially with something like perfview.

For example, I have a large dump laying around (23gb) with 60 million objects on the heap.  On ClrMD 1.1 _with the file in cold storage_ this took 2.5 minutes:

    ClrMD version: 1.1.2.16301
    59,083,414 objects, 10,419,818 strings processed in 00:02:27.0138537

However, once the file is "warm" on disk, rerunning the same scenario only takes 14 seconds:

    ClrMD version: 1.1.2.16301
    59,083,414 objects, 10,419,818 strings processed in 00:00:14.0591030

I tried again on ClrMD 2.0 master branch (ignore the version number that's because it's not a signed build), same result:

    ClrMD version: 42.42.42.42424
    59,097,053 objects, 10,419,605 strings processed in 00:00:16.6182549

There's definitely something odd going on with your setup.  What you are describing shouldn't take longer than 60ish seconds once the dump is warm on disk.

Here's the code I used, try it in your scenario:

    using Microsoft.Diagnostics.Runtime;
    using System;
    using System.Diagnostics;
    using System.Linq;
    using System.Reflection;

    class Program
    {
        static void Main(string[] args)
        {
            Assembly clrmd = typeof(DataTarget).Assembly;
            FileVersionInfo fvi = FileVersionInfo.GetVersionInfo(clrmd.Location);
            Console.WriteLine($"ClrMD version: {fvi.FileVersion}");

            Stopwatch sw = new Stopwatch();
            using (DataTarget dt = DataTarget.LoadCrashDump(args[0]))
            {
                ClrRuntime runtime = dt.ClrVersions.Single().CreateRuntime();
                ClrHeap heap = runtime.Heap;

                sw.Start();

                int objectCount = 0;
                int stringCount = 0;
                foreach (ClrObject obj in heap.EnumerateObjects())
                {
                    // Force creation of the type and getting the name.

                    if (obj.Type?.Name == "System.String")
                        stringCount++;

                    objectCount++;
                }

                sw.Stop();
                Console.WriteLine($"{objectCount:n0} objects, {stringCount:n0} strings processed in {sw.Elapsed}");
            }
        }
    }

**Comment by TheXenocide** [comment]
I'm also using a build of master (with a FixGenerics patch in place, but that fix is incredibly simple currently). I have a solid state and the laptop is a couple years old, but I get the following:

```
ClrMD version: 42.42.42.42424
152,884,916 objects, 29,597,562 strings processed in 00:04:36.9434161
```

That's not so bad honestly, so I suspect it's probably the way I was outputting my data which I can play with. I don't know how much of a difference this makes, but the dump is of a .NET Core 3.1.2 process. I can imagine some amount of difference depending on the number of modules/distinct types and so on. I can probably also employ some caching strategies if I'm working with it long enough.

**Comment by leculver** [comment]
You should submit the FixGenerics patch if you have time.  I'd like to take a look at it before we ship 2.0 RTM.  Even if it's a rough hack I'd like to see where the code can go wrong.

**Comment by leculver** [comment]
Also, try to run the program I gave you twice, back to back and see if it's faster on the second run.

**Comment by TheXenocide** [comment]
Here's two more runs.

```
ClrMD version: 42.42.42.42424
152,884,916 objects, 29,597,562 strings processed in 00:04:39.5505608
```
and
```
ClrMD version: 42.42.42.42424
152,884,916 objects, 29,597,562 strings processed in 00:04:40.0992711
```

**Comment by TheXenocide** [comment]
I was going to try to verify some more scenarios, but figured it wouldn't hurt to push it up as is so you can take a look.

https://github.com/microsoft/clrmd/pull/569

**Comment by TheXenocide** [comment]
Is there an equivalent to `EnumerateRefsOfObject` yet? I'm seeing for references are going the opposite direction as I want. I'm kinda hoping to browse all references to the instance I have in hand at the moment (and am also particularly interested in calculating commonalities between GCRoot chains as well).

I've got things running well enough that I've been able to actually browse around a bit; I still need to put in some side time to get some of the tooling I like to use running, but otherwise I'm at least at the point where ClrMD is saving me enough time over WinDbg for some things. 

Enumerating the whole heap still takes the same time, but I've stopped using live UI output (which is nice but not mandatory) and started caching a good bit and the combination of those things has made many things fast enough for me for now.

**Comment by NextTurn** [comment]
> I'm kinda hoping to browse all references to the instance I have in hand at the moment

That's exactly what GCRoot does.

```cs
IEnumerable<ClrObject> _(ClrHeap heap, ClrObject target) =>
from root in heap.EnumerateRoots()
let source = root.Object
from reference in source.EnumerateReferences(true)
where reference == target
select source;
```

**Comment by TheXenocide** [comment]
I've been sidetracked by other efforts, but as a note I implemented the above logic and found an OverflowException I'll try to gather some information about. I think it happens because `SOSDac.GetMethodTableSlot` tried casting an `int` of -1 to a `uint`

**Comment by leculver** [comment]
The `GetMethodTableSlot` issue should be fixed now.

> Is there an equivalent to `EnumerateRefsOfObject` yet? I'm seeing for references are going the opposite direction as I want. I'm kinda hoping to browse all references to the instance I have in hand at the moment (and am also particularly interested in calculating commonalities between GCRoot chains as well).

Getting "all references pointing to an arbitrary object" is _not_ something ClrMD or any other debugging library can do by itself.  Note that the GC heap is a directional graph where objects point to whatever they are referencing, thereby keeping them alive.  You are asking to _reverse_ the direction of a graph.  Take this graph as an example (image borrowed from [here](https://www.geeksforgeeks.org/transpose-graph/)):

![transpose_both](https://user-images.githubusercontent.com/8496639/79144728-4b3a1f00-7d74-11ea-9f6a-06f4a7442a7f.png)

In CLR, the GC heap is graph `i`, and ClrMD can happily enumerate that graph to you because it already exists in memory of the target process.  You are asking for graph `ii` in that link, which doesn't exist anywhere in memory or in the target dump.  If you want graph `ii` to let you quickly look up what locations _references_ a target object, you will have to build the transposed graph yourself.  Or you'll have to use algorithms to find the route back to a single object (which is what GCRoot does).

Is there any other open questions in this thread?  I can reopen if there's more here.  Thanks!

**Comment by TheXenocide** [comment]
It might be some time before I get to play with ClrMD again as we've solved the issues we were looking at for now. Thanks very kindly for all the help and for the project in general. I love this project and hope to continue some recreational coding with it on the side, but you know how spare time works.
