### ISSUE TITLE
Possible to remotely jit a method?

### ISSUE THREAD

**Issue by Symbai** [microsoft/clrmd#578]
I'm currently using this library to lookup a memory address of a method in a running program. I've noticed that if the method has not been jitted yet the memory address returned will be 0xFFFFFFFFFFFFFFFF and the ILOffsetMap is empty. In this case I would like to remotely jit the method and get the new/correct memory address. How can I do this? Is there way or do I have to re-run the address lookup all the time until the method is jitted?

**Comment by leculver** [comment]
Sorry for the delay in responding.

ClrMD cannot do this itself.  ClrMD is meant to be a passive "inspection" API and will not modify memory in the target process, which would be required to JIT a method.

I believe the CLR profiling API and ICorDebug have ways to force a method to be JIT'ed but this isn't something I know how to do off the top of my head, but you might be able to ask the folks in the CLR diagnostics repo, but it will be invasive.

**Comment by weltkante** [comment]
As far as the profiler API is concerned there's also https://github.com/microsoft/CLRInstrumentationEngine
