### ISSUE TITLE
EnumerateObjectAddresses() is returns different type names than GetMethodByAddress()

### ISSUE THREAD

**Issue by Symbai** [microsoft/clrmd#579]
The following code below:
```
var method = runtime.GetMethodByAddress(0x7FFE5FDCBF30))
Console.WriteLine(method.Type.Name);

foreach (ulong obj in runtime.Heap.EnumerateObjectAddresses())
{
    ClrType type = runtime.Heap.GetObjectType(obj);

    // If heap corruption, continue past this object.
    if (type == null)
        continue;

    if (!type.Name.StartsWith("System.SZArrayHelper")) continue;
    
    Console.WriteLine(method.Type.Name);
}
```

generates this output (all the time, while the target process is paused):
```
//GetMethodByAddress
System.SZArrayHelper+SZGenericArrayEnumerator<TaleWorlds.Core.PieceData>
//EnumerateObjectAddresses
System.SZArrayHelper+SZGenericArrayEnumerator<System.__Canon>
System.SZArrayHelper+SZGenericArrayEnumerator<System.__Canon>
System.SZArrayHelper+SZGenericArrayEnumerator<System.__Canon>
System.SZArrayHelper+SZGenericArrayEnumerator<System.__Canon>
```

However enumerating EnumerateObjectAddresses() should produce the same class names as GetMethodByAddress() does. Otherwise I have no idea which one, IF one, is the right one when searching the other way around, i.e. finding method address by name.

Using nuget package version 1.1.116301

**Comment by leculver** [comment]
Sorry for the delay in responding.

This isn't actually a bug, CLR actually treats those as two different methods.  The `System.__Canon` method is the [open generic version of the method](https://stackoverflow.com/questions/2173107/what-exactly-is-an-open-generic-type-in-net) (or maybe the version for reference types...I can't remember off the top of my head), and the `SZGenericArrayEnumerator<TaleWorlds.Core.PieceData>` method is the specific method instantiation of the method for that struct.  The CLR runtime can generate many different versions of a generic method if it determines the <T> type requires a different form of JIT'ed code.

One thing to keep in mind is that ClrMD is attempting to show you what the CLR runtime really sees and the data it really uses.  This means that even though there might be only one Foo<T> defined in a C# file, the CLR runtime's implementation details may not match the original C# code.

Please let me know if you have more questions here!  Also in the future if you have question if you can give a small repro program that I can take a crash dump of and load into ClrMD then I can answer questions much more quickly.
