### ISSUE TITLE
Change test infrastructure to produce dumps at test time

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#594]
The Arcade build infrastructure fails to properly build due to our test infrastructure design.  When run outside of "real" signed and packaged builds, everything works fine.  Inside our real infrastructure we hit an error after tests/test targets are built and code coverage runs.  So the only way to try to fix this is to submit real changes into master and wait to see what happens in the official build pipeline.  Here's the error:

```
##[error].dotnet\sdk\3.1.100\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): error NU5026: The file 'F:\workspace\_work\1\s\artifacts\bin\Microsoft.Diagnostics.Runtime\Debug\netcoreapp2.1\Microsoft.Diagnostics.Runtime.pdb' to be packed was not found on disk. 
F:\workspace\_work\1\s\.dotnet\sdk\3.1.100\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): error NU5026: The file 'F:\workspace\_work\1\s\artifacts\bin\Microsoft.Diagnostics.Runtime.Utilities\Debug\netcoreapp2.1\Microsoft.Diagnostics.Runtime.Utilities.pdb' to be packed was not found on disk. [F:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime.Utilities\Microsoft.Diagnostics.Runtime.Utilities.csproj] 
##[error].dotnet\sdk\3.1.100\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): error NU5026: (NETCORE_ENGINEERING_TELEMETRY=Build) The file 'F:\workspace\_work\1\s\artifacts\bin\Microsoft.Diagnostics.Runtime.Utilities\Debug\netcoreapp2.1\Microsoft.Diagnostics.Runtime.Utilities.pdb' to be packed was not found on disk. 
```

Things we've tried to fix this (none of this helped):

1.  Disable code coverage.
2.  Change the dotnet build command "AfterTargets" directive.
3.  Try running --no-restore when building testtasks/testtargets to see if the restore itself was affecting the build.

The only thing that makes the problem go away is to kill the test build entirely, as in https://github.com/microsoft/clrmd/commit/dcbb781addf0565b0916b7f862c45f66202454c1.

At this point I've spent as much time as I care to on this issue.  Someone from the Arcade team suggested changing where/how test assets are produced as this comment mentions:  https://github.com/microsoft/clrmd/pull/572#issuecomment-603345590.  Instead of doing that @tmat says:

> the better way in msbuild is to add ProjectReferences that do not add actual metadata references to the referencing project. example: https://github.com/dotnet/roslyn/blob/f4f3aa7ce76f187713d121fff2c57fca98d955e1/src/Compilers/CSharp/Test/CommandLine/Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.csproj#L16
> if you set ReferenceOutputAssembly="false" it won't pass the output assembly of that reference to csc but it will make sure it builds

And then producing the .dmp files as part of the test harness, as ClrMD used to do.

To be clear, I MUCH prefer our current system to produce .dmp files during build when we update source code.  However, Arcade just doesn't handle this scenario well at all and even if we find some way to force it to work (like using `afterSolutionTargets`) I worry some other update to Arcade is going to break it again in the future.

We'll just have to move back to producing .dmp files in the test harness if the files on disk are out of date with the test binaries.  I can't afford to waste more time fighting with Arcade here.

cc @NextTurn as an FYI.

**Comment by NextTurn** [comment]
> the better way in msbuild is to add ProjectReferences that do not add actual metadata references to the referencing project. example: https://github.com/dotnet/roslyn/blob/f4f3aa7ce76f187713d121fff2c57fca98d955e1/src/Compilers/CSharp/Test/CommandLine/Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.csproj#L16
if you set ReferenceOutputAssembly="false" it won't pass the output assembly of that reference to csc but it will make sure it builds

A known problem with `ProjectReference` is that VS is using 32-bit MSBuild.

https://github.com/microsoft/clrmd/blob/2da1ddadd8df4184bc4fdcf88e54b76b0eb9ebb9/src/TestTasks/src/Dump.cs#L28

**Comment by NextTurn** [comment]
> AFAIK most repos take advantage of creating an eng/afterSolutionTargets.props file to add targets that should happen after the solutoin is built:
https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#engaftersolutionbuildtargets-optional

I'm pretty sure that `AfterSolutionBuild.targets` won't work for us either. The targets will be executed after the main projects are built **and tested**.

**Comment by tmat** [comment]
@NextTurn 
The idea was to only build the project during build (as a ProjectReference), not to create the dump file.

> And then producing the .dmp files as part of the test harness, as ClrMD used to do.

It's generally a good practice for the build to be [deterministic](https://en.wikipedia.org/wiki/Reproducible_builds). Creating a crash dump is not deterministic.
