### ISSUE TITLE
Consider using named tuples in public and internal APIs

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#605]
... instead of Item1, Item2 everywhere. :/

**Comment by leculver** [comment]
What's the syntax for what you are proposing?  I was reading through tuple types documentation for C#, but apparently this isn't correct:  `public abstract IEnumerable<(MethodTable: ulong, Token: int)> EnumerateTypeDefToMethodTableMap();`.  Or do you mean defining a struct with Deconstruct?

**Comment by drewnoakes** [comment]
Type declaration is (int Age, string Name).

Instantiation is (1, "foo") or (Age: 1, Name: "Foo")

**Comment by leculver** [comment]
I think I've found and fixed all instances of this.  Please let me know if you find one I missed.

I've also taken the time to remove the last remaining IReadOnlyList usage which shouldn't have been there.
