### ISSUE TITLE
Publish ClrMD 2.0 RTM

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#614]
This issue is mostly a marker/FYI about the current schedule.  I currently plan to do an API review of all public methods of all public classes in ClrMD, fix all outstanding issues, publish RTM, and then update documentation.  Here's my current deadlines for each stage, subject to change if I find more work missing:

- [x] **API Review**
- [x] **Fix open issues** (and testing)
- [x] **Performance Work**
- [x] **Publish Release Candidate**
- [x] **RTM**:  6/5 (planned)
- [x] **Update Documentation**:  6/5 (planned)

I still expect there to be some issues to fix, but I'm trying to really wrap up the public surface area changes by 5/15.  There may be a ClrMD 2.1 and 2.2 within the next few months if I find I need to make more minor breaking API changes, but I'd like to avoid that if possible.

**Comment by leculver** [comment]
I marked a few items as "help wanted" if anyone is looking for a side project.  =)

**Comment by leculver** [comment]
I was pulled into some high priority work last week and continuing this week.  I have pushed back the RTM date.

**Comment by chrisnas** [comment]
Thanks for your hard work @leculver!

**Comment by arvindshmicrosoft** [comment]
This is great, can't wait!

**Comment by leculver** [comment]
I've published a 2.0 release candidate build for ClrMD here:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.0-rc.20278.6.  This is a last-call for breaking changes, as I will publish 2.0 RTM a week from tomorrow (June 5th) to give myself some bake time in case I forgot something or regressed something in the changes this week.

(@NextTurn as an fyi.)

**Comment by leculver** [comment]
We are still on track here.  I will be publishing the final 2.0 RTM build around 6-10pm PST tomorrow (6/5/2020).

**Comment by leculver** [comment]
I have published ClrMD 2.0 here:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.130507

However, I spent a lot of the week stress testing the runtime and I found an issue with the current implementation where we can leak memory in a very specific scenario: https://github.com/microsoft/clrmd/issues/727.  I ran out of time this week to get this fixed but I'll be working on it first thing Monday morning.
