### ISSUE TITLE
Should we replace ClrObject.IsNull with "Nullable<ClrObject>"?

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#617]
A code pattern I want to use is:

    ClrObject obj = ...;
    ClrObject? value = obj.GetObjectField("foo")?.GetObjectField("bar")?.GetObjectField("baz");

Currently in order to deref all of those values it requires `IsNull` checks, otherwise there will be an `InvalidOperationException` thrown if (for example) `bar` was null in the target process.  It's a bit of a pain to deal with nullable values.

I'm going to put up a prototype pull request of this soon.

**Comment by leculver** [comment]
Even with this design we have a problem where if we hit an invalid object, we'll still throw since we aren't checking `IsValid` along the way.

Maybe if "bar" isn't valid (but has a non-zero) address, it will simply return null when you try to get the values out of it.  This means something like "GetValueTypeField" would need to return `ClrValueType?` which is odd since value types are never null.

    ClrObject obj = ...;
    ClrObject? value = obj.GetObjectField("foo")?.GetValueTypeField("bar")?.GetObjectField("baz");

That looks reasonable, but this is a bit of a pain when `obj` isn't null:

    ClrValueType? value = obj.GetValueTypeField("bar");

**Comment by NextTurn** [comment]
> value types are never null

`default(Nullable<T>)` is `null`, but it's another story.

**Comment by leculver** [comment]
I'm not going to make this change in this release.
