### ISSUE TITLE
Implement array reading helpers in ClrMD 2.0

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#648]
The API review/cleanup checkin removed a few array functions that we do not want to support going forward.  We still need to add array helper functions for reading string[] arrays, ClrObject[] arrays, and valuetype[] arrays.  Additionally ReadArrayElements added a start position in the array to read from, but it is not yet implemented.

I likely won't get to implementing this before 2.0 RTM, so I'm marking it as help wanted.

**Comment by NextTurn** [comment]
Failure points of `ClrmdArray`:

- No index/length validation.
- No dimension validation.

However, there has been a rich set of implemented methods in `ClrArray`.
