### ISSUE TITLE
Attach to a 32bit from 64bit

### ISSUE THREAD

**Issue by Symbai** [microsoft/clrmd#666]
How can I passively attach to a 32bit process from a 64bit process? When using AttachToProcess method with AttachFlag.Passive I receive a `Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: Dac architecture mismatch!` exception.

**Comment by leculver** [comment]
You can't do this.  The CLR debugger layer is a native dll (this is mscordacwks.dll/mscordaccore.dll) and it's only built to match the target architecture of the runtime you are debugging.  ClrMD relies on this dll to function, so there's nothing I can reasonably do to make this work.
