### ISSUE TITLE
[Bug] DesktopMethod.Name property : missing first characters for some cases

### ISSUE THREAD

**Issue by Fread75** [Microsoft/clrmd#67]
In the case of a cached property, the `Desktop.Name` property will return something like `".ctor>b__0"` instead of `"<.ctor>b__0"`.

Suggested implementation to get the name of a method : take the signature, and remove the beginning part that matches the original name of its type (the original name of a type is the name returned by `DesktopRuntime.GetTypeName`, without going through the `FixGenerics` method).

This would have the beneficial behavior to return the complete name for explicit interface implementations : {InterfaceName}.{MethodName}, allowing us to differentiate between explicit and implicit interface implementation. It would also be more consistent with names retrieved from reflection.

**Comment by Fread75** [comment]
Hello,

I am currently using ClrMd for a professional project, and my company doesn't allow us *yet* to contribute to open source projects (mostly for legal reasons). They are working on it and in a few months, I would be authorized to submit a pull request to your repo.

In the mean time, I am working on a local clone of your repository. And I create here all the tickets that correspond to the commit I have made on my local repo, mostly to have your feedback in those points, and also in case that you want to correct them directly.

Regards,
Fred

**Comment by leculver** [comment]
Can you give an example?  I tried this in b30b597bc47d5fb1e335e6ca97649d4425baa188, but obviously I am not thinking of the right code pattern to generate that property.

**Comment by Fread75** [comment]
One example could be created by adding the line :
`lambda = x => x + 1;`
Into the constructor of the class Foo.
The lambda would be cached and a method `<.ctor>b__0` will be generated.

**Comment by leculver** [comment]
I could not reproduce this in recent builds.  Also creating a lambda in a constructor did not generate the expected method with the most recent version of roslyn.  If this still reproduces on ClrMD 1.0+ please let me know (be sure to @leculver so I see the message).  Thanks!
