### ISSUE TITLE
ClrType.EnumerateInterfaces throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Ne4to** [microsoft/clrmd#671]
version: 2.0.0-beta.20273.1
code example:
```csharp
var query = from obj in Heap.EnumerateObjects()
            where
                obj.IsValidObject
                && obj.Type.EnumerateInterfaces()
                    .Any(clrInterface => clrInterface.Name == "System.Runtime.CompilerServices.IAsyncStateMachine")
            select obj;

foreach (var clrObj in query)
{
    Console.WriteLine(clrObj.Address);
}
```

> System.ArgumentOutOfRangeException: 'Count cannot be less than zero. (Parameter 'count')'
>    at System.String.Ctor(Char c, Int32 count)
>    at Microsoft.Diagnostics.Runtime.DacInterface.MetadataImport.GetTypeDefProperties(Int32 token, String& name, TypeAttributes& attributes, Int32& mdParent)
>    at Microsoft.Diagnostics.Runtime.Implementation.ClrmdType.GetInterface(MetadataImport import, Int32 mdIFace)
>    at Microsoft.Diagnostics.Runtime.Implementation.ClrmdType.<EnumerateInterfaces>d__56.MoveNext()
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Heartbeat.Runtime.Analyzers.AsyncStateMachineAnalyzer.<>c.<Dump>b__5_0(ClrObject obj) in C:\Users\Ne4to\projects\GitHub\Ne4to\Heartbeat\src\Heartbeat.Runtime\Analyzers\AsyncStateMachineAnalyzer.cs:line 29
    
Exception is in this line: https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs#L76

If I change the following line it starts working https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs#L70
```diff
- if (!hr)
+ if (!hr.IsOK)
```

**Comment by NextTurn** [comment]
@Ne4to The fix should be available in 2.0.0-beta.20276.4. Would you like to create a follow-up issue w.r.t. the empty results?

**Comment by Ne4to** [comment]
@NextTurn Thank you. I updated the package and it works as expected, the query above returns data.

**Comment by Ne4to** [comment]
Reproduced on v2.0.130507
