### ISSUE TITLE
Thread ID should be ulong

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#676]
On non-windows platforms the process and thread IDs may be pointer sized.  Make them ulong instead of uint for compatibility.

**Comment by leculver** [comment]
Looks like uint is standard on linux, and I think OS X.  I'm not going to make this change.

**Comment by mikem8361** [comment]
The runtime and SOS use uint (32bit) for thread and process ids and have never had a problem even though on Linux the pid_t type is usually a ulong.

**Comment by leculver** [comment]
@mikem8361 I was going by [this](https://stackoverflow.com/questions/1922761/size-of-pid-t-uid-t-gid-t-on-linux), which says the pid is always 32bits, at least on intel architectures.  I wonder if that's true for arm and other architectures...

**Comment by mikem8361** [comment]
I was agreeing with you conclusion if that wasn't clear. I think (but not sure) it applies to arm/arm64 also.

**Comment by leculver** [comment]
>  I was agreeing with you conclusion if that wasn't clear. I think (but not sure) it applies to arm/arm64 also.

Yes, sorry.  We are on the same page.  I was just thinking out loud.  =)

**Comment by mikem8361** [comment]
We may want to reconsider reopening because on MacOS process/threads id do and can get larger than an uint.  I forgot/did know this at the time.

**Comment by NextTurn** [comment]
> `#define	PID_MAX		99999`

https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/bsd/sys/proc_internal.h#L639

For reference: https://apple.stackexchange.com/questions/51119/whats-the-maximum-pid-for-mac-os-x

**Comment by mikem8361** [comment]
Yes, it looks like process ids are uint/32bit but thread ids on MacOS are not. From Leandro Pereira who changed the runtime PAL get current thread id functions to return 64bit ids:

I don’t know what’s the deal with the Process and Thread IDs in MacOS.  On Linux, there seems to be a relationship between them.  On MacOS, they seem to be different kinds of animal (pid_t is 32-bit for instance: https://github.com/apple/darwin-xnu/blob/master/bsd/sys/_types.h#L72).

Looking at the implementation for pthread_threadid_np(), it seems it just returns the cached value returned by __thread_selfid(), which is the system call I used to use in one of my portable programs to obtain the thread id:
   Where the cache is set: https://github.com/apple/darwin-libpthread/blob/master/src/pthread.c#L1641
   Where the cache is used: https://github.com/apple/darwin-libpthread/blob/master/src/pthread.c#L1118

If you look at the syscall prototype, you’ll see it’s defined to return a uint64_t:
   https://github.com/apple/darwin-libpthread/blob/master/src/pthread.c#L270

With these in mind, it seems safe to assume here that sizeof(tid_t) – even though that type doesn’t exist – is indeed 64-bit on MacOS.  (And pid_t remains 32-bit.)

**Comment by leculver** [comment]
I'll make the change in ClrMD 2.1.
