### ISSUE TITLE
[Enhancement] Add a ParameterTypes property to ClrMethod

### ISSUE THREAD

**Issue by Fread75** [Microsoft/clrmd#68]
A simple property returning an array of string representing the types of the parameters of the method.

**Comment by Fread75** [comment]
Hello,

I am currently using ClrMd for a professional project, and my company doesn't allow us *yet* to contribute to open source projects (mostly for legal reasons). They are working on it and in a few months, I would be authorized to submit a pull request to your repo.

In the mean time, I am working on a local clone of your repository. And I create here all the tickets that correspond to the commit I have made on my local repo, mostly to have your feedback in those points, and also in case that you want to correct them directly.

Regards,
Fred

**Comment by leculver** [comment]
Thank you for the suggestion!

I don't think this is something I want to add to ClrMD.  I don't want to expose an API to produce string names of types here.  The only way I would implement this API is if I could hand out the real ClrType instances themselves...and that isn't possible with the underlying Dac APIs I use.

You should be able to do this yourself by using [IMetaDataImport](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadataimport-interface) to walk all of the parameters and do this yourself.
