### ISSUE TITLE
EnumerateInterfaces sometimes returns nothing

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#680]
```cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Diagnostics.Runtime;

internal static class Program
{
    private static async Task Async() => await Task.CompletedTask;

    private static void Main()
    {
        const string d__0 = "Program+<Async>d__0";

        Task task = Async();

        using var dt = DataTarget.AttachToProcess(Process.GetCurrentProcess().Id, false);
        using var rt = dt.ClrVersions.Single().CreateRuntime();

        var query = from obj in rt.Heap.EnumerateObjects()
                    where obj.Type?.Name == d__0
                    select obj.Type;

        foreach (var inf in query.Single().EnumerateInterfaces())
        {
            Console.WriteLine(inf);
        }

        Console.WriteLine();

        foreach (var inf in Type.GetType(d__0).GetInterfaces())
        {
            Console.WriteLine(inf);
        }
    }
}
```

```

System.Runtime.CompilerServices.IAsyncStateMachine
```

/cc @Ne4to

**Comment by Ne4to** [comment]
similar to #671 
https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/HResult.cs#L32
```diff
- public static implicit operator bool(HResult hr) => hr.Value >= 0;
+ public static implicit operator bool(HResult hr) => hr.IsOK;
```
it helps for this example, but I'm not sure about all usages of `if (hr) {}` and `if (!hr) {}` in the codebase

**Comment by weltkante** [comment]
Note that `hr >= 0` is the right thing to do if you want to _check for failure_
While `hr == S_OK` is specific to the API and usually _checks if results are available_

Checking whether results are available is different from checking for failures, handling both by a bool conversion and plain `if` statement seems dangerous, maybe code should be more explicit about what its checking?

**Comment by leculver** [comment]
> but I'm not sure about all usages of `if (hr) {}` and `if (!hr) {}` in the codebase

`if (hr)` is equvalent to `SUCCEEDED(hr)` and `if (!hr)` is equivalent to `FAILED(hr)`.  I haven't taken a look at the bug yet.
