### ISSUE TITLE
EnumerateStackTrace on the thread doesn't return Method name

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [microsoft/clrmd#703]
2.0.0-beta.20273.1

EnumerateStackTrace on the thread doesn't return Method name.
The idea is to get string-based stack trace of the thread.

![image](https://user-images.githubusercontent.com/9393016/83467369-b84e6480-a447-11ea-86ba-e1b2657c9ab1.png)

**Comment by leculver** [comment]
Here's a test that shows it working in 2.0:  https://github.com/microsoft/clrmd/pull/705

It's possible there's an issue where IBinaryLocator isn't finding the file in question.  Is this is a regression from 1.1?  Is there any more information on the scenario here?

**Comment by NextTurn** [comment]
There are a bunch of DAC functions that could fail during enumerating the stack trace. I'd suggest trying `x.IsBackground` in case you were not looking at the main thread. Could you please provide a full stack trace of the thread?

```cs
foreach (var frame in thread.EnumerateStackTrace())
{
    Console.WriteLine($"{frame.Kind} {frame}");
}
``

**Comment by ViacheslavAfanasyev** [comment]
I think it's resolved since the tested memory dump contains a lot of threads with no clrstack and it's confused me.
