### ISSUE TITLE
Samples need update using latest API

### ISSUE THREAD

**Issue by sukesh-ak** [microsoft/clrmd#707]
Great to see these API's being updated now.

Found that a lot of the functions and attributes have changed.
LoadCrashDump, PointerSize etc...

Can you please update these samples for the latest bits?
https://github.com/microsoft/dotnet-samples/tree/master/Microsoft.Diagnostics.Runtime/CLRMD

**Comment by NextTurn** [comment]
@leculver Why not migrate those samples here?

**Comment by sukesh-ak** [comment]
> @leculver Why not migrate those samples here?

That makes more sense.

**Comment by leculver** [comment]
That's for the feedback!  These samples will be updated and merged into ClrMD.  I am tracking that in issue #417, so I'm closing this as a duplicate.
