### ISSUE TITLE
Investigate RCW/CCW perf

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#723]
@ryanmolden Reports that the fix to IsCCW/IsRCW isn't as fast as I claim.  =)

**Comment by ryanmolden** [comment]
Technically I didn't call those functions, I just called GetComCallableWrapper (and if it returned null) GetRuntimeCallableWrapper across every item in the talkexample5.dmp heap (~24 million items), excluding ones that were arrays or were boxed values (didn't eliminate that many). With my 'check the object header bits before calling the function' approach my end to end time was 2 minutes (that includes LOTS of other stuff, NOT just time to call these two methods), simply blindly calling GetComCallableWrapper/GetRuntimeCallableWrapper (still filtering out the arrays and boxed values) causes the end to end to move to ~4 minutes.

**Comment by ryanmolden** [comment]
This is also in a parallel enum of gc heap segments, if there are any locks or other safety stuff going on in there

**Comment by leculver** [comment]
I'll take a look as soon as I have the basic benchmark project up and running.
