### ISSUE TITLE
Allow more ways to create a DataTarget not just by filename

### ISSUE THREAD

**Issue by 0blu** [microsoft/clrmd#736]
Hey,
after looking into the code a bit, I've noticed that only the _isTinyDump_ in `Minidump` with `MemoryMappedFile.CreateFromFile` requires a real `FileStream`, all other segments are using a normal `Stream`.
Would it be possible to remove the `FileStream` restriction and `File.Exists(crashDump)` from the code in favor of a new additional factory like `DataTarget.LoadFromStream(string displayName, Stream stream, CacheOptions? cacheOptions = null)`?

**Comment by NextTurn** [comment]
Ideally `LoadDump` could accept a `Stream`, an `ImmutableArray<Byte>` or even a `Byte*` just like what `PEReader` does.
