### ISSUE TITLE
What happened to GCHeap.EnumerateTypes from old ClrMD version

### ISSUE THREAD

**Issue by sukesh-ak** [microsoft/clrmd#737]
In the documentation of [Enumerating all types](https://github.com/microsoft/clrmd/blob/master/doc/TypesAndFields.md), it talks about GCHeap.EnumerateTypes. 
What did it translate to in v2?

Few more references are there...
GCHeap.EnumerateTypes
GCHeapStaticField 
GCHeapThreadStaticField

**Comment by leculver** [comment]
I've updated the FAQ to answer most of these questions in #742.  Note that "TypesAndFields.md" was out of date and intended to be deleted.  That document has been entirely subsumed by "GettingStarted.md".  Please be sure to read through all three items here, which are now up to date:  https://github.com/microsoft/clrmd/tree/master/doc.

Though it's possible I missed a section that might need updating.  =)

Lastly: GCHeapStaticField -> ClrStaticField.

Let me know if you have more questions.
