### ISSUE TITLE
How to use the debugger in the package for native windbg commands

### ISSUE THREAD

**Issue by sukesh-ak** [microsoft/clrmd#741]
I need to run native Windbg commands with ClrMD code for some automated analysis. Since debugger (DebugClient) and other required functions are already implemented and available in the package, can it be made available on the surface?

Usage would be something like
`using (DbgEngine dbg = new DbgEngine()) {

dbg.OpenDump(dumpfilepath, symbolpath);
string output = dbg.Execute("~"); // Any windbg command
Console.WriteLine(output);`

You can also set .extpath and load any native windbg extensions.

This is also useful when you are analyzing larger dumps and you want to dump out a set of native and CLR command outputs into a text file before you dig deeper.

I had a console version earlier (using my debugger) with a text file parameter where the text file had all the commands I wanted to be executed as a start.

**Comment by leculver** [comment]
Here's example code, it's not super polished but it works in what I use it for.  You might want to actually care about the DEBUG_OUTPUT mask as you'll get symbol load and other output in the current form here:

```csharp
    internal class DbgEngExecuteWrapper : IDebugOutputCallbacksWide
    {
        private static readonly object s_sync = new object();

        private readonly IDebugClient5 _client;
        private readonly IDebugControl5 _control;
        private readonly StringBuilder _result = new StringBuilder(1024);
        private readonly DEBUG_OUTPUT _mask;

        public DbgEngExecuteWrapper(IDebugClient5 client, IDebugControl5 control, DEBUG_OUTPUT mask)
        {
            _client = client;
            _control = control;
            _mask = mask;
        }

        public DbgEngExecuteWrapper(IDebugClient5 client, IDebugControl5 control)
        {
            _client = client;
            _control = control;
            _mask = (DEBUG_OUTPUT)0xffffffff;
        }

        public string? Execute(string cmd)
        {
            lock (s_sync)
            {
                _client.GetOutputCallbacksWide(out IDebugOutputCallbacksWide callbacks);

                try
                {
                    HResult hr = _client.SetOutputCallbacksWide(this);
                    if (!hr)
                        return null;

                    hr = _control.ExecuteWide(DEBUG_OUTCTL.THIS_CLIENT, cmd, DEBUG_EXECUTE.ECHO);
                    string result = _result.ToString();
                    return result;
                }
                finally
                {
                    if (callbacks != null)
                        _client.SetOutputCallbacksWide(callbacks);
                }
            }
        }

        int IDebugOutputCallbacksWide.Output(DEBUG_OUTPUT mask, string text)
        {
            if ((_mask & mask) == 0)
                return HResult.S_OK;

            lock (_result)
                _result.Append(text);

            return HResult.S_OK;
        }
    }
```

**Comment by leculver** [comment]
I'm sorry I misunderstood your question at first glance.

If you include the "Microsoft.Diagnostics.Runtime.Utilities" project then you get all of the IDebugClient interfaces.

Get a raw pointer using the `DebugCreate` win32 function (clrmd source has examples of this I think).  You then have to create ClrMD using that pointer with `DataTarget.CreateFromDbgEng`.  That will give you `IDebugClient` to call into and ClrMD will be created from it.

**Comment by sukesh-ak** [comment]
Thank you @leculver 
Will take a look at it and revert soon.

**Comment by sukesh-ak** [comment]
Got this working! Thanks
