### ISSUE TITLE
ClrMD 2.0 RTM questions and feedback thread

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#743]
Hello!

If you find a bug in ClrMD 2.0 please open a new issue to track it.  If you just have a question or feedback about ClrMD 2.0 please feel free to leave it here instead of creating a new issue or scattering the feedback among other places.  This will help me keep track of all questions in one place for a week or two while I stabilize the library and its uses.

Please be sure to read the FAQ and release notes for 2.0 listed here:  https://github.com/microsoft/clrmd/blob/master/doc/

**Comment by jwdj** [comment]
@leculver Will ThreadStaticFields be available again?
I'm interested in what static fields hold on to objects and I could not find a way to access the static vars in TLS.

```C#
foreach (var type in heap.EnumerateTypes())
{
    foreach (CLRAppDomain appDomain in runtime.AppDomains)
    {
        foreach (CLRThread thread in runtime.Threads)
        {
            foreach (GCHeapThreadStaticField field in type.ThreadStaticFields)
            {
                if (field.HasSimpleValue)
                    Console.WriteLine("{0}.{1} ({2}, {3:X}) = {4}", type.Name, field.Name, appDomain.ID, thread.OSThreadId, field.GetFieldValue(appDomain, thread));
            }
        }
    }
}
```

**Comment by leculver** [comment]
Were you actually getting real results out of the code you enumerated above?  There were only certain places that would work and produce anything...  I tended to not trust the thread static results at all.

> Will ThreadStaticFields be available again?

Eventually, yes.  It's all a matter of when I have time to go do that.

Though a warning, it's also possible it'll only work correctly in .Net Core.  Keep in mind the underlying problem here is that the dac private apis give weird or sometimes incorrect answers.  We aren't actually making non-security changes to Desktop CLR, so even when I find time to get this 100% working that may only be true for .Net Core.

**Comment by jwdj** [comment]
@leculver Thank you for your swift response. No I did not test the results. The code was from the 1.1 docs. I can understand that .NET Framework will only receive security fixes. But some things are just more simple in .NET Framework. Making a 32 bit application Large Address Aware for instance, is just a matter of specifying AnyCPU and Prefer 32 bit, while on .NET Core you must write a script to apply editbin /LARGEADDRESSAWARE after publishing.

**Comment by leculver** [comment]
Yep, I understand.  I'm just trying to set some expectations about why threadstatics aren't working and where we can realistically fix the issue.

**Comment by sukesh-ak** [comment]
@leculver How to get only ClrThread with managed code running, while walking the stack?
something like thread.IsManaged ?

I want to either ignore Native only threads or use dbgeng directly to show native threads.

**Comment by NextTurn** [comment]
> something like thread.IsManaged ?

https://github.com/microsoft/clrmd/blob/fb7948ab1502140d25ffe5b2da8a7caa1227dd7a/src/Microsoft.Diagnostics.Runtime/src/Common/ClrThread.cs#L10-L11

`ClrThread` always represents a manged thread. You need to enumerate the stack trace to see if a running frame is a managed one.

**Comment by sukesh-ak** [comment]
Was looking for a way to filter out the threads like below while enumerating all managed threads.

>>> Thread using ClrMD
Thread 5368
    000000a8a6afeee0 00007ffb64e86b93 

>>> Windbg using SOS
OS Thread Id: 0x5368 (3)
        Child SP               IP Call Site

**Comment by NextTurn** [comment]
@leculver All implementations of `IBinaryLocator`s don't work with build IDs. Is this going to be implemented in the future?

**Comment by leculver** [comment]
> @leculver All implementations of `IBinaryLocator`s don't work with build IDs. Is this going to be implemented in the future?

Yes they are intended to be implemented in the future.

**Comment by mikem8361** [comment]
@leculver Are you going to use Micrsoft.SymbolStore in the symstore? It is one-stop shopping for symbol server index generation for all the platforms and has code to do the downloading, caching and directory searching.

**Comment by leculver** [comment]
@mikem8361 That's probably the best course of action.  Why isn't it on NuGet?  (Or am I searching wrong?)

**Comment by mikem8361** [comment]
It isn’t on nuget.org but in the dotnet-tools feed (https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json). Your NuGet.config already has that feed. The latest version is 1.0.130801. You can set up a DARC subscription to update the version automatically when symstore gets updated like the diagnostics repo does. Juan can help you setup the subscription.

**Comment by leculver** [comment]
@holc-tkomp Some replies to your feedback in a parallel thread:

> I'd like to mention that this repo is quite scarce in tags and releases and there was no new tags/releases since Dec 19, 2019

In a perfect world I'd be more on top of the bookkeeping for ClrMD, but I find that's not my strong suit.  Unfortunately, anything which adds additional inertia to releasing versions of ClrMD generally means I'll simply be less likely to make changes to the library and release them.  Keep in mind that ClrMD is maybe 5-10% of my overall job at Microsoft and I have to keep my work on the library time-boxed to make progress on other projects.  Me not creating releases can be fairly attributed to a little laziness or inattention to detail, but also those releases tend to only be used by a few people and require a not-insignificant amount of work on my part.

However, I _do_ plan to keep release notes better up to date.  I'll start working on that tomorrow and stop putting it off.  Release notes will only contain changes from 2.0 and beyond and not 1.1 -> 2.0 because ClrMD 2.0 is basically a complete rewrite.

> `EnumerateMemoryRegions`

The `ClrRuntime.EnumerateMemoryRegions` feature was really rough around the edges.  It gave incorrect information around certain heap sizes (see for example https://github.com/dotnet/diagnostics/issues/1108 which also affects ClrMD), and some of the data returned was done heuristically which was slow and error prone.

I had planned to bring back this function as an extension method in `Microsoft.Diagnostics.Runtime.Utilities`, but it's really far down on my priority list right now.

> Dropping support for .NET Framework <4.5 runtimes is also a huge thing to consider for us, as so far we state to support frameworks 2.0 - 4.7.2. 

Keep in mind that ClrMD 2.0 is meant to be the library of the future.  We still support ClrMD 1.1 to fix major bugs and I still accept pull requests to that library.  If it doesn't make sense for you to upgrade you don't have to.  However, there are definitely a lot of bugs we have fixed in ClrMD 2.0 that affect correctness and those changes can't really be ported back to 1.1 easily.  This is because ClrMD 2.0 is basically a complete rewrite of the internals of the library and we cleaned up a lot along the way and it's not possible to translate that back to 1.1...we'll simply have to fix bugs as we find them.

Lastly, I'd say the internals of ClrMD 2.0 were intended to be very modular.  It's _possible_ that someone could come along and implement IRuntimeBuilder and its interfaces for 2.0 and 4.0, but it would be a big undertaking.  I'm hoping that eventually it will be a moot point though.

@holc-tkomp: Did I miss any questions or concerns from the other thread?

**Comment by holc-tkomp** [comment]
No, I get it.

I'm just looking into if upgrading to 2.0 is worth it for us. The major value of upgrading to 2.0 would be some of the bug fixes and improvements, which are unfortunately not available in 1.1.

But on the other hand we've used quite a bit of functionalities that are now gone and that renders upgrading and making the app behave as before (show the same results) quite a time consuming task.

So I'm basically fetching information which might help us pick the best approach.

I'll probably make some "Can you still retrieve the X somehow" kind of questions (as an separate issues) in the near future, so sorry for that in advance 😅

**Comment by leculver** [comment]
> I'll probably make some "Can you still retrieve the X somehow" kind of questions (as an separate issues) in the near future, so sorry for that in advance 😅

You are welcome to put those here too (creating new issues is fine as well).  Happy to answer questions as you have them.

**Comment by sukesh-ak** [comment]
@leculver 
Can we distribute dbgeng.dll, dbghelp.dll, symsrv.dll & srcsrv.dll (from windbg package) with the tool we create using ClrMD?
The ones which comes with the OS is not updated frequently thus the question.
Any public documentation on the distribution policy of these files?

btw, I pushed out the debugger using ClrMD 2.0 here
https://github.com/sukesh-ak/AutoDebug

**Comment by leculver** [comment]
@sukesh-ak I have passed your question along to the dbgeng team.  Hopefully they will reply back here.

**Comment by aluhrs13** [comment]
Yep, you can redistribute some debugger binaries from the SDK/WDK. You can find the list here - https://docs.microsoft.com/en-us/legal/windows-sdk/redist if something you need to redist isn't on that list and you have a good reason, you can reach out to me.

**Comment by sukesh-ak** [comment]
Thank you @aluhrs13 
This is the link I was looking for. It mentions about the files I need.

**Comment by AArnott** [comment]
I'm trying to update to 2.0 in https://github.com/microsoft/vs-threading/pull/649. The breaking API changes are not obvious to fix and I wonder if you can give some guidance on where to find substitute APIs. Here are the missing APIs that are hitting me (with some filled in to help others):

1.x API | 2.x API
--|--
`ClrValueClass` | `ClrValueType`
`ClrObject.GetField<T>` | `ClrObject.ReadField<T>`
`ClrValueClass.GetObjectField` | `ClrValueType.ReadObjectField`
`ClrObject.GetValueClassField` | `ClrObject.ReadValueTypeField`
`ClrHeap.ReadPointer` | 
`ClrThread.EnumerateStackObjects` | 
`ClrInstanceField.IsValueClass` | `ClrInstanceField.IsValueType`
`IDebugClient` | 
`IDebugControl` | 
`DataTarget.CreateFromDebuggerInterface` | 
`DEBUG_OUTCTL` | 
`DEBUG_OUTPUT` | 
`DEBUG_EXECUTE` |

**Comment by NextTurn** [comment]
@AArnott 

```cs
using M.D.R.I = Microsoft.Diagnostics.Runtime.Interop; // in Microsoft.Diagnostics.Runtime.Utilities package
```

| 1.x API | 2.x API |
| ------- | ------- |
| `ClrHeap.ReadPointer` | `DataTarget.DataReader.ReadPointer` |
| `ClrThread.EnumerateStackObjects` | `ClrThread.EnumerateStackRoots` |
| `IDebugClient` | `M.D.R.I.IDebugClient` |
| `IDebugControl` | `M.D.R.I.IDebugControl` |
| `DEBUG_OUTCTL` | `M.D.R.I.DEBUG_OUTCTL` |
| `DEBUG_OUTPUT` | `M.D.R.I.DEBUG_OUTPUT` |
| `DEBUG_EXECUTE` | `M.D.R.I.DEBUG_EXECUTE` |

**Comment by AArnott** [comment]
Thanks, @NextTurn. When will M.D.R.I. be released as a stable package? It will be a problem for my package to pick up an unstable dependency for long.

**Comment by NextTurn** [comment]
Ping @leculver. The latest *Microsoft.Diagnostics.Runtime.Utilities* package is still a RC.

**Comment by leculver** [comment]
Sorry for the delay, I was out sick yesterday.

The utilities package shouldn't be an RC.  I'll ship a new one this week that's not RTM.  There's no difference between the version out now and the one I'll ship that's not marked -rc, so you can go ahead and do that work without fear of it breaking.

> DataTarget.CreateFromDebuggerInterface

This is now `DataTarget.CreateFromDbgEng`.  The old method was ambiguous as to what debugger we were referring to.

Let me know if you run into any other issues.

**Comment by AArnott** [comment]
Thanks, @NextTurn  and @leculver. 

> I'll ship a new one this week that's not RTM

I'll assume that was a typo and that you'll actually ship an "RTM" verison. :)

**Comment by sukesh-ak** [comment]
@AArnott I have a sample of using DataTarget.CreateFromDbgEng [here](https://github.com/sukesh-ak/AutoDebug/blob/1fd08bfe50ca69720c0320cebc50fd162fcc262e/AutoDebug/DbgEngine.cs#L61) if it helps.

**Comment by leculver** [comment]
> I'll assume that was a typo and that you'll actually ship an "RTM" version. :)

Yes, correct.  I'm still a little foggy today, sorry about that.  =)

**Comment by AArnott** [comment]
Thanks for the offer, @sukesh-ak. I have completed the upgrade and the testing looks good.

**Comment by arvindshmicrosoft** [comment]
@leculver - seconding what @NextTurn mentioned in https://github.com/microsoft/clrmd/issues/743#issuecomment-668934490, the current Nuget for `Microsoft.Diagnostics.Runtime.Utilities` still says RC (`2.0.0-rc.20303.3`). Would be good to remove the pre-release status.
