### ISSUE TITLE
ClrMD 2.0: Missing access to ThreadPool details 

### ISSUE THREAD

**Issue by chrisnas** [microsoft/clrmd#746]
ClrRuntime does not expose ClrThreadPool ThreadPool anymore.
Note that GetThreadPoolData is available at SosDac level but does not seem to be called.

**Comment by leculver** [comment]
The Threadpool works completely differently in .Net Core than it does on desktop CLR.  Most of the functions that the old ClrMD threadpool code exposed (including the dac functions) don't produce the right answers anymore.  I'd like to add this back at some point (and plan to) but it will be a lot bigger than just porting the old 1.1 code...I'll need to go dig through new implementation and see what we should actually expose through APIs.

**Comment by meriffa** [comment]
This issue is marked as "completed", even though ClrRuntime.ThreadPool returns null whereas SOS.threadpool returns the correct information.

Does that mean that this update was rejected?
