### ISSUE TITLE
ToString Format mismatch in MemoryRange.cs

### ISSUE THREAD

**Issue by sukesh-ak** [microsoft/clrmd#750]
Braces mismatch in the below function. Just a typo.

Opening with square braces and close with normal one here
public override string ToString() => $"[{Start:x},{End:x}**)**";

**Comment by sukesh-ak** [comment]
Braces mismatch like below output. Not sure if you understood.

Ephemeral object range: [1d1445a1000,1d14477ffe8)
committed memory range: [1d1445a0000,1d144782000) 
reserved memory range: [1d144782000,1d2445a0000)

**Comment by NextTurn** [comment]
We don't call them braces. `[` is a (square) bracket which specifies an inclusive address, `)` is a parenthesis which specifies an exclusive address.
