### ISSUE TITLE
When will there be a new nuget release of CLRMD?

### ISSUE THREAD

**Issue by discostu105** [Microsoft/clrmd#76]
CLRMD is a great library and we're actively using it (https://github.com/Dynatrace/superdump).

The last (and only) release of CLRMD was in October 2015 (0.8.31-beta, which is also on nuget.org). Clearly, some work has been done on the library since then. Are there plans for a new release? Should we build CLRMD ourself to get the latest and greatest bits?

**Comment by chuanboz** [comment]
+1, find this cool library and want to know when is it officially released so we could reference it in production.

**Comment by leculver** [comment]
I am working on this now (but can't promise any ETA).

ClrMD fell into a window of time before we really figured out the open source thing.  This project was one of the first to be open sourced and didn't get update to work like other projects (such as coreclr/corefx).  As such it's not up to date with our current workflow, which is why it's been so long since release.

**Comment by discostu105** [comment]
Thanks @leculver! It's great to hear that something is happening at least.

**Comment by leculver** [comment]
I know it's been three weeks, but this hasn't been forgotten or dropped.  Work has been scheduled and hopefully "Soon (TM)" we should have the right process in place.  Once all the work is done to build, sign, and package things we can ship as frequently as needed.

**Comment by discostu105** [comment]
@leculver No worries. Keep up the good work! +1 for this great library!

**Comment by weltkante** [comment]
@leculver the [WPFDXInterop](https://github.com/Microsoft/WPFDXInterop) project seems to have similar problems, being an old repository and getting no attention anymore. I know that repository is a totally different subject, sorry for cross-posting but any idea how to get attention back to it again, or if that's even possible?

**Comment by leculver** [comment]
@weltkante Sorry, this is outside my team's area so I'm not sure I can promise a response here.  I've asked around but the person to find out from is on vacation.  I'll reply back if I find something I can share (when they get back).

**Comment by leculver** [comment]
@discostu105 @chuanboz I have published a new release of ClrMD to NuGet.  I haven't decided what cadence to ship at in the future, but it now only takes me a half hour to release changes (instead of the week it took before).  I should be able to get fixes out faster now.

**Comment by leculver** [comment]
@zone117x Would you mind pulling down the Microsoft.Diagnostics.Runtime.Latest package now that we have our act together?  =)

I worry that someone will get confused, and it's now out of date.

Thank you!

**Comment by zone117x** [comment]
Nuget is having a server error when trying to delist the package. Will try it again later 👍
