### ISSUE TITLE
Add `DataTarget.SymbolPath` or `IBinaryLocator.SymbolPath`

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#771]
The symbol locator implementation was intentionally marked internal, but there still should be a way to set the symbol path other than setting _NT_SYMBOL_PATH.  I also need to go do symbol resolution on Linux as well, so I will likely roll that change into this too.

**Comment by sukesh-ak** [comment]
Ideally DataTarget functions should have a overload with SymbolPath parameter.

DataTarget.AttachToProcess
DataTarget.CreateFromDbgEng
DataTarget.CreateSnapshotAndAttach
DataTarget.LoadDump

**Comment by baal2000** [comment]
BTW [GettingStarted.md](https://github.com/microsoft/clrmd/blob/master/doc/GettingStarted.md#getting-the-dac-from-the-symbol-server) still mentions `DataTarget.SymbolLocator` (no longer present in ClrMd v.2)
