### ISSUE TITLE
Is it possible to get !runaway times?

### ISSUE THREAD

**Issue by tysmithnet** [Microsoft/clrmd#79]
We're using CLRMd for automated memory dump analysis, and we'd like to be able to get the sos !runaway times. Is it possible to do this with CLRMd?

@karelz :)

**Comment by karelz** [comment]
@leculver the other spin (assuming ClrMd doesn't support it) on this might be: How to use !runaway in pure windbg. I know it doesn't belong here, but I thought this may be best communication channel for this particular case and maybe ClrMd already does support it :).
If you disagree (which is possible), I apologize and will happily use/guide people to use more appropriate channel. Thanks!

**Comment by leculver** [comment]
Karel is correct, using WinDbg for this is how you would need to do it.  ClrMD is a view over managed code, and isn't intended to be a general debugging api for more OS and native code specific stuff.

Here's some code I've used in the side project I've been building (I make no claims on correctness or code quality):


        class ExecuteWrapper : IDebugOutputCallbacks, IDisposable
        {
            private bool _disposed = false; // To detect redundant calls
            private IDebugOutputCallbacks _old;
            private IDebugClient _client;
            private IDebugControl _control;
            private StringBuilder _builder = new StringBuilder();

            public ExecuteWrapper(IDebugClient client)
            {
                _client = client;
                _control = (IDebugControl)client;

                int hr = client.GetOutputCallbacks(out _old);
                Debug.Assert(hr == 0);

                hr = client.SetOutputCallbacks(this);
                Debug.Assert(hr == 0);
            }

            public string Execute(string cmd)
            {
                lock (_builder)
                    _builder.Clear();
                
                int hr = _control.Execute(DEBUG_OUTCTL.THIS_CLIENT, cmd, DEBUG_EXECUTE.NOT_LOGGED);
                Debug.Assert(hr == 0);
                //todo:  Something with hr, it may be an error legitimately.

                lock (_builder)
                    return _builder.ToString();
            }

            int IDebugOutputCallbacks.Output(DEBUG_OUTPUT mask, string text)
            {
                // TODO: Check mask and write to appropriate location.

                lock (_builder)
                    _builder.Append(text);

                return 0;
            }

            #region IDisposable Support

            protected virtual void Dispose(bool disposing)
            {
                if (!_disposed)
                {
                    _client.SetOutputCallbacks(_old);
                    _disposed = true;
                }
            }

            ~ExecuteWrapper()
            {
                Dispose(false);
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }
            #endregion
        }

`DataTarget.DebuggerInterface` is an instance of IDebugClient (if you use default options for creating a DataTarget).  That is used for the constructor of this type.  Running "Execute" will run an arbitrary windbg command and return it back as text.  Then I've been Regex'ing the return value for what I was working on.  Not the prettiest solution, but it works.

The full IDebug* suite of interfaces is wrapped in ClrMD (to varying degrees of usability).  For more advanced stuff (other than running !commands), you should refer to the public documentation [here](https://msdn.microsoft.com/en-us/library/windows/hardware/ff549827(v=vs.85).aspx).

**Comment by tysmithnet** [comment]
Thanks, @leculver I'll give this a shot.

**Comment by karelz** [comment]
Thanks @leculver for super-fast answer!

**Comment by discostu105** [comment]
@tysmithnet if you're interested in kernel- and usertime of each thread, you can get them via `IDebugAdvanced2`. Our project is based on ClrMD too, but we use additional interfaces like `IDebugClient` and friends for additional information that ClrMD does not provide.

Here is our implementation for getting KernelTime and UserTime for each thread: https://github.com/Dynatrace/superdump/blob/master/src/SuperDump/Analyzers/ThreadAnalyzer.cs#L152

**Comment by tysmithnet** [comment]
@discostu105 This is really really helpful!
