### ISSUE TITLE
Mismatched dac. Dac version: 4.8.4180.0, expected: 0.0.0.0.

### ISSUE THREAD

**Issue by AArnott** [microsoft/clrmd#812]
Using Microsoft.Diagnostics.Runtime 2.0.137201...

With no changes to our source code, it seems that our windbg extension has stopped working. It now throws:

> System.InvalidOperationException: 'Mismatched dac. Dac version: 4.8.4180.0, expected: 0.0.0.0.'

From this line:

https://github.com/microsoft/vs-threading/blob/7614a11d98a9a57e1c2de47381c3d46e426ad0d8/src/SosThreadingTools/DebuggerContext.cs#L75

If I change it to:

```cs
runtime = dataTarget.ClrVersions.Single().CreateRuntime();
```

The exception changes to:

> System.IO.FileNotFoundException: 'Could not find matching DAC for this runtime.'

Did the .NET Framework just get patched with something that broke this? Any idea what we're doing wrong or what we should do instead?

**Comment by leculver** [comment]
I have a fix for this in PR #813.

We call GetModuleVersionInformation twice.  The first time to get the size required (with a null buffer), and the second time to obtain it.  This has test coverage, in our testbed this succeeds just fine.  However when using the crash dump you gave me offline, this first call fails for some unknown reason.  I'm not sure if this is dbgeng weirdness, bug, or something else.  In any case, by skipping the first call and just ensuring a large enough buffer the first time we avoid the issue entirely.

@AArnott I'll have a new build out in a day or so on NuGet with this fix.

**Comment by leculver** [comment]
@AArnott Shipped here:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.142501
