### ISSUE TITLE
Need to access method info even without binary

### ISSUE THREAD

**Issue by dailongchen** [microsoft/clrmd#823]
https://github.com/microsoft/clrmd/blob/60be1e1302c74f0c415a9e71d3b75d779936e17d/src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs#L1299

In Clrmd 1.1 logic, after loaded Windows minidump, even without related binary, we can still get many useful information from frame.Method, like method name, module info...
But in 2.0 code, frame.Method will be set to null if fail to GetMethodTableSlot. And even frameName is also not filled.

May I know is that possible to still create ClrmdMethod in this case?
I tried to remove the check of "builder.Init" result in RuntimeBuilder.CreateMethodFromHandle function, it seems can still work fine.

Thanks,

**Comment by leculver** [comment]
This should be fixed now.
