### ISSUE TITLE
EnumerateFinalizableObjects and EnumerateFinalizerRoots appear backwards

### ISSUE THREAD

**Issue by WilliamXieMSFT** [microsoft/clrmd#831]
# Environment
Windows 10 (Build 10.0.19042.508)
Tested on .NET 4.7.2, 4.8, .NET Core 2.1, 3.1, 5.0

# Sample Code
## Code for the heap dump to be analyzed
```

    class Indestructible
    {
        ~Indestructible()
        {
            while (true) ;
        }
    }

    static void Main(string[] args)
    {
        for (int i = 0; i < 10_000; i++)
        {
            _ = new Indestructible();
        }

        GC.Collect(2);

        Console.ReadLine();
    }

```

## Use CLRMD to see FinalizerQueue
```
            string dumpPath = @"[PATH TO .DMP FILE]";

            using DataTarget dataTarget = DataTarget.LoadDump(dumpPath);
            foreach (ClrInfo clr in dataTarget.ClrVersions)
            {
                using ClrRuntime runtime = clr.CreateRuntime();
                ClrHeap heap = runtime.Heap;

                List<ClrObject> finalizableObjects = new List<ClrObject>();
                Console.WriteLine("===");
                Console.WriteLine("FinalizerQueueObjects:");
                Console.WriteLine("===");
                foreach (var obj in heap.EnumerateFinalizableObjects())
                {
                    Console.WriteLine($"{obj.Address:x16} {obj.Type.MethodTable:x16} {obj.Size,8:D} {obj.Type.Name}");
                    finalizableObjects.Add(obj);
                }

                List<ClrFinalizerRoot> finalizerRoots = new List<ClrFinalizerRoot>();
                Console.WriteLine("===");
                Console.WriteLine("FinalizerQueueRoots:");
                Console.WriteLine("===");
                foreach (var obj in heap.EnumerateFinalizerRoots())
                {
                    Console.WriteLine($"{obj.Address:x16} {obj.Object.Type.MethodTable:x16} {obj.Object.Size,8:D} {obj.Object.Type.Name}");
                    finalizerRoots.Add(obj);
                }
```

# Results
```
===
FinalizerQueueObjects:
===
00000202a3c522c8 00007ffac0b24078       32 Microsoft.Win32.SafeHandles.SafePEFileHandle
00000202a3c52d80 00007ffac0b23b48       64 System.Threading.ReaderWriterLock
00000202a3c535f0 00007ffac0b26a10       96 System.Threading.Thread
00000202a3c559f8 00007ffac0b295d0       32 Microsoft.Win32.SafeHandles.SafeFileHandle
00000202a3c56318 00007ffac0b14320       32 Microsoft.Win32.SafeHandles.SafeViewOfFileHandle
00000202a3c56338 00007ffac0b143b0       32 Microsoft.Win32.SafeHandles.SafeFileMappingHandle
00000202a3c56820 00007ffac0b774f8       32 System.IO.StreamWriter+MdaHelper
00000202a3c56e80 00007ffac0b295d0       32 Microsoft.Win32.SafeHandles.SafeFileHandle
===
FinalizerQueueRoots:
===
00000202a3ad2b60 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2b68 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2b70 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2b78 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2b80 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2b88 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2b90 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2b98 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2ba0 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2ba8 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2bb0 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2bb8 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2bc0 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2bc8 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2bd0 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2bd8 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2be0 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2be8 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2bf0 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2bf8 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
00000202a3ad2c00 00007ffa64567448       24 ConApp_MemoryAnalyzer.Indestructible
```

# Other things to note
The Unit tests are trying to reference `clrmd\src\TestTargets\TestTargets.csproj`, but the actual file name is `TestTargets.proj`
https://github.com/microsoft/clrmd/blob/master/src/TestTargets/TestTargets.proj

After fixing the above issue, there's no generation of the dump file (`clrmd\src\TestTargets\bin\x64\FinalizationQueue_wks.dmp`) so the unit tests fail with System.IO.FileNotFoundException. When attempting to fix the build to generate the .dmp file, I kept getting the following error so I gave up.

`C:\Repos\clrmd\src\TestTargets\TestTargets.proj(101,5): error MSB4044: The "Dump" task was not given a value for the
required parameter "ExePath".`

**Comment by leculver** [comment]
Hmm, the output you've listed looks right to me, though I think you've mislabeled them:

                Console.WriteLine("FinalizerQueueObjects:");  <== Not a good name for what these are.
                Console.WriteLine("===");
                foreach (var obj in heap.EnumerateFinalizableObjects())

These aren't "FinalizerQueueObjects", these are finalizable objects on the GC heap.  The objects listed there, such as `SafePEFileHandle`, `ReaderWriterLock`, etc are all **live** objects on the GC heap which will be finalized when the objects are collected by the GC.

Your listing of `FinalizerQueueRoots` are correct too.  Those are objects that have been collected by the GC, but since they defined a finalizer, they are "alive" in the sense that they are rooted by the FQ.  Once these objects are processed by the FQ (by calling their finalizer), they will be cleaned up by the GC...  (Well, they will be cleaned up by the GC assuming that the finalizer doesn't resurrect the object, but that's just being pedantic.)

Did I miss something here?

> Unit tests

Thanks for the report on the unit tests!  I do need to clean that up.  Currently the way to build them successfully looks like:

    set Configuration=Debug
    cd src\testtasks
    dotnet build
    cd ..\testtargets
    dotnet build

It's _supposed_ to just be `dotnet build` from within TestTargets, but it's definitely broken right now and needs to be cleaned up.

**Comment by WilliamXieMSFT** [comment]
Thank you for the explanation, Lee! I was confused around the naming of these types.
