### ISSUE TITLE
Missing leading zero for binary index path

### ISSUE THREAD

**Issue by dailongchen** [microsoft/clrmd#835]
https://github.com/microsoft/clrmd/blob/a3fddc25187af597e67bfdc757ea2771c23d144e/src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs#L332

I found CLRMD cannot find some binaries from Microsoft Symbol Store, for example below ntdll.dll case:
> http://msdl.microsoft.com/download/symbols/ntdll.dll/0c1bb3011f0000/ntdll.dll

For this file, its timestamp is 203141889 (1976-06-09T04:18:09+00:00), I guess it comes from a build machine with wrong time settings.
Current logic will work out the index as "c1bb3011f0000", which does not exist in symbol store.

I think we may need to format the timestamp using "x8", or is that just my misunderstanding?

Thanks,

**Comment by leculver** [comment]
I think you are right, the first should be `:x8`, but `imageSize` should remain `:x`.

Thanks for the report!

**Comment by leculver** [comment]
Should be fixed here:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.151903
