### ISSUE TITLE
CLRMD isn't signed with a strong name and can't be referenced from strong named apps

### ISSUE THREAD

**Issue by 0xd4d** [Microsoft/clrmd#84]
A strong named application can't use CLRMD since it's unsigned. An exception is thrown at runtime.

It would be nice if the nuget package contained a strong named CLRMD assembly.

Current workaround is to compile the sources yourself and add your own snk file.

**Comment by adamsitnik** [comment]
BenchmarkDotNet has the same problem with ClrMD

it would be great to have a strong named NuGet package

**Comment by leculver** [comment]
This was fixed a while back.
