### ISSUE TITLE
Equivalent for EnumerateMemoryRegions

### ISSUE THREAD

**Issue by pr8x** [microsoft/clrmd#877]
I am currently upgrading some code to clrmd v2 and I noticed that `EnumerateMemoryRegions` is gone. I saw some other post mentioning that there's plans (in the future) to include this in the utilities package. But is there something right now I can do to emulate this functionality? My goal is to revive https://github.com/goldshtn/minidumper (kinda) to help with reducing the size of my crash dumps. I tried replacing `EnumerateMemoryRegions` with `ClrHeap.Segments`, but that doesn't seem to be enough for debugging. Any ideas? Thanks in advance.

**Comment by leculver** [comment]
We removed this because it used heuristics and wasn't very accurate.  This feature is back now but implemented in a way I can maintain with `ClrRuntime.EnumerateClrNativeHeaps`.
