### ISSUE TITLE
PdbReader's GetPdbProperties can throw uncaught UnauthorizedAccessException

### ISSUE THREAD

**Issue by smourier** [Microsoft/clrmd#88]
There are cases when the pdbFile argument of GetPdbProperties points to a directory (like for example c:\symbols\kernel32.pdb) for example when _NT_SYMBOL_PATH=c:\symbols (w/o anything else).

In this case File.OpenRead(pdbFile) throws an expected but painful UnauthorizedAccessException.

There are many ways to change this, for example:

1) add this code to GetPdbProperties (simulate the IOException that's documented to happen)
```
if (Directory.Exists(pdbFile))
    throw new IOException();
```

2) add this code to GetPdbProperties (don't throw)
```
    if (Directory.Exists(pdbFile))
    {
        signature = Guid.Empty;
        age = 0;
        return;
    }
```

3) change ValidatePdb and add this code to it:
```
      catch (UnauthorizedAccessException)
      {
        return false;
      }
```

**Comment by mitikov** [comment]
I like the exception to bubble to allow calling code/user figure out what's next.

I guess silent 'sorry no' could be of little use...

**Comment by smourier** [comment]
@mitikov - Of course, I agree when you're calling the method yourself, but there are cases where this method is called implicitly (I don't remember my use case, but I think it was around the symbol locator). In this case, the "user" cannot figure what's next.

**Comment by mitikov** [comment]
@smourier The code is consumed by `DefaultSymbolLocator.FindPdb` that is sitting inside `DataTarget.SymbolLocator` property (with public setter) that gives a default implementation of SymbolLocator.

I did not find any code usages OOB as well, so it would be good to know a bit more about the scenario you are trying to achieve. 

As for technical aspect - the method description states: `Validates whether a pdb on disk matches....`

[Framework Design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exception-throwing) suggest: 

> Execution failure occurs whenever a member cannot do what it was designed to do (what the member name implies).

It seems we might need to update `PdbReader.GetPdbProperties` code to catch whatever bubbled and wrap into IOException per code documentation.

As a result the default `SymbolLocator` impl. of ValidatePDB will catch exception and report validation failed.
The cost is loosing the knowledge why PDB was not loaded (like file access issues in the scenario you've mentioned) in default scenario.

Despite a vew from outside as it looks to be quite easy to overcome the problem in custom code, I guess in reality there could be troubles on the way.

That is why knowing the scenario/use-case is much appreciated :)

**Comment by smourier** [comment]
Ok, I found my use case back. It's like I said in my first comment:

    Environment.SetEnvironmentVariable("_NT_SYMBOL_PATH", @"c:\symbols");
    using (var file = new PEFile(@"c:\windows\system32\kernel32.dll"))
    {
        new DefaultSymbolLocator().FindPdb(file.PdbInfo);
    }

This raises the following error, at least on my machine:

```
System.UnauthorizedAccessException: Access to the path 'c:\symbols\kernel32.pdb' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbReader.GetPdbProperties(String pdbFile, Guid& signature, Int32& age)
   at Microsoft.Diagnostics.Runtime.Utilities.SymbolLocator.ValidatePdb(String pdbName, Guid guid, Int32 age)
   at Microsoft.Diagnostics.Runtime.Utilities.DefaultSymbolLocator.FindPdb(String pdbName, Guid pdbIndexGuid, Int32 pdbIndexAge)
   at Microsoft.Diagnostics.Runtime.Utilities.SymbolLocator.FindPdb(PdbInfo pdb)
   at PdbDump.Program.SafeMain(String[] args) in D:\SimonMourier\Tfs\PdbDump\PdbDump\PdbDump\Program.cs:line 65
   at PdbDump.Program.Main(String[] args) in D:\SimonMourier\Tfs\PdbDump\PdbDump\PdbDump\Program.cs:line 38
```

**Comment by leculver** [comment]
Interesting.  Reading through this and looking at the code, I think `PdbReader.GetPdbProperties` should throw.  You are asking PdbReader to give you a concrete answer on a single pdb, and it's appropriate to throw UnauthorizedException there.

However, FindPdb should be checking multiple paths and a single unauthorized location shouldn't result in aborting the entire path and throwing.  Looking at `SymbolLocator.ValidateBinary` it looks like we wrap everything with an untyped `catch` block, and I think it's appropriate to do the same in `SymbolLocator.ValidatePdb`.

I don't like untyped `catch` blocks in general, but in this narrow window when validating a binary it makes some sense.  I worry a little about applications which opt into handling corrupted state exceptions, but since I replaced PEFile with a safer PEImage, that is also less of a concern.
