### ISSUE TITLE
Complete Mac OS X Support

### ISSUE THREAD

**Issue by sdmaclea** [microsoft/clrmd#888]
The equivalent of #690 is needed for osx-arm64 

https://github.com/microsoft/clrmd/blob/a2c23aa4525a237d33e84fcfbfb5d02215797db4/src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/MacOSFunctions.cs#L27-L30

I am also not sure if we to do something special for universal binaries.

/cc @nxtn @leculver

**Comment by mikem8361** [comment]
It looks like the check for the cpu type can just be removed. The header magic field should be validated instead. @sdmaclea this code doesn't handle MachOFat binaries yet. Is that going to be important?

I can do this change in my current single-file work. It may be a while before the single-file changes are ready so if you want it sooner.

**Comment by sdmaclea** [comment]
I was think `clrmd` needed `MachOCpuArch` & `MachOCpuType` too for completeness, but it is probably not required to unblock SOS.

**Comment by sdmaclea** [comment]
> MachOFat binaries yet. Is that going to be important?

Eventually it will be important.  We haven't decided whether we will support for .NET 6 yet though.  Current plan doesn't include universal binaries, but it may change in a month.

**Comment by leculver** [comment]
I'm using this issue to track completing Mac OS X support for all scenarios.  This will be my next major project in ClrMD aside from bugfixes.

**Comment by k15tfu** [comment]
@leculver Hi! I made changes for macOS support (both, x64 and ARM64) to be able to walk through the stack frames using `EnumerateStackTrace()`. Could you please review #915, #916, and #917?

**Comment by k15tfu** [comment]
@leculver Hi! Can you please release a new package with these changes?

**Comment by leculver** [comment]
Hello!  I plan to release a package next week that includes these changes and Mach-O coredump support.

Thanks!

**Comment by leculver** [comment]
> @leculver Hi! Can you please release a new package with these changes?

New package is listed here:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.226401

Mach-O support is not yet implemented though.  =(

**Comment by leculver** [comment]
AFAIK we are complete with full OS-X support.  I'm closing this general issue.  If any problems are found please file a new, more specific issue with details.
