### ISSUE TITLE
Interop interfaces

### ISSUE THREAD

**Issue by zodiacon** [Microsoft/clrmd#9]
Hi,

I'm using the debug engine interop interfaces (as well as CLRMD) and some methods accept IntPtr instead of the "proper" interface (e.g. IDebugClient.SetEventCallbacks). I've tried to replace the IntPtr with the "real" interface and use it - and it works just fine (maybe adding MarshalAs with Unmanaged.Interface for safety... but it works regardless).
Would it be possible to set the interfaces? I can certainly do that.
Is there a reason to not do it?
  
  Pavel

**Comment by leculver** [comment]
Thanks for the report!

I begun the work to change those from IntPtr over to the real interfaces yesterday, but I see I missed a few.  I just fixed the remaining ones I could find.  Please report any more issues like this (or send a pull request if you have the interest in fixing them yourself).

> Is there a reason to not do it?

Nope!  These should definitely be the real interfaces and not IntPtr.  Originally the interfaces here came from another team within Microsoft who used them slightly differently.  I hadn't gotten around to updating them until this week.

Thanks!
-Lee Culver
