### ISSUE TITLE
CreateSnapshotAndAttach does not kill the created process

### ISSUE THREAD

**Issue by jairbubbles** [microsoft/clrmd#925]
I would expect calling `Dispose` on the returned target to kill the suspended process created by `CreateSnapshotAndAttach`.

The problem can be seen with this simple sample:
```csharp
static void Main()
{
    for (int i = 0; i < 10; i++)
    {
        using var dt = DataTarget.CreateSnapshotAndAttach(Process.GetCurrentProcess().Id);
    }
}
 ```

 If you break on the last line you can see that the 10 processes are still there: 
 
![image](https://user-images.githubusercontent.com/15875066/118992236-be08c700-b984-11eb-8f2f-ad8dc7a346e5.png)

While looking at the code, I noticed that adding in `WindowsProcessDataReader.Dispose`   

```csharp
Process.GetProcessById(ProcessId)?.Kill();
```
does fix the issue.

I'd be happy to propose a PR!

**Comment by jairbubbles** [comment]
It looks like the kill was removed in https://github.com/microsoft/clrmd/pull/903

**Comment by leculver** [comment]
Sorry for the delay, I've been working on other projects.  I have a small issue on the PR to resolve.

**Comment by isaevdan** [comment]
@leculver @jairbubbles can you please tell if this is released? I see that the latest version is 2.0.226801 and was released 3 months ago, and looks like fix was done later

**Comment by jairbubbles** [comment]
It doesn't seem so indeed. A simple workaround is to manually kill the process.

**Comment by isaevdan** [comment]
On our case we want to dump thread stack traces into logs whenever we identify that our process is in deadlock in production environment. So this might be problematic there. Is there any plans to release this functionality?

**Comment by jairbubbles** [comment]
I'm just a dev there 😁, only @leculver can answer!

**Comment by isaevdan** [comment]
Got it, anyway thanks for reply :)

**Comment by kierenj** [comment]
My implementation of this - doesn't need modifying the source, but is super hacky:

````c#
                if (target.DataReader.GetType().Name == "WindowsProcessDataReader")
                {
                    var val = int.Parse(target.DataReader.DisplayName["pid:".Length..], System.Globalization.NumberStyles.HexNumber);
                    var proc = Process.GetProcessById(val);
                    if (proc.ProcessName == thisProc.ProcessName)
                    {
                        try { proc.Kill(); } catch { }
                    }
                }
````
