### ISSUE TITLE
ClrMD 2  heap.EnumerateRoots() get hangs

### ISSUE THREAD

**Issue by MaheshGpillai** [microsoft/clrmd#928]
I am using latest ClrMD for finding managed process live objects as below

but always it gets hang in  heap.EnumerateRoots() .

when I am using older versions 1 this issue is not there

**Comment by leculver** [comment]
I will need a repro or example to make progress here.  I'm closing old bugs which aren't actionable.  If this is still an issue for you, please let me know and I'll reopen.
