### ISSUE TITLE
[Question] How can I get the CustomAttributes for a method?

### ISSUE THREAD

**Issue by Ruikuan** [microsoft/clrmd#970]
Sorry about this silly questions.

Assuming we have a method defined as below.
```cs
public class SomeClass
{
    [My("beautifulName")]
    public void DoSomeThing()
    {
         // whatever.
    }
}

public MyAttribute : Attribute
{
    public string Name { get; init; }
    public MyAttribute(string name) => Name = name;
}
```
Now we got a memory dump of this application, we can use ClrMD to find the `SomeClass` type easily, then we can easily find the `DoSomeThing` ClrMethod. Now, how can I find the corresponding `MyAttribute` instance and get the `beautifulName` value?

Thanks for any helping!

**Comment by MSDN-WhiteKnight** [comment]
Custom attributes are a metadata thing, you need to get your hands on the assembly that houses SomeClass and inspect it somehow. Ideally you could use System.Reflection.Metadata or System.Reflection.MetadataLoadContext for this. In the simplest case, if the assembly is available as file under the same location as in the dumped process and you can afford to load it for execution, standard reflection also does it:


        static void PrintName(ClrMethod m)
        {
            ClrType t = m.Type;
            ClrModule module = t.Module;
            string path = module.Name;
            Assembly moduleAssembly = Assembly.LoadFrom(path);
            MethodBase mi = moduleAssembly.ManifestModule.ResolveMethod(m.MetadataToken);
            string attrName = mi.GetCustomAttribute<MyAttribute>().Name;
            Console.WriteLine(attrName);
        }

**Comment by Ruikuan** [comment]
Thank you for your help! @MSDN-WhiteKnight  
Can we load Assembly from some segment of the dump itself? It would be great if the tool doesn't have to depend on the location of the assembly dlls.
I will figure out how to inspect the metadata in the dump,  hopefully I can start from `MetadataLoadContext`. The information about this part is rare.

**Comment by MSDN-WhiteKnight** [comment]
You can use DataTarget.DataReader.Read to get assembly image as byte array. I have example here: https://github.com/MSDN-WhiteKnight/CilTools/blob/e1d48edf8013cb21ac6b5be9a794301fd55b3147/CilTools.Runtime/ClrAssemblyReader.cs#L559 , but it uses ClrMD 1.1 which had DataTarget.ReadProcessMemory instead.

Not sure whether MetadataLoadContext would be able to handle assembly image loaded this way, as it has different layout than assembly file. System.Reflection.Metadata will handle it if you pass it into [PEReader](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.portableexecutable.pereader?view=net-6.0) with PEStreamOptions.IsLoadedImage set to true.

**Comment by Ruikuan** [comment]
Thank you @MSDN-WhiteKnight for your awesome example and explanation.   
Actually I am not very familiar with these concepts here. I will follow your example carefully to see if I can complete this task.  
Will post the result here if I can achieve it.
Thank you again!

**Comment by leculver** [comment]
Looks like this question was answered, thanks!
