### ISSUE TITLE
Cannot implement ClrType

### ISSUE THREAD

**Issue by sharwell** [Microsoft/clrmd#98]
The property `GCDesc` is `internal abstract`, preventing external code from implementing the rest of `ClrType`.

https://github.com/Microsoft/clrmd/blob/6735e1012d11c244874fa3ba3af6e73edc0da552/src/Microsoft.Diagnostics.Runtime/ClrType.cs#L228

**Comment by leculver** [comment]
GCDesc is now public, thank you!
